### ISSUE TITLE
Potential reflect issue: DynamicStruct not registered

### ISSUE THREAD

**Issue by raffaeleragni** [bevyengine/bevy#10086]
## Bevy version

version: current main branch

## What you did

While migrating my crate to the current bevy main, I am facing the current error: "No registration found for bevy_reflect::DynamicStruct" when deserializing a reflected component.
This worked in bevy 0.11.

The current branch where I'm working, and my test failing is: https://github.com/raffaeleragni/bevy_sync/blob/bevy_0_12/src/proto_serde.rs#L122

**Comment by alice-i-cecile** [comment]
@MrGVSV I don't follow exactly what's going on / broke here, but this looks like a regression.

**Comment by MrGVSV** [comment]
Yeah this seems to be an issue with the recent changes to how `TypePath` is used in the reflection serializer. I'll make a PR!

**Comment by MrGVSV** [comment]
I should make a note, though, that this only applies to top-level dynamic types. Attempting to serialize a field that is a dynamic type is currently not allowed (or should be if it isn't). 

This is because of the fact that the top-level type is always serialized as a map of its type path to its value. Whereas fields do not contain any self-describing type information. Because of this, we couldn't possibly deserialize a value accurately (i.e. is `123` an `i32` or a `u32`?).

This is also why dynamic types need to be proxied in order to be serialized— they need a type to describe themselves as representing!
