### ISSUE TITLE
issue with shape::plane uv or indices order

### ISSUE THREAD

**Issue by trashuj** [bevyengine/bevy#1018]
**Bevy version**
commit 1398d7833007e85198cfd35d5fabc70b51b4db31 (HEAD -> master, origin/master, origin/HEAD)
Author: Corey Farwell <coreyf@rwell.org>
Date:   Fri Dec 4 17:31:17 2020 -0500

    Allow windows to maximized. (#1004)

**Operating system & version**
Windows 10

**What you did**
Display a texture on a shape::Plane.
I modified the 3d_scene.rs to create a simple example (in zip file):
[shape.zip](https://github.com/bevyengine/bevy/files/5649745/shape.zip)

**What you expected to happen**
Looking at the original png ("textures/rpg/mobs/boss_bee.png"), we can see it's mirrored, ie it looks like we would look at it from the bottom except we look at it from the top (hope that makes sense)

**What actually happened**
texture is flipped

**Additional information**
I tried playing with the uv and indices order in shape.rs / struct Plane, but i'm not sure what is the global logic (are the indices wrong or UV?).
Also note that shape::Quad version is correct.

**Comment by FrankenApps** [comment]
Could you maybe upload the whole project?
I tried running your sample but it doesn't even include a `main` function.

**Comment by trashuj** [comment]
Hi, sorry, for some reason the modified 3d_scene was not attached.
Here it is. Notice how the png is mirrored (without using the modified shape.rs, just copy this over the existing 3d_scene.rs example)

[3d_scene.zip](https://github.com/bevyengine/bevy/files/5764411/3d_scene.zip)

**Comment by cart** [comment]
Yup that definitely looks flipped to me!

**Comment by FrankenApps** [comment]
I have looked into that, because I have experienced weird UV-Mapping for Boxes and Cubes. I would be willing to fix this, however I would need to know as @trashuj noted if the UVs or the indices are wrong. 
I have also compared the setup to Threejs [here](https://jsfiddle.net/FrankenApps/wvfn1grb/20/) for reference:
<img width="511" alt="Bildschirmfoto 2021-01-05 um 11 55 22" src="https://user-images.githubusercontent.com/17967303/103638611-73def600-4f4d-11eb-8d07-6872b3a69954.png">
<img width="1269" alt="Bildschirmfoto 2021-01-05 um 10 53 28" src="https://user-images.githubusercontent.com/17967303/103638625-77727d00-4f4d-11eb-9585-fd60826c7836.png">
The bevy scene implementation I used for testing can be found [here](https://github.com/FrankenApps/bevy/blob/uv-testing/examples/3d/3d_scene.rs).

**Comment by wmbest2** [comment]
Running into this as well. I'm playing with building out quads by hands for voxel chunks and wanting to use a generated texture atlas, so having the UVs be intuitive would be very helpful.

Curious if you think this will be addressed as part of the v0.6 graphics pipeline changes @cart or if the best solution here is to just invert the UVs (I believe subtracting them from 1 should do the trick but haven't tested).

**Comment by cart** [comment]
This won't be directly addressed by graphics pipeline changes. But this definitely seems like something that should be fixed. We should do a quick comparison to other applications like godot + blender just to make sure we're aligning to the ecosystem. Whoever wants to pick this up is welcome to do it!

**Comment by wmbest2** [comment]
I'm relatively new to rendering, but I found several supporting posts with what I had assumed might be the issue. I assume that when we load the images we are loading them the standard 0,0 at the top left position. However OpenGL (and I assume SPIRV) assumes UV originates at the bottom left of the image. 

The options seem to be:
* Flip the image during load so that the texture itself is flipped in memory
* Flip the UVs (or really V I suppose) in the shader so that the image remains the same but the UVs are correct

I wanted to toss this out here as rust's image library does have a `::flip_vertical()` method which could be used when loading the texture. But I was almost certain this would have implications on the 2D render side.

Again, I want to caveat that this is pretty new to me, so I didn't want to go proposing changes collecting concerns first.

__Posts__
https://gamedev.stackexchange.com/questions/140789/texture-coordinates-seem-to-have-flipped-or-incorrect-position
https://learnopengl.com/Getting-started/Textures
![image](https://user-images.githubusercontent.com/74319/117353892-5592f380-ae76-11eb-93e0-228b3f3db66c.png)
https://www.reddit.com/r/opengl/comments/6mon2j/how_do_you_deal_with_images_being_inverted/

**Comment by cart** [comment]
wgpu is "top left y down" for images afaik (same as vulkan and metal). I don't think we should try to change that (or flip things on load). Images are also generally defined this way. I think we need to account for this solely in the uvs we generate for our meshes.

**Comment by wmbest2** [comment]
Ah, indeed that's where my limited knowledge was likely getting in the way. Looks like metal is also the same. Understanding that UV coordinates in this renderer are top left helps immensely. 

I'm assuming for model loading, e.g. `.obj` files, we would need to correct that during asset loading. 

In either case I think this should be enough to correct my understanding. I may add a note to the bevy cheatbook regarding UVs.
