### ISSUE TITLE
Distortion on high values of transform translate

### ISSUE THREAD

**Issue by numfin** [bevyengine/bevy#10443]
## Bevy version

Bevy: 0.12

Relevant system information

- cargo 1.75.0-nightly
- nixos 23.05

```ignore
`AdapterInfo { name: "NVIDIA GeForce RTX 3070", vendor: 4318, device: 9348, device_type: DiscreteGpu, driver: "NVIDIA", driver_info: "535.113.01", backend: Vulkan }`
```

## What you did

After moving forward with my character, picture/mesh (whatever you call it) becomes distorted.

![image](https://github.com/bevyengine/bevy/assets/8134947/ca605696-4278-42f6-a09a-ca64479afc52)

My first attempt was to solve it [like here](https://github.com/Jondolf/bevy_xpbd/issues/211#issuecomment-1789342920) and jittering was solved. But later I tried to test high translation values and picture become really distorted

## What went wrong

- I expected normal picture
![image](https://github.com/bevyengine/bevy/assets/8134947/81a3afae-332d-4423-9fc0-c69b68cb4a15)

- Picture become completely distorted

## Additional information

- [https://github.com/Jondolf/bevy_xpbd/issues/211](https://github.com/Jondolf/bevy_xpbd/issues/211)
- People in discord think this is about float precision
- I can show demo in realtime in discord if you want
- Camera projection doesn't fixing it
- Also it doesn't matter if camera following character or not in realtime

**Comment by superdump** [comment]
@aevyrie

**Comment by Rigidity** [comment]
Hello, I've noticed this issue occurring in my game at coordinates as low as 20,000. It gets worse at 100,000 and the game becomes unplayable as you get closer to 1,000,000 from the origin.

**Comment by aevyrie** [comment]
This is caused by limited precision of 32bit floats. This is why most game engines only support maps that are a few kilometers across. Unreal, for example, has a maximum world size of 20km x 20km. In your example, you are 100,000km from the origin, which is 10,000 times further away.

This happens because floating point numbers have variable precision, and a fixed amount of space to store the number (32 bits). As the number gets larger, there are effectively less bits available to the right of the decimal place.

Small number with 10 digits has 9 decimal places: 0.123456789

Large number still only has 10 digits, so it ends up with only a single decimal place: 123456789.0

Floating point is base two and more similar to scientific notation, so this explanation isn't entirely accurate, but it hopefully explains the "why".

Common solutions to this are floating origins and/or double precision coordinates. There are many ways to solve this problem, all with different tradeoffs. I've made a bevy plugin that solves this problem using an integer grid and a floating origin: https://github.com/aevyrie/big_space

**Comment by numfin** [comment]
@aevyrie nice workaround. But feels like there should be tools/api available out of the box in bevy.
Also what are the tradeoffs?
