### ISSUE TITLE
`SceneSpawner::spawn_dynamic` doesn't hold the handle after 0.12

### ISSUE THREAD

**Issue by Shatur** [bevyengine/bevy#10482]
## Bevy version

0.12

## What you did

On 0.11 the following code worked just fine:

```rust
let mut scenes = app.world.resource_mut::<Assets<DynamicScene>>();
let scene_handle = scenes.add(dynamic_scene);
let mut scene_spawner = app.world.resource_mut::<SceneSpawner>();
scene_spawner.spawn_dynamic(scene_handle);
```

But after 0.12 the code fails to spawn the scene. It's because I need to call `.clone()` on `scene_handle`, otherwise the handle will be dropped. I would expect scene spawner to hold the handle when I call `spawn_dynamic`.

**Comment by cart** [comment]
Hmmm yeah we moved to AssetId  (effectively a weak handle) across the board for SceneSpawner in Bevy Asset V2, the idea being that we shouldn't be keeping scene assets alive for already spawned scenes. Although I do think it makes sense to use strong handles for scenes queued to be spawned. So we should "unmigrate" the "queuing" portion of this api.

We haven't hit this issue for things like `SceneBundle` because it holds the strong handle.
