### ISSUE TITLE
serde Serialize and Deserialise on shape types

### ISSUE THREAD

**Issue by ActuallyHappening** [bevyengine/bevy#10626]
## What problem does this solve or what need does it fill?

I am wanting ot efficiently sync data between server and client. Since `Mesh` is not (and should not) implement serialise, I am using a custom enum. I wanted this enum to have variants like `Prism(shape::Box)` but I found out `shape::Box` doesn't implement serialise and deserialise.

## What solution would you like?

#[cfg_attr("serialize-serde", derive(Serialize, Deserialize)] on all of the shapes

## What alternative(s) have you considered?

Currently I can manually store the underlying types

## Additional context

Thanks so much for bevy! Its awesome to have fun with :)

**Comment by Kanabenki** [comment]
That could also be done for the [shapes types](https://github.com/bevyengine/bevy/tree/main/crates/bevy_math/src/primitives) recently added in `bevy_math`.

**Comment by ActuallyHappening** [comment]
> That could also be done for the [shapes types](https://github.com/bevyengine/bevy/tree/main/crates/bevy_math/src/primitives) recently added in `bevy_math`.

Bevy-math looks cool but I've never heard of it until now, is it supposed to replace bevy::prelude::shape in a future release? (I've only briefly looked myself, doesn't parry support these basic shapes?) it would be cool to have more expressive shapes in the future

**Comment by Jondolf** [comment]
> is it supposed to replace bevy::prelude::shape in a future release

For the most part, yes. The high-level goal is to have a nice set of primitive shapes that are reusable and interoperable across Bevy's own crates and 3rd party plugins, so they could be used for mesh creation, rendering shapes via gizmos, collider shapes, raycasting, bounding volumes, some rendering things, and so on. This is unlike the existing shapes in `bevy_render` that are specific to meshes (e.g. IcoSphere and UVSphere with subdivision counts instead of a simple Sphere with a radius).

- [RFC](https://github.com/bevyengine/rfcs/blob/main/rfcs/12-primitive-shapes.md)
- Initial PR: #10466
- Tracking issue: #10572

> doesn't parry support these basic shapes?

Yes, but we don't want to depend on Parry and bring Nalgebra to the dependency tree. We also might need to have more control over the shape representations so that they are as efficient and general-purpose as possible while being ergonomic to use.

And yes, implementing `Serialize`/`Deserialize` for the primitive shapes could be useful :)

**Comment by ActuallyHappening** [comment]
> > Since Mesh is not (and should not) implement serialise, I am using a custom enum.
> 
> Why shouldn't it implement serialize?

I guess it's entirely possible, I just looked at it and saw it was complicated with only private fields. Maybe upholding invariants? It would be great, actually, if `Mesh` would be serializable.

**Comment by BD103** [comment]
At this point, all of the primitives within `bevy_math` now implement `Serialize` and `Deserialize` behind a feature flag. (And the old shapes have been removed.) Marking as closed :)
