### ISSUE TITLE
Use lld only for debug build

### ISSUE THREAD

**Issue by morr0ne** [bevyengine/bevy#1062]
While being much faster lld produces measurably bigger and slower binaries.
I suggest changing https://github.com/bevyengine/bevy/blob/master/.cargo/config_fast_builds to only use lld in target.dev

**Comment by Moxinilian** [comment]
I believe, because of higher performance needs, some people are using release builds to do iterative work as well.
Maybe providing documentation on actually release builds would be nice? Like a general thing on how to correctly publish for all supported platforms.

**Comment by smokku** [comment]
Are such measurements available online?

**Comment by morr0ne** [comment]
> Are such measurements available online?

Regarding size just building small projects, size goes from 500kb to 700kb, regarding speed I've seen some small but measurable differences in some of my projects but I don't have enough knowledge of rust to build proper benchmarks.

This kind of problems are not rust related as the same difference can be observed by building c project using the gnu toolchain vs clang.

While the speed improvements are really nice I believe that for production build we'd want as much optimization as possible

>I believe, because of higher performance needs, some people are using release builds to do iterative work as well. But maybe specifying the opt-level is enough, in that case, I am not sure.

Maybe a disclaimer stating these tradeoffs and letting the user decide whether or not they are worth it

**Comment by morr0ne** [comment]
I closed the issue accidentaly 😅

**Comment by memoryruins** [comment]
This is the first time I've heard of this and haven't noticed it in projects so far. 

> measurable differences in some of my project

Could you post reproductions of this and list the native linker it is being compared to?

If something is notable enough, it may be worth mentioning in one of the rust issues related to https://github.com/rust-lang/rust/issues/39915, which aims to make lld the default linker on multiple platforms for both debug and release builds.

**Comment by morr0ne** [comment]
I never heard of lld before this project so I didn't do extensive testing. I tried switching all my projects to lld hoping for faster compile times and noticed the same behavior. Almost no improvements to build times and larger binaries.
Switching to lld in https://github.com/morr0ne/leech gave me the following results:

### Without lld enabled
rlib 689,9 KiB
binary 1,5 MiB
build time 1m 4s

### With lld enabled
rlib 725,7 KiB
binary 1,6 MiB
build time 1m 6s

I made a https://github.com/morr0ne/leech/tree/lld so that it can be tested on other machines

**Comment by Puciek** [comment]
That's a weird result, but then it doesn't show the binaries to be slower as 1 second difference is so tiny it's likely due to randomness. The size is definitely bigger, though the biggest benefit from going LLD is kicking in when cargo is spending a lot of time in linking, and I guess in your example it's not doing that.

I tried to reproduce them locally on Threadripper 1950x running at 4.0GHZ and m.2 drive:

`cargo build` with LLD: Finished dev [unoptimized + debuginfo] target(s) in 28.78s
`cargo build` without LLD: Finished dev [unoptimized + debuginfo] target(s) in 28.70s

`cargo build --release` with LLD: Finished release [optimized] target(s) in 50.71s
`cargo build --release` without LLD: Finished release [optimized] target(s) in 51.16s

I ran them few times and the difference was never bigger than a second either way around (except for one very odd run that suddenly took +20 seconds). The binary size is bigger, yep, but I don't see how LLD will hurt you, and the bigger your project gets, the more you can possibly get out of it, that's also why RUST is slowly switching over to it.

**Comment by morr0ne** [comment]
I definitely agree that the 1 second difference is not an actual problem but since the size different is measurable I feel like a disclaimer at least is necessary

**Comment by Puciek** [comment]
Not against that idea, especially if it also includes some examples. But you've also mentioned that it creates slower binaries, is there anything concrete for it?

**Comment by morr0ne** [comment]
Yeah regarding slower binaries might just have been my imagination or isolated cases, I noticed when messing around with some computation heavy task but I have literally zero knowledge of benchmarking to how to setup testes in rust so I wouldn't know how to reproduce or even if those claims are valid also, I don't know why lld binaries are bigger so for all I know they could even be faster

**Comment by bjorn3** [comment]
> ### Without lld enabled
> 
> rlib 5,3 MiB
> binary 4,30 MiB
> second binary 5,0 MiB
> build time 6m 20s
> ### With lld enabled
> 
> rlib 5,7 MiB
> binary 4,35 MiB
> second binary 4,9 MiB
> build time 6m 21s

I think lld enabled or not is not the only variable between the two tests. The rlib size can not be influenced by the used linker. Creation of rlibs doesn't involve linking anything. Rlibs are one of the inputs of a linker invocation at some point in the future.

**Comment by morr0ne** [comment]
I'm gonna go ahead and close this, perhaps this can be investigated again in the future
