### ISSUE TITLE
Race condition in assets loading

### ISSUE THREAD

**Issue by Shatur** [bevyengine/bevy#10688]
## Bevy version

0.12

## What you did

My game have a plugin that generates preview images for buttons from 3D models. And I migrated from 0.11 to 0.12.

## What went wrong

I noticed that my preview generation plugin sometimes generates empty images. I looked into it deeper and discovered that `AssetServer` sometimes returns `LoadState::Loaded` too early.

## Additional information

I managed to extract and simplify this logic into a minimal project that reproduces the issue: [assets_render.zip](https://github.com/bevyengine/bevy/files/13432070/assets_render.zip)

If you run it, you will see that some generated images are empty (sometimes happens on second run on my machine, but usually always happen):
![image](https://github.com/bevyengine/bevy/assets/22453358/7b443c5f-da35-4d7f-bb80-0472d1d38b9d)

If you disable `multi-threaded` feature in `Cargo.toml`, all images will be rendered correctly:
![image](https://github.com/bevyengine/bevy/assets/22453358/4fc6f8f4-bad7-4f11-b6e7-2d18291de9f3)

**Comment by cart** [comment]
I can repro on my machine.

> I noticed that my preview generation plugin sometimes generates empty images. I looked into it deeper and discovered that AssetServer sometimes returns LoadState::Loaded too early.

I don't think this is true. From what I'm seeing in your app / my tests, whenever LoadState::Loaded is set, the asset is available. Ex: if I read the asset data from `Assets<Scene>` in `loading_system`, the scene is there. Do you have a test that indicates otherwise?

I think this is likely a _rendering_ delay, not an asset system delay. Looks like your app operates under the assumption that  it can spawn a scene, wait for the asset to load and create a camera/render on frame X, cleanup on frame X+1, and then restart the process. I'm guessing theres something preventing the spawned scene from rendering immediately on frame X.

I _do_ think this pattern should work in Bevy (ex: be able to easily and predictably know when a scene is ready for render). Just want to make sure we're solving the right problem.

**Comment by cart** [comment]
One issue with the pattern you are using: `LoadState::Loaded` is an indicator of the top level referenced asset itself being loaded. `RecursiveDependencyLoadState::Loaded` is an indicator of all dependencies (including recursive dependencies) being loaded. You can check both for a combined "loaded with recursive dependencies".

If the goal is to know when a scene is "fully ready", you should be checking both. Alternatively, you can just listen for `AssetEvent::LoadedWithDependencies`, which is fired when the asset and its dependencies are loaded.

However even when adapted to use that event, it still doesn't always load.

I have more confirmations of the theory in the previous post:

I've constrained the example to only 4 items for easier debugging. In this case, the bench asset fails to load:

![image](https://github.com/bevyengine/bevy/assets/2694663/0476a5a0-7ad5-4c2c-b662-36f3ad8ed30e)
 
```
2023-11-23T04:06:03.180682Z DEBUG assets_render::preview: loading asset for preview Some(foliage/simple_bush/simple_bush.gltf#Scene0)
Not actually ready Some(foliage/simple_bush/simple_bush.gltf#Scene0)
2023-11-23T04:06:03.332004Z DEBUG assets_render::preview: asset for preview was sucessfully loaded: Some(foliage/simple_bush/simple_bush.gltf#Scene0)
Scene { world: World { id: WorldId(7), entity_count: 5, archetype_count: 9, component_count: 11, resource_count: 0 } }
Spawned Some(foliage/simple_bush/simple_bush.gltf#Scene0)
2023-11-23T04:06:03.339946Z DEBUG assets_render::preview: rendering preview
skipping 1v0 because of missing material instance
finish
rendering 16v0
2023-11-23T04:06:03.370838Z DEBUG assets_render::preview: loading asset for preview Some(outdoor_furniture/classic_bench/classic_bench.gltf#Scene0)
skipping 1v0 because of missing material instance
skipping 17v0 because of missing material
Not actually ready Some(outdoor_furniture/classic_bench/classic_bench.gltf#Scene0)
2023-11-23T04:06:03.687814Z DEBUG assets_render::preview: asset for preview was sucessfully loaded: Some(outdoor_furniture/classic_bench/classic_bench.gltf#Scene0)
Scene { world: World { id: WorldId(8), entity_count: 37, archetype_count: 9, component_count: 11, resource_count: 0 } }
Spawned Some(outdoor_furniture/classic_bench/classic_bench.gltf#Scene0)
2023-11-23T04:06:03.701938Z DEBUG assets_render::preview: rendering preview
skipping 1v0 because of missing material instance
finish
skipping 1v0 because of missing material instance
skipping 32v0 because of missing material
skipping 33v0 because of missing material
skipping 34v0 because of missing material
skipping 35v0 because of missing material
skipping 36v0 because of missing material
skipping 37v0 because of missing material
skipping 38v0 because of missing material
skipping 39v0 because of missing material
skipping 40v0 because of missing material
skipping 41v0 because of missing material
skipping 42v0 because of missing material
skipping 43v0 because of missing material
skipping 44v0 because of missing material
skipping 45v0 because of missing material
skipping 46v0 because of missing material
skipping 47v0 because of missing material
skipping 48v0 because of missing material
skipping 49v0 because of missing material
2023-11-23T04:06:03.721036Z DEBUG assets_render::preview: loading asset for preview Some(rocks/medium_stone/medium_stone.gltf#Scene0)
Spawned Some(rocks/medium_stone/medium_stone.gltf#Scene0)
2023-11-23T04:06:03.729398Z DEBUG assets_render::preview: asset for preview was sucessfully loaded: Some(rocks/medium_stone/medium_stone.gltf#Scene0)
Scene { world: World { id: WorldId(6), entity_count: 3, archetype_count: 9, component_count: 11, resource_count: 0 } }
skipping 1v0 because of missing material instance
2023-11-23T04:06:03.737359Z DEBUG assets_render::preview: rendering preview
finish
skipping 1v0 because of missing material instance
rendering 49v1
2023-11-23T04:06:03.746069Z DEBUG assets_render::preview: loading asset for preview Some(decorations/mirror/mirror.gltf#Scene0)
Spawned Some(decorations/mirror/mirror.gltf#Scene0)
2023-11-23T04:06:03.962403Z DEBUG assets_render::preview: asset for preview was sucessfully loaded: Some(decorations/mirror/mirror.gltf#Scene0)
Scene { world: World { id: WorldId(5), entity_count: 3, archetype_count: 9, component_count: 11, resource_count: 0 } }
2023-11-23T04:06:03.970165Z DEBUG assets_render::preview: rendering preview
skipping 1v0 because of missing material instance
skipping 1v0 because of missing material instance
rendering 49v2
finish
```
Note that nothing was rendered for the bench and a lot of entities were skipped for missing materials / material instances.

Also note that the leaves on the bush didn't render for the same reason.

**Comment by Shatur** [comment]
> Do you have a test that indicates otherwise?

Honestly no, it's was just my assumption. It worked on 0.11, and since asset system heavily changed I assumed that this could be the case.

> RecursiveDependencyLoadState::Loaded

Didn't know about it, will check it too.

> AssetEvent::LoadedWithDependencies

In my game asset could already be spawned (e.g. loaded), this is why I check it like this.

So looks like the scene spawned partially? This is interesting.

**Comment by cart** [comment]
>   Didn't know about it, will use it too. With checking RecursiveDependencyLoadState additionally to LoadState the code will be a bit messy...

Yeah a combined state seems reasonable.

> So looks like the scene spawned partially? This is interesting.

I'm pretty sure the scene is fully spawned, given that we are _trying_ to render the things that aren't showing up (and skipping them because of missing GPU-side materials). I strongly suspect it would fully render if given a couple more frames. That being said, I still consider this a bug to be fixed (somehow). Easily determining when a scene will be fully rendered is important.

**Comment by cart** [comment]
Ok found the fix! It actually wasn't a bug in the renderer _or_ the assets system. It was an issue with how the GLTF loader constructs its scenes. The dependencies were being added to the top level GLTF instead of to the Scene sub-assets, meaning the scenes were entering the LoadedWithDependencies state "immediately" because there were no dependencies.

This is a reasonably straightforward fix. I have a hackey one put together to prove this works, but I'll come up with something a bit nicer.
