### ISSUE TITLE
Unexpected Pitch behavior on Ubuntu/Debian

### ISSUE THREAD

**Issue by dxtr85** [bevyengine/bevy#11067]
## Bevy version 
0.12
## \[Optional\] Relevant system information: 
Linux W540 5.10.0-26-amd64 #1 SMP Debian 5.10.197-1 (2023-09-29) x86_64 GNU/Linux, also confirmed to occur on unspecified Ubuntu setup. 

## What you did
I extended Pitch example provided in Bevy 0.12 release notes with keyboard input handling so that now only if I press a key the Pitch gets created and PitchBundle gets spawned into world.
In release notes there is a sentence "More complex sounds can be created by playing several pitch audio sources at the same time, like chords or hamonics."

## Code sample
```rust
use bevy::prelude::*;
use bevy::utils::Duration;

fn play_pitch_a(
    mut pitch_assets: ResMut<Assets<Pitch>>,
    mut commands: Commands,
    keyboard_input: Res<Input<KeyCode>>,
) {
    if keyboard_input.just_pressed(KeyCode::A) {
        let pitch_handle = pitch_assets.add(Pitch::new(220.0, Duration::new(1, 0)));
        commands.spawn(PitchBundle {
            source: pitch_handle,
            ..default()
        });
    }
}

fn play_pitch_b(
    mut pitch_assets: ResMut<Assets<Pitch>>,
    mut commands: Commands,
    keyboard_input: Res<Input<KeyCode>>,
) {
    if keyboard_input.just_pressed(KeyCode::O) {
        let pitch_handle = pitch_assets.add(Pitch::new(440.0, Duration::new(1, 0)));
        commands.spawn(PitchBundle {
            source: pitch_handle,
            ..default()
        });
    }
}

fn main() {
    App::new()
        .add_plugins(DefaultPlugins)
        .add_systems(Update, play_pitch_a)
        .add_systems(Update, play_pitch_b)
        .run();
}
```

## What went wrong

- what were you expecting?
I was expecting the frequency stay the same even if I trigger another PitchBundle with the same frequency value spawning while another one is still sounding.
In case of two Pitch instances with different frequency values playing simultaneously I was expecting to hear only those two defined frequencies.

- what actually happened?
But right now if I press a key while the Pitch is playing then I get some other, higher pitch for the time when the old pitch and the new one are being played (both with the same frequency). When old pitch is done playing the remaining pitch goes down in frequency to that which was defined when I created Pitch instance.
Also similar thing happens when I try to play two different Pitches (?) with not equal frequencies: when they overlap I get some unexpected high pitch and only when they don't overlap I can hear what was defined.

## Additional information

Please see following thread on Discord:
[Pitch audio source example from Bevy 0.12 release notes](https://discord.com/channels/691052431525675048/1187019275286884382)

**Comment by GitGhillie** [comment]
If I create two tracks in Audacity and do Generate > Tone (default settings) on each track then I get a similar distorted sound as what I heard when I tried code sample on my Ubuntu setup. Lowering the volume on both tracks in Audacity removes the distortion.

On Windows the code sample did not sound distorted. So I'm guessing on Windows there is some kind of compensation going on when the audio gets too loud. But I'm not an audio expert

**Comment by SolarLiner** [comment]
The reason this is happening on Windows is indeed that it is dynamically reducing the audio output when an application's audio signal is too loud. So the audio is scaled appropriately, but because it happens at the OS level, after mixing all audio from all applications, it will also reduce the audio level of other applications. The only correct solution is to plan how loud the signals will be and never going too loud (like having the 1/N solution described above). Note that the level reduction thing on Windows is a recent thing, I definitely used to get some distortion in the not so distant past, so it might be the case that on Windows 10 (as opposed to Windows 11), the audio still distorts.

There are dynamics control audio effects that can also be applied on Bevy's output, but unfortunately for now "master effects" are not possible to implement in `bevy_audio`.

Closing as wontfix (at least until we have proper audio processing infrastructure) / user error
