### ISSUE TITLE
order of commands.with(...) matters

### ISSUE THREAD

**Issue by fopsdev** [bevyengine/bevy#1120]
**Bevy version**
0.4
The release number or commit hash of the version you're using.
master 3b2c6ce4
**Operating system & version**
Win 10

**What you did**
Adding a Component (Empty Struct) to Example sprite,rs
```rs
...
commands
        .with(Sprite)
        .spawn(Camera2dBundle::default())
        ...
```
**What you expected to happen**
Sprite Component should be added

**What actually happened**
Panic

**Additional information**
It works when adding the 
```rs
.with(...)
```
at the end like:
```rs
    commands
        .spawn(Camera2dBundle::default())
        .spawn(SpriteBundle {
            material: materials.add(texture_handle.into()),

            ..Default::default()
        })
        .with(Sprite);
```

**Comment by cart** [comment]
Anything that uses `with_x` naming is a modifier on the "current" thing (in this case, an entity). This fails because there is no "current" entity. `spawn` is the command that creates a new entity / entity id, so we can't create the "with" command because the entity id hasn't been created yet. And semantically it has no meaning because the "X" in `X.with()` is undefined. 

We could consider adopting a "typed builder" pattern to only allow the correct call pattern, but this has implications for ergonomics because it requires the typed builder to "terminate" (which would mean adding a `.finish()` function call).

I'll leave this open for a bit in case anyone wants to respond, but I consider this to be the "expected / desirable" behavior.

**Comment by smokku** [comment]
We could add a more meaningful panic message though, suggesting what to do.

**Comment by cart** [comment]
Good call!

**Comment by smokku** [comment]
Current message is `"Cannot add component because the 'current entity' is not set. You should spawn an entity first."` which is fine I think.

Maybe `"Cannot add component because the 'current entity' is not set. You should use .spawn() method to create an entity first."`?

**Comment by fopsdev** [comment]
Or maybe adding it also to the "Warning" Section which is already discoverable by rust analyzer:
![image](https://user-images.githubusercontent.com/5448300/102865964-d0fb8780-4436-11eb-9323-a20ac4620b18.png)

**Comment by fopsdev** [comment]
though there are some more places where a method expects an existing entity...
not sure how to add this meta information to the method signatures without a lot of duplication

my vote: carts mentioned "typed builder" - pattern. i wouldn't mind adding a .finish() method to those candidates

On the other hand the panic msg is quite ok. together with the stack trace myself as a beginner was able to locate the issue.
so for sure not high prio :)

**Comment by smokku** [comment]
This panic is a small price to pay for not having to use `.finish()` every time you spawn an entity. And since this engine is ECS based, you deal with entity spawning _a lot_.

Like you mentioned, panic explains what you need to do, and in a moment it will be habit.

**Comment by fopsdev** [comment]
yes, i think we can close this. current behaviour is ok

**Comment by tripokey** [comment]
Isn't a finish() method on a typed builder that returns the created Entity better than having to do .current_entity().unwrap() everytime you need to get the created Entity?

Also a panic might happen during production so I think a design where a panic is not possible is vastly better.
