### ISSUE TITLE
Inconsistent use of tracing and bevy_log

### ISSUE THREAD

**Issue by BD103** [bevyengine/bevy#11298]
Bevy seems to inconsistently switch between using `bevy_utils::tracing` and `bevy_log`. It would be good to pick one and use it consistently throughout the project.

---

> Also it appears Bevy is using a mix of both `bevy_utils::tracing` and `bevy_log` for accessing logs. Interesting. Might wanna fix that sometime.
>
> _Originally posted by @doonv in https://github.com/bevyengine/bevy/pull/11296#discussion_r1448943630_

**Comment by james7132** [comment]
I'm generally for moving this all our tracing usage to bevy_utils, since bevy_log focuses on actually setting up the LogPlugin and the outward facing IO for tracing. This way compilation shouldn't be blocking on compiling bevy_log's extra features when most other crates are really only there to add log messages and instrumentation. 

However, the `*_once` macros are all in `bevy_log`, so unless we move those to `bevy_utils`, which we probably don't want to be doing (see #11478), so I'm fine with us going either way.

**Comment by mockersf** [comment]
an issue I have with using bevy_utils for logs is that it exposes [`bevy_utils::error`](https://docs.rs/bevy_utils/latest/bevy_utils/fn.error.html), [`bevy_utils::warn`](https://docs.rs/bevy_utils/latest/bevy_utils/fn.warn.html), [`bevy_utils::info`](https://docs.rs/bevy_utils/latest/bevy_utils/fn.info.html)  and  [`bevy_utils::dbg`](https://docs.rs/bevy_utils/latest/bevy_utils/fn.dbg.html) (somehow this one didn't get authorised for vowels) and those are not the same things as the log macros
