### ISSUE TITLE
Some examples are broken on web due to calling `argh::from_env()`

### ISSUE THREAD

**Issue by Elabajaba** [bevyengine/bevy#11503]
## Bevy version

Bevy main 02bf4efe64f2d10c8063edc760303e67e9b99e19 (haven't tried to bisect it)

## What you did

Build a bevy example that uses `argh::from_env()` (eg. many_foxes, bevymark, or many_cubes) targeting web (either webgl2 or webgpu).

## What went wrong

It panics on the call to `argh::from_env()` and fails to run.

**Comment by rparrett** [comment]
There's no for a fancy bisection. Any of the stress tests that make use of `argh` haven't worked on the web since that was added. Oops.

The most barebones/quick fix might be to use `let args = Args::from_args(&[], &[]).unwrap();` instead of `from_env`. The library sort of works on wasm, just not `from_env`.

Full list:
```
bevymark
many_buttons
many_cubes
many_foxes
text_wrap_debug
```
