### ISSUE TITLE
Asset loader error messages for unknown extension should point to requisite cargo feature

### ISSUE THREAD

**Issue by alercah** [bevyengine/bevy#11510]
## Bevy version

0.12

## What you did

I attempted to load a JPEG asset without the `jpeg` feature enabled.

## What went wrong

I received an error: `2024-01-24T16:46:41.664329Z ERROR bevy_asset::server: no `AssetLoader` found for the following extension: jpg`

There is no information on how to fix this error, but the fix is simple: enable the relevant cargo feature, in this case `jpeg`.

**Comment by BD103** [comment]
I feel like implementing this without hardcoding individual features' extensions would be very difficult. The point of features is that disabling them prevents them from ever being compiled, so `bevy_asset` wouldn't even know what a JPEG is.

**Comment by spectria-limina** [comment]
I have a [prototype](https://github.com/alercah/bevy/tree/assetfeature) to add generic hinting support to `AssetServer`, that `ImageLoader` automatically populates with hints for its missing extensions when it's loaded.

Limitations:

- Only supports one hint per missing extension (last one wins)
- Adds additional allocations and copies when loading an asset with more than one extension, where the full extension does not match a known `AssetLoader`. There are already spurious allocations/copies on this codepath, this patch just adds more.
- Only `ImageLoader` currently makes use of the missing extension list
- The feature->extension mapping currently needs to be written out twice, because my macro-fu is not good enough to do it only once.

With this prototype, the resulting message is `ERROR bevy_asset::server: no `AssetLoader` found for the following extension: jpg (try enabling bevy feature 'jpeg')`

**Comment by alercah** [comment]
I have a [prototype](https://github.com/alercah/bevy/tree/assetfeature) to add generic hinting support to AssetServer, that ImageLoader automatically populates with hints for its missing extensions when it's loaded.

Limitations:

    Only supports one hint per missing extension (last one wins)
    Adds additional allocations and copies when loading an asset with more than one extension, where the full extension does not match a known AssetLoader. There are already spurious allocations/copies on this codepath, this patch just adds more.
    Only ImageLoader currently makes use of the missing extension list
    The feature->extension mapping currently needs to be written out twice, because my macro-fu is not good enough to do it only once.

With this prototype, the resulting message is ERROR bevy_asset::server: no AssetLoader found for the following extension: jpg (try enabling bevy feature 'jpeg')

**Comment by alice-i-cecile** [comment]
Okay, that prototype is pretty neat. It gives good error messages and is surprisingly maintainable, which was by far my largest concern. Clean it up and PR it?

**Comment by reima** [comment]
Is this still relevant? It seems https://github.com/bevyengine/bevy/pull/13712 has already fixed this by issuing a warning for the missing feature flag.
