### ISSUE TITLE
Regression: Changing the Texture contents of a TextureHandle does not change the rendered texture on screen

### ISSUE THREAD

**Issue by jornvandebeek** [bevyengine/bevy#1161]
**Bevy version**

Current master (https://github.com/bevyengine/bevy/commit/4825051c6a2faf097ff3976db10e06b782f04056) and 0.4.0

**Operating system & version**

Windows 10 1909

**What you did**

I upgraded my code to Bevy 0.4.0.

**What you expected to happen**

Deferred texture generation should update a texture in my game a moment after starting. 

**What actually happened**

The texture as rendered on the screen did not change from the starting placeholder.

**Additional information**

I have made a minimal reproduction by altering the texture.rs example.

Changing the underlying texture of a handle [works in 0.3.0](https://gist.github.com/jornvandebeek/5a21118a8873a6ea7e5a782c0efa69ff).

But it is [broken in 0.4.0](https://gist.github.com/jornvandebeek/e345cb2fb7a2cbe54a3a39d6dc18e643)

Printing the contents of the texture underlying the handle after updating it does show the correct updated texture, but for some reason, it is not actually shown on the screen.

**Comment by mockersf** [comment]
I've had a similar issue in one of my project after updating to bevy 0.4:
1.  retrieve the component `Handle<ColorMaterial>` from an entity
2. retrieve the actual material from the handle
3. retrieve the `Handle<Texture>` from the material
4. retrieve the actual texture from the handle

In bevy 0.3, only step 4 needed a mut with a `ResMut<Assets<Texture>>`

In bevy 0.4, I had to make sure everything in the path was triggering mutable borrow to trigger a change. You can see the patch [here](https://github.com/vleue/bevmnist/commit/b0777ab9dd71726be098ec67e59a6b33c3a74909#diff-42cb6807ad74b3e201c5a7ca98b911c5fa08380e942be6e4ac5807f8377f87fcL338)

**Comment by jornvandebeek** [comment]
The ability to change a texture underlying a handle might simply not have been intentional. I have confirmed that replacing the `albedo_texture` on a material with a new texture handle does [work as expected in 0.4.0](https://gist.github.com/jornvandebeek/306c4d063c14a1fbe2bc8d1f26d6c5e0).

**Comment by tigregalis** [comment]
> 
> 
> The ability to change a texture underlying a handle might simply not have been intentional.

If it isn't intentional, I think it should be. Being able to draw to a texture, and display the updated texture, is used in the couple of bevy tilemap implementations I believe, and a game too: https://github.com/dmitriy-shmilo/sio2. It's also one of the examples (displaying the font atlas), which is now broken: #1243

**Comment by mockersf** [comment]
The issue is that when changing the `Texture`, the `ColorMaterial` used to display it doesn't pick up the change and isn't updated itself.

This is a common issue to all assets that can contain handles to other assets, and that need to be updated when their included assets are.

Short term fix would be to monitor the changes to `Texture` and trigger changes to related `ColorMaterial` but it adds complexity and overhead.
Long term fix (for rendered assets) would be to move to "pipelined" rendering where render state is separate from world state.

This would still be a potential issue for assets that are not rendered.
