### ISSUE TITLE
WebGL2: can't render StandardMaterial

### ISSUE THREAD

**Issue by mockersf** [bevyengine/bevy#12081]
## Bevy version

main since https://github.com/bevyengine/bevy/pull/11904

## \[Optional\] Relevant system information

This is on Wasm on WebGL2

## What you did

Try to run an example using `StandardMaterial` like `lighting` or `load_gltf`

## What went wrong

Nothing renders

**Comment by janhohenheim** [comment]
@superdump the error is  `drawElementsInstanced: Buffer for uniform block is smaller than UNIFORM_BLOCK_DATA_SIZE.`
Looks like our cool packing for `Affine2` is the problem, since the issue is gone if I pass a `Mat3` instead. What should I do about it? I see the following possibilities:
- Pass in a `mat3x3` all the time
- Pass in a `mat3x2` on non-webgl target and a `mat3x3` otherwise
- Do something about `UNIFORM_BLOCK_DATA_SIZE` (idk how)

**Comment by janhohenheim** [comment]
@mockersf if this is super important to fix ASAP, I can whip up a hotfix right now by passing slightly less optimized data structures to the standard material. Just let me know :)
