### ISSUE TITLE
Render world blocking certain ecs developments

### ISSUE THREAD

**Issue by Trashtalk217** [bevyengine/bevy#12144]
Currently, there are at least two worlds in any given bevy app, the 'normal' world and the render world. The render world is responsible for rendering a scene to the screen. To keep the two worlds in sync, all the entities of the render world are removed at the end of a frame and in the subsequent frame the render world is 'rebuilt'.

There are [plans for the ecs](https://github.com/bevyengine/bevy/discussions/6493) (mainly involving Relations) that hinge on more things becoming entities. As entities become more fundamental (components as entities, queries as entities), it becomes a problem when the render world removes all entities in every frame.

I'm mainly attempting to lift this problem from Discord (where it has been repeatedly discussed) to a slightly less transient and easier-to-read format.

If I got anything wrong, please tell me. While I think that this problem should be solved, it is sadly also a problem of which I don't know the full details.

**Comment by james-j-obrien** [comment]
Thanks for creating a place to track this.

The main issue is that the render world currently guarantees that extracted entities from the main world will be able to use the same `Entity` id in the render world. This forces all entity and component data to be dropped each frame to make room for the entities from the main world. This is primarily a problem as mentioned above for using the ECS storage for things like queries, systems and most importantly components which is a requirement for flecs-like fragmenting relations, a long term goal of the project.

Some proposed solutions include:
1. Stop deleting entities in the render world entirely, move to a resource based render world where extracted data is not store in entities at all.
2. Instead of ensuring ids match attach a `MainWorldEntity` component to render world entities to track the mapping and assign arbitrary ids. Then either:
  a. Persist entities in the render world, only despawning them when the corresponding entity is despawned.
  b. Despawn entities properly each frame (avoid using `SparseSet` components so entire tables can be dropped).
  
In my opinion 2b is the only option I'm currently aware of that doesn't require a huge rearchitecting of the renderer, however I am aware there are some who want to pursue 1 or 2a for performance reasons unrelated to the blocked entitification of the ECS. 

Regardless I think we are united in wishing to move away from the current model and I'll be happy wherever we end up.

**Comment by JMS55** [comment]
Additional constraint: The render world entity ID must be stable between frames. Lots of temporal rendering techniques require storing and retrieving data across multiple frames per entity.

**Comment by james-j-obrien** [comment]
> Additional constraint: The render world entity ID must be stable between frames. Lots of temporal rendering techniques require storing and retrieving data across multiple frames per entity.

Could you use the value from the component in the place of the actual entity ID?

Alternatively this does remind me of another implementation which is to split the address space and use a bit in the identifier to signify a foreign id. This involves a few intricacies with how high entity ids would interact with sparse sets and other ECS internals but we do need to resolve that for relations anyway.

**Comment by JMS55** [comment]
> Could you use the value from the component in the place of the actual entity ID?

What component? MainWorldEntity? Yes, so long as MainWorldEntity is stable across frames. I need to be able to do this basically:

```rust
// Resource
let mut last_frame_data_per_light = HashMap::new();

// Current frame
for entity in light_query {
     last_frame_data_per_light .insert(entity, foo);
}

// Next frame
for entity in light_query {
   last_frame_data_per_light .get(entity); // Need to know some info about the light stored from last frame
}
```

**Comment by superdump** [comment]
My main concern for the render app is performance. In one sense moving away from using the ECS for the main mesh entity flow has been freeing to use whatever we find works best. For me at least it lets me focus on the data and how best to structure and access it to achieve fast rendering, rather than being constrained by how the ECS works.

That said, if there were to be an ECS world shared between the apps so that we could avoid extraction and could access everything that we need, that certainly seems interesting.

And from the original post, 1 sounds ok, 2 sounds a bit clunky but could work.
