### ISSUE TITLE
Adding a `FlatSurface` or `Rect3d`

### ISSUE THREAD

**Issue by EmiOnGit** [bevyengine/bevy#12388]
## What problem does this solve or what need does it fill?
First of there are many names which describe this structure such as finite plane, bounded plane, flat surface or rect(3d). I'll go with rect3d for this post since it is the most intuitive to me.

Currently, there is no primitive buildin to express a rect in 3d space.
There are however usecases, such as:
* Using the rect3d to for raycasting/collision detection (imagine looking through a portal)
* Using the rect3d to describe a surface, such as a water surface
* Using the rect3d to create meshes.

The current alternative would be the [`Plane3d`](https://docs.rs/bevy/0.13.0/bevy/math/prelude/struct.Plane3d.html) which is describes a unbounded plane. Not quite what we need her but close.
I also believe that separating the abstraction of a infinite and finite plane is necessary to avoid confusion and unwanted sideeffects down the line. 
This topic has already been raised by @alice-i-cecile in this issue https://github.com/bevyengine/bevy/issues/12243

## What solution would you like?
A struct `Rect3d` 
implementing `Meshable` and being a Bounding volume

The actual name of the struct is open to debate

**Comment by andristarr** [comment]
This is both for the mesh and the math primitive, correct?

**Comment by alice-i-cecile** [comment]
Correct :)

**Comment by andristarr** [comment]
Looking into this!

**Comment by andristarr** [comment]
I started working on this but I am a tad bit confused. In #12243, it is said that we currently have plane as a finite plane, which is true, in our 3d primitives, the plane is defined with a size of vec2.

_Unless I missunderstood something_, we do miss a finite math primitive but not an actual mesh, because that one is derived from our current infinite 2d plane math primitive, so if I add a rect3d mesh and math primitive, we will end up having two finite ended plane primitive meshes. (plane3d and rect3d)

So I guess this work is a precursor to making plane3d to be an infinite plane primitive mesh, which would come later down the line? Want to make sure our intention is to end up with 2 finite primitive plane meshes at the end of this PR.

**Comment by alice-i-cecile** [comment]
We should remove the primitive plane mesh from `Plane` as part of this work :) Making it meshable (well, kind of) is much more complex and should be tackled independently.

**Comment by EmiOnGit** [comment]
I agree here with Alice. The current implementation of `Meshable` for `Plane3d` is already not right.
As `Plane3d` is infinite, therefore it should also represent a indefinitely large mesh (which is not how meshes usually work).

**Comment by Jondolf** [comment]
I do think that we need to make it easier/clearer how people can make bounded plane meshes, but:

- I don't love the name `Rect3d`. It's confusing considering we already have `Rect`, `URect` and `IRect` which are *not* primitives, and it's also inconsistent with the 2D primitive `Rectangle`. It should at *least* be `Rectangle3d` if we want to call it a rectangle, but then we'd need to rename *that* to `Rectangle2d`.
- A rectangle is a 2D shape. One defining factor of the primitives is that they should have no inherent configurable position or orientation outside of what is needed to represent the shape (like triangle points or a plane normal), or using `Transform` or separately allowing transformations for e.g. meshes. Otherwise, they wouldn't really be primitives. A normal is *not* something that mathematically defines a rectangle, so I wouldn't really consider `Rectangle3d` to be a geometric primitive, at least with that name.
- If it is a `Rectangle3d`, which direction is it facing by default? Up, like the default plane, which is probably what the main use case would be? This would be inconsistent with the 2D rectangle which should be facing +Z. I would expect the two rectangles to be the same by default.
- Having a 3D `Plane` mesh that is bounded *is very common*. For example, Godot, [Three.js](https://threejs.org/docs/#api/en/geometries/PlaneGeometry), and even [Blender](https://docs.blender.org/manual/en/latest/modeling/meshes/primitives.html#plane) all have it, and call it a plane. I would personally be very surprised to see it being called something else, as it is quite standard to be looking for "a ground plane" (typically bounded), and not... a flat surface? A 3D rectangle pointing up? I consider calling the shape a plane to be pretty standard in 3D game dev and modelling.
- While planes may technically be unbounded, I don't think there is anything mathematically wrong with applying bounds to them (e.g. restricting X/Y to a certain range, for example). I think of the `size` method for the mesh as doing this, applying bounds to an otherwise unbounded primitive (and the default size is also bounded for rendering and practicality reasons).

Essentially, I personally don't think it is *wrong* to treat plane meshes as bounded, and I would consider it the standard in the 3D game development and modelling space. I'm also not a fan of the name `Rect3d`, because it is inconsistent, somewhat confusing, and not even really a primitive by our own definitions.

Again, I do think it should be clearer how plane meshes work, at least through better documentation and/or nicer helpers and constructors. But calling it something other than a plane would deviate from my expectations considering prior art and what I consider to be a plane in game development. I'd personally just keep it as a `Plane3d`, but improve the documentation, use it in examples (we already do), and maybe add some nicer helpers.

If we do insist on a new primitive, I'd at least like a different name than `Rect3d`. `Quad` would be one option (it was the old `Rectangle`), but giving it a normal and making it face up by default would also deviate from what quads typically are in engines, so I don't think it's a great option either.

**Comment by andristarr** [comment]
Is there a concensus what we aim for the name?

**Comment by alice-i-cecile** [comment]
`InfinitePlane` for the 3D version seems like a clear way to distinguish it while allowing us to be consistent with other engines.

**Comment by Elabajaba** [comment]
> If not I would agree that Plane3d is a fitting name enough. Additonally to that I would always expect Plane3d to be a finite plane. Maybe we should rather come up with a more descriptive name for the unbounded infinite version.

Agreed. If you look at Unreal, Unity, Godot, Blender, 3ds Max, or Maya (and probably everyone else), a plane is finite/bounded and optionally subdivided.

**Comment by andristarr** [comment]
Now we have an Plane3d and an InfinitePlane3d math primitive. :)
