### ISSUE TITLE
`Oklab` and `Laba` color space bounds are incorrect

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy#12543]
> This is consistent with the docs for the `a` and `b` fields, but I would argue that the docs are wrong here. In Lab, the `a` and `b` are unbounded and their practical ranges depend on the reference white. Similarly, the lightness is also only lower-bounded by 0, but technically any lightness can be expressed in Lab. Where 100 is defined as reference white, you *can* have brighter colors than your reference, so an upper bound does not make sense.
> 
> Some software clamp the a and b values to the `-128..127` range as they would work in signed 8-bit integers, but this is technically clipping the Lab color space (note that [`palette`](https://docs.rs/palette/latest/palette/struct.Lab.html) uses this anyway as their bounds for a and b).
> 
> I don't know what sources the documentation used to determine the original ranges of the fields, and it's possible that they actually referred to a variant of Lab; but it stands to reason that the definition for this color type should follow the most generally used variant of the color space (that is, in its full name, `L*a*b* CIE 1976`), in which case the only meaningful bound to check is `lightness > 0`.
> 

_Originally posted by @SolarLiner in https://github.com/bevyengine/bevy/pull/12525#discussion_r1527573500_
            
            
 To fix this:
 
 1. Update the docs to soften the language on the bounds to something like "typically within the range of...", and clarify that these values are not clamped.
 2. Remove the incorrect clamping added in #12525.

**Comment by Gingeh** [comment]
there had already been some discussion about this on the discord: 
https://discord.com/channels/691052431525675048/691052431974465548/1212607622893805578

https://discord.com/channels/691052431525675048/691052431974465548/1212616712982364160

**Comment by Gingeh** [comment]
this issue should also include `Lcha` and `Oklcha`

**Comment by NthTensor** [comment]
Just throwing it out there, even sRGB colors can be unbounded (in intensity) if they are scene-referred. My understanding is that we should only ever fully clamp when creating a new display-referred color, and then only to the gamut of the display (or the best available approximation).

I have a longer explanation of this in the works. Got nerd-sniped on photometry and colorimetry recently.

**Comment by SolarLiner** [comment]
Similarly, here's a list of resources wrt. digital color:

- https://www.youtube.com/watch?v=fv-wlo8yVhk
- https://solarliner.dev/post/a-colorful-journey/ (disclaimer: it's my own writeup after falling down the digital color rabbit hole a few years ago)
- https://www.youtube.com/watch?v=53m-17Y_zJg (in the context of Blender, but mostly general technical knowledge)

**Comment by NthTensor** [comment]
Ok, here's what it looks like to me:
+ In order to support wide-gamut spaces (webgpu currently just supports P3 but it's possible it may eventually support more), our `LinearRgb` color needs to be non-normalized. It can't ever be clamped.
+ XYZ is inherently display independent. We can clamp to the positive quadrant, but is otherwise we can't bound it, so why bother.
+ Lab and Lch are inherently display-independent. We can clamp the chroma components to the locus of visible colors but we shouldn't clamp lightness. But it's not clear what method we should use to turn imaginary colors into real ones.
+ OkLab and OkLch are probably the same story, but I haven't checked.
+ sRGB and it's various alternate encodings HWB, HSV, HSL are all inherently display-referred and should be clamped, but we don't actually need to clamp them ourselves because wgsl will do it for us when we pass them into `rgba8unorm-srgb`.

Conclusion: We should probably remove the `ClampColor` trait.
