### ISSUE TITLE
Retrieving data in buffers from GPU to CPU

### ISSUE THREAD

**Issue by 443eb9** [bevyengine/bevy#12648]
## What problem does this solve or what need does it fill?

When compute shaders finished calculating, I can't get the data back to CPU to do more things. In my case, I want to implement a parallel A* pathfinding algorithm, but what is embarrassing is that I can't get the data from GPU.

It's also impossible to generate meshes using GPU then.

## What solution would you like?

Add some method to copy the data back to arrays on CPU, like `ComputeBuffer::GetData()` in Unity.

## What alternative(s) have you considered?

None

## Additional context

None

**Comment by bugsweeper** [comment]
There is [crate](https://crates.io/crates/bevy_app_compute) for it, which compatible with bevy 0.10, his [github version](https://github.com/Kjolnyr/bevy_app_compute) is compatible with bevy 0.12, it has [PR for bevy 0.13 compability](https://github.com/Kjolnyr/bevy_app_compute/pull/14). You can use it's branch for last version of bevy. I'm not sure about correctness of this crate, even [author admits some problems](https://github.com/Kjolnyr/bevy_app_compute/blob/5cc5400e0a309cf010a399d2cde65fc8fdd4b5a6/src/pipeline_cache.rs#L1). This crate works with buffers in both directions in PreUpdate/Update stages, that's why this buffers should not be used with other shaders (as input or output). As bevy expects copy data from main world to render world done on Extract stage, there is no backward copy stage, I think it should be at some cleanup point, and should be exclusive relative to main and render world like Extract stage is.

**Comment by bugsweeper** [comment]
Looks like there is solved [issue](https://github.com/bevyengine/bevy/pull/12877) with same goal
