### ISSUE TITLE
Document Aabb vs Aabb2d/3d

### ISSUE THREAD

**Issue by ChristopherBiscardi** [bevyengine/bevy#12675]
[`Aabb`](https://docs.rs/bevy/0.13.1/bevy/render/primitives/struct.Aabb.html) is a render primitive used most often for frustum culling.

[`Aabb2d`](https://docs.rs/bevy/0.13.1/bevy/math/bounding/struct.Aabb2d.html) (and [3d](https://docs.rs/bevy/0.13.1/bevy/math/bounding/struct.Aabb3d.html)) are math primitives intended for use in collision detection, ray/shape casts, and other bounding volume use cases.

They have similar names, which can lead users toward thinking they are similar/interchangeable or generalizations of each other, but the usage is different and this currently isn't called out in the docs. For example `Aabb` implements `Component` while `Aabb2d` does not, which compounds when users' Sprites get `Aabb` "for free" but `Aabb2d` must be manually constructed [as seen in the breakout example](https://github.com/bevyengine/bevy/blob/944fc71eb1a815b7a1de07998d96567454abe510/examples/games/breakout.rs#L370-L373).

The docs should ideally answer the question: "Which Aabb should I use?".

The answer to me seems like "Use Aabb2d/3d moving forward, since `Aabb` is optimized for the frustum culling use case", but I haven't been able to find a definitive answer.

**Comment by alice-i-cecile** [comment]
The actual answer is that this issue should be replaced with  "deprecate then remove `Aabb`": the math crew wants to swap us over completely, following the general design in the Primitive Shapes RFC. Doing so should be simple enough, but will require benchmarking to ensure there aren't performance regressions.

**Comment by Jondolf** [comment]
Alice beat me to it :)

I believe the general plan here is to hopefully deprecate `Aabb` in favor of `Aabb2d/3d`, or to make it a wrapper over `Aabb2d/3d` specifically for sprite/mesh purposes, probably with a more rendering specific name to avoid confusion.

The main reason this hasn't already been done is that `Aabb3d` currently uses `Vec3` instead of the SIMD-aligned `Vec3A`, unlike `Aabb`, and the representation is also different. We need to change it to `Vec3A` and make sure there are no performance regressions compared to `Aabb` to satisfy rendering people.

**Comment by ChristopherBiscardi** [comment]
Thanks for the details! I'm cool with closing this issue in that case. Finding this issue would have been enough for me to figure out what to expect/how to move forward.
