### ISSUE TITLE
Ordered List of Most Important Principals for Bevy Design

### ISSUE THREAD

**Issue by zicklag** [bevyengine/bevy#127]
I think it would be very helpful if Bevy had a list of principals for its current and future design **in order of precedence**. For example in one [comment](https://github.com/bevyengine/bevy/issues/32#issuecomment-671667952) @cart said:

> Usability and productivity will take priority over almost everything.

This is actually a really useful statement to me as a consumer of this project to help me understand what will be sacrificed for what when it comes to decisions. It would be nice to have kind of the list of guiding principals similar to the ["Why Build Bevy?"](https://bevyengine.org/news/introducing-bevy/#why-build-bevy), but specifically as a list ordered by importance.

That way I can understand, for instance, that if there is a decision that necessitates a trade-off between usability and performance, what will be the direction taken. According to the above quote, probably usability.

**Comment by GabLotus** [comment]
I think this is a very difficult question to answer and overall it will be a constantly evolving heuristic to determine whether or not a trade-off is worth it.

**Comment by zicklag** [comment]
It is perfectly fine for it to change over time, and I know that it will never be a perfect, clear-cut, decision maker or anything like that as each decision will have to be weighed individually, but I think it would be very useful as a general *guideline*. Not a set-in-stone are hard-fast rule list or anything, but a guide for what is, in general, how important to the vision of Bevy.

**Comment by cart** [comment]
I agree that its important to communicate the current goals of the project. Right now the decision making process is "have a discussion, come to a conclusion, and hope @cart can be convinced of that conclusion". In order to protect people from throwing away work (or brain power), I should communicate my general process.

That being said, there are no hard and fast rules here and each case must be considered individually. 

I can't say this is pri-1 over the next few days, but I will start giving this some thought.

**Comment by zicklag** [comment]
:+1: You have already done a great job of communicating why you are building Bevy and that means a *lot* to me and my team.

**Comment by tristanpemble** [comment]
@cart you clearly have a strong vision and set of guiding principles. for now, decision making is centralized to you. that's excellent and essential to the early stages of any project. as a project/organization scales, it will reach a point that it is unavoidable to distribute decision making. once you're there, it is notoriously difficult to align people in one direction. a clearly communicated vision for the future, with well defined values that are used to makes decisions on how achieve it, is a great way to "herd the cats" so to speak. timing this is difficult - too early and it can limit potential, too late and you've already lost momentum.

I think one reason this project has 'gone viral', is because that vision was very clear. I think the intro blog post is a great north star for decision making right now. it clearly resonated with people. I'd pay close attention to when you start to feel like you are straying from that vision and evaluate at that moment.

just my two cents :)

**Comment by cart** [comment]
Thats very welcome wisdom. Thank you!

**Comment by zicklag** [comment]
Somewhat relevant recent discussion from the Amethyst community: [Step 2: After the Vision Comes Leadership](https://community.amethyst.rs/t/step-2-after-the-vision-comes-leadership/1611?u=zicklag). Don't have to read if you don't want to. :)

**Comment by cart** [comment]
I've already read it. I'm a long time lurker of the Amethyst forums. I've learned so much from you all ♥️

**Comment by alice-i-cecile** [comment]
@cart are you okay if I close this out? I think this question will bubble up again naturally over time if it's needed.

**Comment by cart** [comment]
Yup!
