### ISSUE TITLE
Add QueryState::contains to mirror Query::contains

### ISSUE THREAD

**Issue by ItsDoot** [bevyengine/bevy#12750]
## What problem does this solve or what need does it fill?

There exists [`Query::contains`](https://docs.rs/bevy/0.13.1/bevy/ecs/system/struct.Query.html#method.contains), but not `QueryState::contains`.

## What solution would you like?

Add `QueryState::contains`.

## Additional context

`Query::contains` was originally added in [#3090](https://github.com/bevyengine/bevy/pull/3090) in 2021; QueryState wasn't generally accessible by users until [#6083](https://github.com/bevyengine/bevy/pull/6083) in 2022, so just seems like an oversight.

**Comment by FlippinBerger** [comment]
Wouldn't the implementation for `QueryState::contains` be essentially the same thing as `Query::contains` since the current Query impl accesses its QueryState as_nop and calls the QueryState method `get_unchecked_manual`? 

I'm not 100% on what the use case of adding `QueryState::contains` would be, but I'd imagine the implementation of `Query::contains` would just call the newly added impl that this issue is requesting. Not necessarily a problem, I'm just trying to understand what situations moving this logic down to QueryState would solve.

**Comment by ItsDoot** [comment]
> Wouldn't the implementation for `QueryState::contains` be essentially the same thing as `Query::contains` since the current Query impl accesses its QueryState as_nop and calls the QueryState method `get_unchecked_manual`?

Correct; this would simply be to give QueryState all the exact same tools as Query.
