### ISSUE TITLE
UI: image with Absolute position don't render correctly

### ISSUE THREAD

**Issue by mockersf** [bevyengine/bevy#13155]
## Bevy version

main since https://github.com/bevyengine/bevy/pull/10690

## What you did

Run example `game_manu` or `overflow_debug`

## What went wrong

Images that have `position_type: PositionType::Absolute` in their style are not displayed correctly

<img width="1280" alt="Screenshot 2024-05-01 at 02 23 48" src="https://github.com/bevyengine/bevy/assets/8672791/4e0b0e18-5243-4cf8-ae32-706d274645c1">

**Comment by mockersf** [comment]
@nicoburns any idea?

**Comment by nicoburns** [comment]
Hmm... no that's weird. It looks like it's about the right size in the x axis but it's getting stretched by about a factor of 2 in the y axis :/

**Comment by bugsweeper** [comment]
That because [width is set](https://github.com/bevyengine/bevy/blob/22305acf660486554fe6276e580e65a910b9e2df/examples/games/game_menu.rs#L396), but height isn't. If you remove width from style, you'll see ![image](https://github.com/bevyengine/bevy/assets/17225606/d6aa2644-3ff7-4ffc-b5e5-c7e5c6c09fcc) big icons with correct proportions.

**Comment by bugsweeper** [comment]
@mockersf I set height same as width and got 
![image](https://github.com/bevyengine/bevy/assets/17225606/44da7d1d-dc18-4872-9474-658d04a887ea)
correct result. Is this change good enough solution, or someone should dig deeper and figure out why taffy changed behaviour?

**Comment by bugsweeper** [comment]
For `overflow_debug` same thing: height is set, but width isn't. If add `width: Val::Px(400.0),`, then result 
![image](https://github.com/bevyengine/bevy/assets/17225606/a7258fa5-dca8-4121-a7ba-9fcbbdcd2093)
looks correct

**Comment by bugsweeper** [comment]
But if this solution get approve, then I think we should add some notes to Migration guide, because such things could be in bevy users code

**Comment by bugsweeper** [comment]
Or better add some check/warning in `bevy_ui::layout::convert::from_style(...) -> taffy::style::Style`

**Comment by mockersf** [comment]
>  Is this change good enough solution, or someone should dig deeper and figure out why taffy changed behaviour?

No, images should keep their ratio when you set only one of their dimension

**Comment by bugsweeper** [comment]
@mockersf The problem hides in taffy, because [at some point size fills None by measured_size](https://github.com/DioxusLabs/taffy/blob/066949d8b445eb19dbe76a4c5733038be4c30579/src/compute/leaf.rs#L137) which is done [componentwise](https://github.com/DioxusLabs/taffy/blob/066949d8b445eb19dbe76a4c5733038be4c30579/src/geometry.rs#L594). So there Size(Some(45), None) becomes Size(45, 100) which have no correct ratio.

**Comment by nicoburns** [comment]
I think the issue here is with the image measure function. It ought to read the image node's `Style` and use the `size`, `min_size` and `max_size` as part of it's computation. For most (all?) other "leaf" nodes this is automatically applied by Taffy, but that doesn't work for images because of their inherent aspect ratio.

**Comment by bugsweeper** [comment]
I agree with your desire for universal approach, but IMO min_size and max_size is for clamping but not for ratio description, if there is width or height set only, image should be abble grow or reduce unlimitedly but proportionally. I read the contribution.md page of taffy, it says that behaviour must be similar as in chrome css render. That's why IMO we should make html example first (test?) for taffy and reproduce this issue. If chrome behaves as we expect, then this is the basis for creating a well-formed issue in taffy project.

**Comment by bugsweeper** [comment]
I didn't notice that bevy doesn't inform taffy about node types, that's why taffy can't make correct decision about size behaviour. I think Style::aspect_ratio is correct approach, I will make PR based on it.

**Comment by bugsweeper** [comment]
@mockersf May I ask you for a review?

**Comment by nicoburns** [comment]
@alice-i-cecile Just wanted to call attention to this issue. It's a really not great regression which I believe it caused by the interaction between Taffy and Bevy's measure function. I don't think the fix should be *too* hard (either need to expose taffy's `Style` to the measure function or inherent aspect ratios to Taffy - the former is probably an easier quick fix), but it's a bit of an awkward one because I think it will require breaking changes in Taffy and then another Taffy upgrade in Bevy.

(but luckily Taffy doesn't have any other unreleased changes sitting around, so the upgrade should be quite straightforward).

What kind of release date is 0.14 targeting?

**Comment by alice-i-cecile** [comment]
We're looking at 1-2 weeks for the release candidate. I agree that this is important to resolve.
