### ISSUE TITLE
TrackedRenderPass::wgpu_pass may compromize invariants

### ISSUE THREAD

**Issue by fintelia** [bevyengine/bevy#13225]
Raising this as a issue as requested in https://github.com/bevyengine/bevy/pull/3595#issuecomment-2093464939...

The `TrackedRenderPass` type internally tracks which pipeline and bind group are active on a render pass. However, I think the `wgpu_pass` method may allow compromising its tracking:

```rust
tracked_render_pass.set_render_pipeline(&x); // Set render pipeline to "x"
tracked_render_pass.wgpu_pass().set_pipeline(&y); // Render pipeline is now "y"
tracked_render_pass.set_render_pipeline(&x); // No-op since tracked_render_pass thinks "x" is still active
```

**Comment by PPakalns** [comment]
Had problem with this when trying to migrate plain wgpu project rendering gradually to bevy rendering approach.

When rendering something inside egui window using [egui::PaintCallback](https://docs.rs/egui/latest/egui/struct.PaintCallback.html) , some views are rendered using native wgpu rendering libraries that use `RenderPass` instead of `TrackedRenderPass`. Due to this `TrackedRenderPass` doesn't work correctly after render implementation tries to restore bindings to previous ones after custom Paint callback.

If instead RenderPass is passed around:
1) bevy does not reexport this type. 
https://github.com/bevyengine/bevy/issues/3823 . 
2) Additionally such approach doesn't play nicely with [render phases](https://docs.rs/bevy_render/latest/bevy_render/render_phase/index.html).
