### ISSUE TITLE
Import Lights from GLTF

### ISSUE THREAD

**Issue by inodentry** [bevyengine/bevy#1331]
Currently, the GLTF loader loads meshes, textures, materials, scenes ... but it does not load lights.

Why that limitation? Can we load lights from GLTF?

**Comment by FrankenApps** [comment]
Loading lights from a GLTF requires the `KHR_lights` extension.
See this [Issue](https://github.com/KhronosGroup/glTF/issues/1068) for further information.
That means it is not in the standard spec for GLTF 2.0.

The `gltf` crate does however support at least the `KHR_lights_punctual` [extension](https://github.com/gltf-rs/gltf#gltf-extensions), so I guess support for punctual lights could be added pretty effortlessly.
However I do not know, why it has not been done yet.

Apart form that, it seems to me, that because of [this answer](https://blender.stackexchange.com/questions/200925/how-do-i-export-my-model-with-some-light-in-gltf), that only punctual, directional and spot lights can be included and no ambient lights. Since bevy does not support directional or spot lights (correct me if I am wrong) the only supported light type would be punctual lights.

**Comment by james7132** [comment]
This seems to at least be partially resolved as of #4715. Are we still missing anything for this issue?

**Comment by inodentry** [comment]
Bevy has supported Directional, Point, and Spot lights for some time now, and looking through the `bevy_gltf` code right now I see that they are all being loaded. It seems like it should all be resolved.

Closing this issue.
