### ISSUE TITLE
CPU Frustum Culling

### ISSUE THREAD

**Issue by bonsairobo** [bevyengine/bevy#1333]
**What problem does this solve or what need does it fill?**

Frustum culling is a pretty simple optimization where you put bounding volumes on your meshes and if a volume doesn't intersect the view frustum, you don't issue a draw call for that mesh. This saves a lot of vertex shader calls that would do culling on the GPU.

**What alternative(s) have you considered?**

This is a pretty standard feature for a renderer. I'm not aware of any better alternatives.

**Comment by aevyrie** [comment]
This is something I'm interested in working on, as I've been doing similar things for ray cast picking. To be upfront - if I did work on this, I would need some guidance when it comes to integrating with the renderer.

**Comment by aevyrie** [comment]
https://user-images.githubusercontent.com/2632925/108823172-ed21bf00-7574-11eb-8229-c54c38207692.mp4

I have a functioning CPU frustum culling plugin here: https://github.com/aevyrie/bevy_frustum_culling

This relies on the bounding plugin here: https://github.com/aevyrie/bevy_mod_bounding

This does not use a scene graph or any sort of BVH, instead, it simply runs culling in parallel with a `par_iter()`. Lots of room, for improvement, but functional. I will need to wait on #1492 to see how marker components for visibility shakes out. A PR for this issue would be significant - it would require merging the bounding volume plugin first, which could require significant change due to broader engine needs.

**Comment by alice-i-cecile** [comment]
Implemented by #2861 🎉
