### ISSUE TITLE
Increase default font size

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy#13587]
> Also, maybe 20px should just be the default font size. The default seems too tiny for any real use case anyway. Again, out of scope though.

_Originally posted by @IceSentry in https://github.com/bevyengine/bevy/issues/13583#issuecomment-2140906070_

**Comment by mockersf** [comment]
This is about the "default" font size we decided to use for example on screen instruction, which was 20

The default font size is 12.0 https://github.com/bevyengine/bevy/blob/ed042e5f9a715c16b5b5ccbaa765deb02c00a4b6/crates/bevy_text/src/text.rs#L205

Could we change the default implementation to be 24 and remove the need to specify a font size in examples?

**Comment by alice-i-cecile** [comment]
Yeah, my opinion is that the universal default should be larger, since you care most about the defaults when doing quick debug things like that.

**Comment by IceSentry** [comment]
> Could we change the default implementation to be 24 and remove the need to specify a font size in examples?

Yeah, that's essentially what I was suggesting in that comment. The default font size of 12px seems way too small for most cases where you want to just use the default value. I don't really know what a better value should be. I suggested 20px there because that's the value the PR was using for examples, but anything 16px or more would be good enough IMO.

**Comment by mnmaita** [comment]
I'm working on this now. I'll use 24px as default value and we will get some feedback in case someone has a better idea.
