### ISSUE TITLE
when will this support the mmd?

### ISSUE THREAD

**Issue by Tom-Jim** [bevyengine/bevy#13595]
i want to use it to make a game which need to port mmd format like pmx and vmd.

**Comment by valaphee** [comment]
Probably never at least in-tree, because the format isn't freely available therefore requires reverse engineering efforts and not that common. But it should be fairly straight forward to add support for formats like this in 3rd party crates.

As there is already a parser for pmx you just have to integrate it into Bevy.

**Comment by alice-i-cecile** [comment]
MMD: MikuMikuDance 
PMX: Polygon Model eXtended
VMD: Vocaloid Motion Data

The answer above is correct: we won't have first-party support for proprietary formats, and these formats are also not widely enough used in games to justify first-party support anyways. That said, writing your own asset loader is deliberately supported, and if you end up doing so it can be nice to publish a reusable crate for others to use and help maintain.
