### ISSUE TITLE
Shader is not loaded error is unclear

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy#13644]
The actual error produced here feels confusing to me, which is unfortunate.

```
thread '<unnamed>' panicked at examples/shader/compute_shader_game_of_life.rs:233:25:
Initializing assets/shaders/game_of_life.wgsl:
Pipeline could not be compiled because the following shader is not loaded yet: AssetId<bevy_render::render_resource::shader::Shader>{ index: 0, generation: 0}
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Encountered a panic in system `bevy_render::renderer::render_system`!
```

Specifically, the `not loaded *yet*` part. I wonder if that could be improved (not in this PR), or if there are scenarios where that language actually makes sense?

_Originally posted by @rparrett in https://github.com/bevyengine/bevy/issues/13624#issuecomment-2143885176_

**Comment by imrn99** [comment]
Hello all,

I took some time to look into this issue for a first contribution, and here is what I've found so far.

The printed-out error corresponds to the following enum variant:

https://github.com/bevyengine/bevy/blob/3bfc42766621d12749c09eca3bfd9911dc0dc3f5/crates/bevy_render/src/render_resource/pipeline_cache.rs#L1016C1-L1022C38

From the variant's name & its error message, it seems like it's trying to cover different issues (all related to shader loading, but still different); However, I could only find two usages of the variant in the source code, only one of which being a return:

https://github.com/bevyengine/bevy/blob/3bfc42766621d12749c09eca3bfd9911dc0dc3f5/crates/bevy_render/src/render_resource/pipeline_cache.rs#L276C1-L288C62

All occurences (cross-checked in my IDE): 
```bash
grep -rn --include="*.rs" "ShaderNotLoaded"
# ./crates/bevy_render/src/render_resource/pipeline_cache.rs:288 : .ok_or(PipelineCacheError::ShaderNotLoaded(id))?; (!)
# ./crates/bevy_render/src/render_resource/pipeline_cache.rs:929 : PipelineCacheError::ShaderNotLoaded(_)
# ./crates/bevy_render/src/render_resource/pipeline_cache.rs:1022: ShaderNotLoaded(AssetId<Shader>),
```
I'm willing to make a PR to fix this, but I'm not sure how it should be handled. Was there a greater motivation behind the current message (or a previous usage deleted at some point) that would justify having a `ShaderNotLoadedYet` variant? My guess is that it may relate to this `else` block during shader imports:

https://github.com/bevyengine/bevy/blob/3bfc42766621d12749c09eca3bfd9911dc0dc3f5/crates/bevy_render/src/render_resource/pipeline_cache.rs#L422C1-L455C1

The easy alternative would be to replace the current message with something along those line:

`Pipeline could not be compiled because the following shader could not be loaded: {0:?}`

**Comment by alice-i-cecile** [comment]
> The easy alternative would be to replace the current message with something along those line:

I would start with the easy alternative here.
