### ISSUE TITLE
Example script missing in compiler target

### ISSUE THREAD

**Issue by Wuketuke** [bevyengine/bevy#13685]
there is this script at examples/helpers/camera_controller.rs
but its not possible to compile with cargo run --example camera_controller,
and it is not mentioned in examples/README.md
i tried fixing it myself, but i wasnt quite able to do so

**Comment by mnmaita** [comment]
I think this is because the `camera_controller.rs` module is an "utility" meant to be used by the concrete examples (e.g. the `skybox` example uses `CameraControllerPlugin` from this module).

I'll close this issue but feel free to reopen it or leave a reply if this doesn't make sense to you. Thanks!
