### ISSUE TITLE
Get and set window position and keep scale unchanged

### ISSUE THREAD

**Issue by coolit** [bevyengine/bevy#137]
- Sometimes you need to get and save the position, so that next time the program can startup at your set position.
- If you drag the program into an extended big screen, the scale will change. But sometimes you might want to keep it unchanged.
Edit: Currently scale just applies to inner elements and title bar, not inner size which should be scaled too.

**Comment by rostyslav52** [comment]
What do you mean by "inner sizes"?
For example, in https://github.com/bevyengine/bevy/blob/master/examples/window/window_settings.rs
there is width and height. Is that it?

If so, then indeed I +1 your issue since keeping inner sizes updated with window resizing/scaling in fullscreen will help with mouse position detection.

**Comment by targrub** [comment]
> * Sometimes you need to get and save the position, so that next time the program can startup at your set position.
> * If you drag the program into an extended big screen, the scale will change. But sometimes you might want to keep it unchanged.
>   Edit: Currently scale just applies to inner elements and title bar, not inner size which should be scaled too.

Do the current methods on Window support all your requests?  If not, what else do you need?  If they do, maybe this issue can be closed?
