### ISSUE TITLE
Sysinfo plugin does not compile without `multi_threaded` feature

### ISSUE THREAD

**Issue by Friz64** [bevyengine/bevy#13957]
## Bevy version

Any version after #13693

## What you did

Compiled bevy without the `multi_threaded` feature, but with the `sysinfo_plugin` feature

## What went wrong

```
error[E0308]: mismatched types
    --> crates/bevy_diagnostic/src/system_information_diagnostics_plugin.rs:147:30
     |
147  |             tasks.tasks.push(task);
     |                         ---- ^^^^ expected `Task<SysinfoRefreshData>`, found `FakeTask`
     |                         |
     |                         arguments to this method are incorrect
     |
     = note: expected struct `Task<SysinfoRefreshData>`
                found struct `FakeTask`
note: method defined here
    --> /home/friz64/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/vec/mod.rs:1993:12
     |
1993 |     pub fn push(&mut self, value: T) {
     |            ^^^^
```

**Comment by bugsweeper** [comment]
That because [single_threaded_task_pool::TaskPool::spawn](https://github.com/bevyengine/bevy/blob/68db79862227885bb5d4794c2636e1749e36e574/crates/bevy_tasks/src/single_threaded_task_pool.rs#L153) returns FakeTask which can't contain future result, because [it's just empty struct](https://github.com/bevyengine/bevy/blob/68db79862227885bb5d4794c2636e1749e36e574/crates/bevy_tasks/src/single_threaded_task_pool.rs#L205), but actualy for non wasm (for wasm it indeed can't do better, because uses [wasm spawn method which allows only futures which outputs only empty tuple](https://rustwasm.github.io/wasm-bindgen/api/wasm_bindgen_futures/fn.spawn_local.html)) it [spawns future, gets it's task](https://github.com/bevyengine/bevy/blob/68db79862227885bb5d4794c2636e1749e36e574/crates/bevy_tasks/src/single_threaded_task_pool.rs#L165), waits [while executor finishes](https://github.com/bevyengine/bevy/blob/68db79862227885bb5d4794c2636e1749e36e574/crates/bevy_tasks/src/single_threaded_task_pool.rs#L167), and return nothing (FakeTask), throwing away _task with result! I think should be two `spawn` implementations for wasm (returning empty FakeTask) and for non-wasm which would return ready result T.
