### ISSUE TITLE
Behavior difference in sync point between Startup and OnEnter default State

### ISSUE THREAD

**Issue by zbx1425** [bevyengine/bevy#14094]
## Bevy version

0.14.0-rc.4

## What you did

Referencing an entity spawned in a `Startup` system inside `OnEnter(AppState::(Default State))`

## What went wrong

It works in 0.13, while in 0.14.0-rc.4 this entity cannot be found.

## Additional information

`add_systems(Startup, (app_startup, apply_deferred).chain())` seems to make it work.
It seems like a difference in behavior between 0.13 and 0.14.0-rc.4. Maybe what I was doing wasn't the best practice, though?

**Comment by alice-i-cecile** [comment]
This is the same phenomenon as #13968. `OnEnter` schedules are now executed immediately upon state initialization in order to ensure that it is impossible to be in a state without having actually entered it. Check that issue for strategies to deal with this :)

While annoying, this is intended behavior and something that I think is worth the tradeoff here.

**Comment by zbx1425** [comment]
Oh thanks!
Didn't notice it on migration guide though, or did I miss that
