### ISSUE TITLE
Most of the examples panic when run on FreeBSD 12

### ISSUE THREAD

**Issue by graeme3317** [bevyengine/bevy#141]
On FreeBSD 12.1, I get this:

` cargo run --example breakout
    Finished dev [unoptimized + debuginfo] target(s) in 0.15s
     Running `target/debug/examples/breakout`
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', crates/bevy_wgpu/src/wgpu_renderer.rs:28:14
`

This happens with most of the examples (hello_world,empty,headless all ran ok).

`rustc --version

rustc 1.46.0-nightly (346aec9b0 2020-07-11)
`

**Comment by costashatz** [comment]
I am also getting similar errors in ArchLinux:

`thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', crates/bevy_wgpu/src/wgpu_renderer.rs:22:23`

```bash
rustc --version
rustc 1.45.2
```

Any ideas on what's wrong?

**Comment by Titae** [comment]
I think it is related to #109

**Comment by costashatz** [comment]
> I think it is related to #109

Indeed it seems related! Thanks!

But I do have a GPU. The one that comes with the CPU. Bevy is not able to use this?

**Comment by graeme3317** [comment]
I have a Nvidia GeForce GTX 960 and am running the Nvidia supplied drivers.

**Comment by dzuvic** [comment]
I encountered the same issue on Gentoo. It seems that gfx-rs/wgpu on Linux (and maybe on FreeBSD too) only supports Vulkan, which i did not install initially. After recompiling Mesa with Vulkan support the example did work. The following table lists the supported platforms:


   API   |    Windows 7/10    |  Linux & Android   |    macOS & iOS     |
  -----  | ------------------ | ------------------ | ------------------ |
  DX11   | :white_check_mark: |                    |                    |
  DX12   | :heavy_check_mark: |                    |                    |
  Vulkan | :heavy_check_mark: | :heavy_check_mark: |                    |
  Metal  |                    |                    | :heavy_check_mark: |
  OpenGL | :construction:     | :construction:     | :construction:     |

(shameless copy from their GitHub README)

Since your're using NVidia drivers and they should support Vulkan, too. So maybe you are are only missing an ICD loader library. I had to install the [Vulkan Loader](https://github.com/KhronosGroup/Vulkan-Loader) from Khronos. I don't know if it exists on FreeBSD.

**Comment by costashatz** [comment]
> It seems that gfx-rs/wgpu on Linux (and maybe on FreeBSD too) only supports Vulkan

This indeed solved the issue. I installed the Vulkan drivers and it works! Thanks!

**Comment by graeme3317** [comment]
It looks like the Nvidia drivers for FreeBSD do not support Vulkan - [this thread](https://forums.freebsd.org/threads/vulkan-nvidia-freebsd12.68970/) discusses the issue. :-(
(For example, 'vulkaninfo' fails with an initialization error).

Thanks for your help.

**Comment by cart** [comment]
Thats very unfortunate. Lets hope that eventually the situation changes, either via a driver fix or wgpu opengl support.

Lets leave this issue open until Bevy can do rendering on BSD

**Comment by graeme3317** [comment]
It will probably work on FreeBSD right now as long as a supported  Radeon card is installed. 

Sadly, I can't test that.

**Comment by james7132** [comment]
Gentle poke on this, things have shifted quite a lot since 2020. Is this still an issue?

**Comment by graeme3317** [comment]
I'm now running on a new machine with an NVIDIA GeForce RTX 3060 Ti on FreeBSD 13.2

The good news is that vulcaninfo now runs OK.

The bad news is that  building a bevy program fails on gilrs.core:
`
001f/gilrs-core-0.5.11/src/platform/linux/gamepad.rs:22:15
   |
22 | use nix::sys::epoll::{Epoll, EpollCreateFlags, EpollEvent, Ep...
   |               ^^^^^ could not find `epoll` in `sys`

`

From what I recall Epoll is a Linux thing while FreeBSD uses kqueue.

**Comment by mockersf** [comment]
someone managed to run Bevy on FreeBSD and update the dependencies needed https://github.com/bevyengine/bevy/blob/main/docs/linux_dependencies.md#freebsd
