### ISSUE TITLE
z_order_debug renders are cubes black

### ISSUE THREAD

**Issue by mrk-its** [bevyengine/bevy#1411]
**Bevy version**
current master

**Operating system & version**

Ubuntu 20.04

**What you did**
Ran z_order_debug example

**What you expected to happen**

cubes should have different color depending on distance

**What actually happened**

All cubes are black

It seems this behavior is introduced by https://github.com/bevyengine/bevy/commit/7d065eeb718bffd55bf8c2dfc5add2220c51d830#diff-ee5fac51976cada9d968631feef5cb2bbfdbdb4c2057c08e1a1a2e743fa7f4ae

cc: @jamadazi

**Comment by DJMcNab** [comment]
Reintroducing the square root does fix it. That is, converting:
https://github.com/bevyengine/bevy/blob/3475a64a2c04b237b4d3b8988722a48d29c17739/examples/3d/z_sort_debug.rs#L37 to
```rust
let value = 1.0 - (visible_entity.order.0.sqrt() - 10.0) / 7.0;
```
That being said, it doesn't seem like we should encourage relying on what `order` actually means

Since there is the possibility we'd want to change it again in the future (e.g. normalise it to a certain power of 2 to speed up comparisons, as a potential example)
