### ISSUE TITLE
Implement FromStr and TryFrom for ParsedPath

### ISSUE THREAD

**Issue by Multirious** [bevyengine/bevy#14438]
## What problem does this solve or what need does it fill?

`ParsedPath` is parsed from strings and so can implement `FromStr` and any of the `TryFrom` string variants.
This let users to use `.parse()` or library author to create functions using `TryInto<ParsedPath>` for ergonomic reasons.

## What solution would you like?

Implment any of:
- `FromStr`
- `TryFrom<&str>`
- `TryFrom<String>`
- more string variants...

## What alternative(s) have you considered?

Use `ParsedPath::parse()` or `ParsedPath::parse_static()` directly.

**Comment by alice-i-cecile** [comment]
I think `FromStr` is my preference, but I'd be curious to hear more about which one is idiomatic and why.

Definitely think this should exist!

**Comment by soqb** [comment]
iirc `FromStr` only really exists as a remnant from (no pun intended) before `TryFrom<&str>` existed.

i think the typical solution is to implement both but there's an argument for not implementing `FromStr` since it's the less "flexible" trait.

i think `TryFrom<&str>` is the only parameter type which makes much sense considering the current `ParsedPath` api.
