### ISSUE TITLE
Unsoundness in QueryState::transmute_filtered

### ISSUE THREAD

**Issue by re0312** [bevyengine/bevy#14528]
## Bevy version

It's unsound to transmute a query state if D::DENSE or F::DENSE changed

## What you did

```rust
use bevy::prelude::*;

#[derive(Component)]
struct Table;
#[derive(Component)]
#[component(storage = "SparseSet")]
struct Sparse;
#[allow(unsafe_code)]
fn main() {
    let mut world = World::new();
    world.spawn(Sparse);
    world.spawn((Table, Sparse));
    let query = QueryState::<(&Table, &Sparse)>::new(&mut world);
    let mut new_query = query.transmute_filtered::<(Entity, &Table), ()>(world.components());
    for e in new_query.iter(&mut world) {
        println!("{:?}", e.0);
    }
}

````

## What went wrong

process didn't exit successfully: `target\release\examples\hello_world.exe` (exit code: 0xc0000005, STATUS_ACCESS_VIOLATION)

**Comment by hymm** [comment]
Are you sure it's that it's because D::DENSE of F::DENSE changes? That would be surprising to me since the QueryState is completely remade. Maybe the safety requirements on `new_archetype` aren't quite correct and it's the call there that is causing the memory violation.

You're not really supposed to call `QueryState::iter` on a transmuted query, because that calls `update_archetypes` internally. I wonder if we need to make `QueryState::transmute_filtered` unsafe and make the user promise not to call `update_archetypes` or any methods that call it.

**Comment by SkiFire13** [comment]
> Are you sure it's that it's because D::DENSE of F::DENSE changes?

The initial `QueryState` is over `(&Table, &Sparse)`, which uses archetype iteration. Hence the `matched_storage_ids` field of `QueryState` holds `StorageId`s initialized with `archetype_id`s (note that `StorageId` is an `union`). In particular it should be archetype 2 (not tested), with 0 being the empty one and 1 containing only `Table`.

When it gets transmuted the `matched_storage_ids` is cloned as is, but since it now uses dense iteration the `archetype_id`s are read as if the active field was `table_id`. It should hence try to read table 2, which shouldn't exist (table 0 is the empty one while table 1 contains `Table`s and is shared between archetypes 1 and 2). This is an out of bound read which likely leads to dereferencing some uninitialized pointers and eventually lead to the `STATUS_ACCESS_VIOLATION`.

Just re-creating the `matched_storage_ids` with `StorageId`s initialized with `table_id` however would not fix the issue, since the query matches only part of the table, so it would need to either drop access to those entities (likely undesiderable) or extending it to them (which is unsound).

Ultimately the issue is that the dense query optimization assumes that given a dense query data and filter then the query will always iterate over full tables, but transmutes (and `QueryBuilder`) break that assumption.
