### ISSUE TITLE
`bevy` fails to build with just `bevy_dev_tools` feature

### ISSUE THREAD

**Issue by BD103** [bevyengine/bevy#14736]
## Bevy version

Main branch :)

## \[Optional\] Relevant system information

Caught on both the `ubuntu-latest` Github Actions runner and on MacOS.

## What you did

```shell
cargo c -p bevy --no-default-features -F bevy_dev_tools
```

## What went wrong

```bash
error[E0609]: no field `render_layers` on type `&mut GizmoConfig`
   --> crates/bevy_dev_tools/src/ui_debug_overlay/mod.rs:112:20
    |
112 |             config.render_layers = LAYOUT_DEBUG_LAYERS.clone();
    |                    ^^^^^^^^^^^^^ unknown field
    |
    = note: available fields are: `enabled`, `line_width`, `line_perspective`, `line_style`, `depth_bias`, `line_joints`

For more information about this error, try `rustc --explain E0609`.
error: could not compile `bevy_dev_tools` (lib) due to 1 previous error
```

## Additional information

Originally caught in [this run](https://github.com/TheBevyFlock/flag-frenzy/actions/runs/10335648662/job/28610474579) by [`flag-frenzy`](https://github.com/TheBevyFlock/flag-frenzy).

**Comment by BD103** [comment]
Looks like its because `GizmoConfig::render_layers` is feature-gated behind `bevy_render`, which is not enabled.

https://github.com/bevyengine/bevy/blob/46e8c6b662ea2fcaac2ce9e9a4cc8cae2267c3d2/crates/bevy_gizmos/src/config.rs#L163-L167

**Comment by maslabgamer** [comment]
Repro'd this on Windows.

Looks like there's some dependency fun going on here, since `bevy_render` is required for `bevy_dev_tools` but not for `bevy_gizmos`, which is where `GizmoConfig` comes from.

Enabling the feature in the `bevy_dev_tools`' `Cargo.toml` appears to fix this:
`bevy_gizmos = { path = "../bevy_gizmos", version = "0.15.0-dev" , features = ["bevy_render"]}`

The alternative would be making `bevy_render` optional in dev tools, which seems like it would generate a _bit_ more wake.
