### ISSUE TITLE
Incorrect Time resource for fixed systems run with World::run_schedule(FixedMain)

### ISSUE THREAD

**Issue by nick-e** [bevyengine/bevy#15011]
## Bevy version

0.14

## Relevant system information
cargo version:
```
$ cargo --version
cargo 1.80.1 (376290515 2024-07-16)
```
operating system:
```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 12 (bookworm)
Release:	12
Codename:	bookworm
```
## What you did

```rust
use bevy::{app::FixedMain, prelude::*};

pub const FIXED_TIME_HZ: f32 = 60.0;
pub const FIXED_TICK_TIME: f32 = 1.0 / FIXED_TIME_HZ;

fn main() {
    let mut app = App::new();
    app.add_plugins(MinimalPlugins);
    app.insert_resource(Time::<Fixed>::from_hz(FIXED_TIME_HZ as f64));
    app.add_systems(Update, non_fixed_system);
    app.add_systems(FixedUpdate, fixed_system);

    app.run();
}

fn fixed_system(time: Res<Time>) {
    assert_eq!(time.delta_seconds(), FIXED_TICK_TIME);
}

fn non_fixed_system(world: &mut World) {
    world.run_schedule(FixedMain);
}
```

## What went wrong

I expect that executing `delta_seconds()` within `fixed_system()` will always return `FIXED_TICK_TIME`. This is because `fixed_system()` uses the `FixedUpdate` scheduler. What happened is that calling `delta_seconds()` within `fixed_systems()` did not return `FIXED_TICK_TIME` after being executed using `World::run_schedule(FixedMain)` within `non_fixed_system()`.

## Additional information
The program will not panic if `world.run_schedule(FixedMain);` is commented out. I believe that when `fixed_system` is run within `World::run_schedule(FixedMain)` it re-uses the `Time` resource of the caller. In this scenario, the caller is using the non-fixed schedule and its `Time::delta_seconds()` is not a fixed time. I'm not sure if that is intended behavior. The documentation for `World::run_schedule()` doesn't make the clarification.

**Comment by alice-i-cecile** [comment]
The reason this occurs is because the time swapping logic isn't done in the schedule itself. We could probably move it there to avoid this.

**Comment by bushrat011899** [comment]
There is some documentation on `FixedMain` that explains, by default, it is run by the `RunFixedMainLoop` schedule. The reason for this two-stage scheduling is to ensure the `Time<()>` resource is replaced with an appropriately updated `Time<Fixed>` copy. So a fixed version of your example would instead be:

```rust
use bevy::{app::{FixedMain, RunFixedMainLoop}, prelude::*};

pub const FIXED_TIME_HZ: f32 = 60.0;
pub const FIXED_TICK_TIME: f32 = 1.0 / FIXED_TIME_HZ;

fn main() {
    let mut app = App::new();
    app.add_plugins(MinimalPlugins);
    app.insert_resource(Time::<Fixed>::from_hz(FIXED_TIME_HZ as f64));
    app.add_systems(Update, non_fixed_system);
    app.add_systems(FixedUpdate, fixed_system);

    app.run();
}

fn fixed_system(time: Res<Time>) {
    assert_eq!(time.delta_seconds(), FIXED_TICK_TIME);
}

fn non_fixed_system(world: &mut World) {
    world.run_schedule(RunFixedMainLoop);
}
```

However, I also want to note that a default `App` (even called with `App::new()` will include the `MainSchedulePlugin`, which already sets up all these schedules to run each update. If you look at the `MainScheduleOrder` type you'll see the default set of schedules that get run by `Update` each...update.

Since this is documented and already as simple as I think it can be, I believe we can close this issue, but only if you feel this actually addresses your issue!

**Comment by nick-e** [comment]
Makes sense, thanks!
