### ISSUE TITLE
Segfault on running UI example

### ISSUE THREAD

**Issue by khionu** [bevyengine/bevy#1510]
[Logs, system, bevy version, and rust version](https://gist.github.com/khionu/6b287b6d3c1f6eab528e31f298738165).

## What you expected to happen

I'd see the UI example

## What actually happened

Visual output is an empty window containing a segment of my framebuffer.

**Comment by alice-i-cecile** [comment]
You said on Discord this took a few minutes to segfault right? We should try testing this on a few different systems, in order to see if we can reproduce it.

**Comment by khionu** [comment]
I can test on my System76 which is PopOS 20.10. I might be able to get someone else to test on Arch.

**Comment by alice-i-cecile** [comment]
Working for me on Windows 10 in both debug and release, even after a few minutes. I suspect this is probably an issue with loading in text. 

> 'Fatal error when processing text: failed to add glyph to newly-created atlas GlyphId(249).', crates/bevy_ui/src/widget/text.rs:110:21

looks like the critical line. Can you run the `text` example successfully?

**Comment by khionu** [comment]
It's taking a while longer to crash, still hasn't actually, but nor is it successfully rendering anything.

**Comment by khionu** [comment]
Finally crashed, same error message and source location

**Comment by Davier** [comment]
This looks like a system ordering issue with `text_system`, I can look into it this evening.

**Comment by DJMcNab** [comment]
The segfault looks different to the text issue - can you test running any other panicking system to see if you also get a segmentation fault?

**Comment by Davier** [comment]
I failed to reproduce this issue on Fedora (using the same rustc and bevy).
The only way to produce it is when a glyph fails to be allocated there: <https://github.com/bevyengine/bevy/blob/bc4fe9b186db3f32eef38fc4241289df480fa949/crates/bevy_text/src/font_atlas.rs#L91>, but the UI example only ever allocates 9 glyphs at the start, so it shouldn't panic after minutes.
Since you mention that it fails to render anything, it might be continuously trying to add the glyph until the texture atlas is filled. khionu, could you check if that's what happens? In my case I just added `dbg!(texture_atlas.len())` in `crates/bevy_sprite/src/dynamic_texture_atlas_builder.rs` line 37, to see the number of allocated glyphs.

**Comment by khionu** [comment]
I might be able to get to this this weekend.

**Comment by TimJentzsch** [comment]
This issue is almost 3 years old now, I think both the example and the UI implementation changed significantly during this time.

Just to make sure, I let the current UI example run for over an hour and didn't encounter any segfaults.

I think it's safe to close now, but @khionu if you can still reproduce feel free to reopen the ticket! :)
