### ISSUE TITLE
Entities with multiple observers do not function correctly

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy#15122]
> While you can technically make the entity itself an observer you can't do that multiple times as the `ObserverState` component would get overridden leading to serious issues. If that was exposed in bundles users could easily accidentally break things by inserting different bundles that each have observers.

_Originally posted by @james-j-obrien in https://github.com/bevyengine/bevy/issues/14204#issuecomment-2212515944_

**Comment by alice-i-cecile** [comment]
This is a pretty serious footgun / caveat. I'd prefer to eliminate this, but failing that, clear docs about this limitation would be helpful.

**Comment by james-j-obrien** [comment]
For what it's worth I would consider it very confusing if multiple observers could be associated with one entity.

It is equivalent to having an ID that maps to multiple systems or queries (after those are entities).

The most straightforward approach to support multiple is to give the state generics so they are different component IDs. This would make observers difficult to handle in type-erased/dynamic environments i.e. would I be able to create multiple observers on an entity for an event with a dynamic id? Or even just two observers with the same signature? Probably not since the states would still conflict, we would still have a footgun, just a more arbitrary one. Scripting scenarios may face trouble with this.

The alternative would be to add complexity to the existing state so it can act as multiple, which I think would be overkill for a feature that is used in the minority of cases.

This limitation should be well documented, but even ignoring the above complications I think it's idiomatic to have a 1-to-1 id to observer mapping.
