### ISSUE TITLE
Introduce `QuerySingle<Q, F>` family of system parameters

### ISSUE THREAD

**Issue by MiniaczQ** [bevyengine/bevy#15264]
## What problem does this solve or what need does it fill?

Following #15276 we should expose new system params that benefit from no panics.
Specifically, we should support entities that act as resources.
We can provide system parameters that are equivalents of `Query::single` family of methods.

## What solution would you like?

Add the following system parameters:
- `QuerySingle<Q, F>` - valid with exactly one result
- `Option<QuerySingle<Q, F>>` - valid with zero or one result

**Comment by MiniaczQ** [comment]
I'll be happy to implement it if someone gives me some directions

**Comment by alice-i-cecile** [comment]
So I quite like this idea from an ergonomics standpoint, and would use it in my own personal projects.

I'm loathe to expose more panicking APIs though, see #14275. I'd be interested in seeing `Single` return an `Option`. I'd also be nervous to use this in learning materials other than that dedicated to this concept, since teaching users a single blessed tool is really helpful conceptually.

**Comment by MiniaczQ** [comment]
Until #14275 gets resolved I feel like we should stick to the existing convention.
The scope is already massive, one more feature won't make a dent in the breaking changes

**Comment by janhohenheim** [comment]
@alice-i-cecile imo we should not introduce more `Option`s, but only use `Result`s where possible in new API. Otherwise we will have to change it again once we an error handling overhaul happens.

**Comment by janhohenheim** [comment]
@MiniaczQ alright, sorry!

**Comment by alice-i-cecile** [comment]
I'm happy to consider this idea unblocked due to the ideas in #15625. Once that's fully implemented, this should be recommended as the default way to work with singleton queries and used consistently through our examples.
