### ISSUE TITLE
Unnessesary assets in examples

### ISSUE THREAD

**Issue by fhgaha** [bevyengine/bevy#16055]
[This](https://bevyengine.org/examples/ui-user-interface/ui/) ui example has such lines of code as `font: asset_server.load("fonts/FiraSans-Bold.ttf")` and `UiImage::new(asset_server.load("branding/bevy_logo_dark_big.png"))`. That means if I want to run this example from my project I need to go through those things and change them to `..default()` or download all of them. This makes it more complicated then it should be. I ask to use default font and default UiImage... by default.

**Comment by rparrett** [comment]
Removing the custom fonts and images might undermine the purpose of the example, which is to demonstrate various `bevy_ui` features including loading fonts and showing images.

We could potentially use a the default font, but the default font has a limited glyph set and is monospaced, so most users will likely want to use a custom font. It is limited in this way to keep file size down.

Using a default for the `UiImage` would make the example silently broken though, instead of emitting a helpful "asset missing" warning.

**Comment by fhgaha** [comment]
Well, that's a fair point although I don't completely agree with that. You want me to close this issue?
