### ISSUE TITLE
Sprite pixels per unit

### ISSUE THREAD

**Issue by DarkMara** [bevyengine/bevy#1617]
## What problem does this solve or what need does it fill?

It allows sprites to be drawn at a different size than pixels. It also makes it possible to use sprites of different resolutions and make them the same size in-game.

## What solution would you like?

There should be a f32 on `Sprite` and `TextureAtlas` that determines the pixels per unit the sprite(s) are drawn at. For `TextureAtlas,` it will determine the pixels per unit for all sprites in the atlas.

## What alternative(s) have you considered?

The alternative is to scale the sprite, which is annoying because it will scale everything else on the entity.

## Additional context

[Here's a question](https://gamedev.stackexchange.com/questions/83433/what-is-the-pixels-to-units-property-in-unity-sprites-used-for) that talks about the feature in Unity.

**Comment by mockersf** [comment]
From the discussion you linked, it seems this is used in Unity for physics, which is not an issue in Bevy

I also had this issue, I "fixed" it by having my sprite in a child entity where I could set the scale only for the sprite. Would this workaround work for you?

**Comment by DarkMara** [comment]
I am aware of that workaround, and it's what I'm currently doing as well. I believe this is not useful only for physics. It's also useful if you want to use sprites of different resolutions in the same project and have them be the same size in-game. It is also useful if you have a tilemap and you want the 1 unit to be the size of a tile. I guess in that case I can just try scaling the entire tilemap?

Unity has this feature, but it doesn't look like Godot does. To me it's a convenient feature to have, but maybe not absolutely necessary, since it could be handled by the user. But I still think it's a useful feature. 

I feel it should be built into the sprite shader like it is in Unity. Then you don't have to fiddle around with scaling things.

**Comment by ArjunNair** [comment]
Godot doesn't need the PPU system because it always works in pixel units in the 2D space (all co-ordinates are in screen space). Unity is a 3d engine that "does" 2d by converting between the two co-ordinates, which is why Unity thinks in terms of world units. To make it easier for people to work with the unit system, Unity introduces a PPU feature where every sprite used in the game can be visualized in terms of Unity units. This is usually required when working with a grid based game typically using a tilemap (which can be thought of in terms of units. eg, 4x4, 10x10 etc). Suppose you had a MxN tilemap where each tile is expected to be of 64x64 pixels. Your PPU therefore is 64 for the tile sprites (64 pixels = 1 unit). If the PPU is set to 32 instead, the sprites will be scaled up 2 to fit one unit space. If PPU is set to 128, the sprites are scaled down by 2 to fit one unit instead. 

In principle the Unity PPU system is kinda neat because it allows you to make your sprites fit a 'unit' system (as DarkMara mentioned), but in practice I've found it a nightmare to explain it to artists, designer and other coders who might be working on a project. "See this sprite is 64x64 but our game is working on 128x128 = 1 unit system. So please make sure the PPU for this sprite is set to 32 if you want it to appear the same size as the larger sprites". This is usually met with blank stares and mild panic attacks. I have to do what now? I'm just an artist! 

To be fair, this is usually not an issue if you're the solo developer but it can quickly turn into a major annoyance of managing content when a lot of pixel art is being used and there are multiple people working on the project who don't seem to "get" it or more commonly seem to forget to set the PPU (or worse, set it incorrectly!) and then get all surprised when the sprites show up all the wrong size in the game. 

But everyone seems to understand 'scale' or 'size' of a sprite. This is a 64x64 asset, so just scale it up twice to get 128x128 - that makes sense!

I feel that a true 2D support will be a better option for Bevy, much like Godot. In fact, I found this project based on Bevy seems to do exactly that: https://github.com/katharostech/bevy_retro

I apologize for the rambling. But that's my two cents FWIW.

**Comment by richchurcher** [comment]
@alice-i-cecile just cruising the issue stack looking for more old D-Trivial's to clear up! However, this one feels like it doesn't have consensus behind it. Is this perhaps a "close" rather than an "implement"?
