### ISSUE TITLE
Missing blanket impl for Debug on States

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy#1699]
## Bevy version

c78b76bba8def0d72b579b4a06673843f32e8532

## What you did

Tried to debug a state resource added with `.add_state`. The underlying type has Debug derived.

## What you expected to happen

I can use the `dbg!` macro normally.

## What actually happened

Debugging fails because the Debug trait for the State wrapped type is not found.

## Additional information

This should be an easy fix with a blanket impl that uses the wrapped type's debug function.

**Comment by guimcaballero** [comment]
Hi, could you provide a code example that generates the error? I'd like to work on this but I'm having trouble understanding where the issue is. As far as I know, `State` [already derives `Debug`](https://github.com/bevyengine/bevy/blob/main/crates/bevy_ecs/src/schedule/state.rs#L14). 

Something like the following does work in the linked Bevy version:

```rust
#[derive(Clone, Eq, PartialEq, Debug)]
enum AppState {
    Menu,
    InGame,
}

fn test(
    state: Res<State<AppState>>,
) {
    dbg!(&*state);
}
```

**Comment by alice-i-cecile** [comment]
Aha: the old &* trick. I was pair programming and didn't dwell on it.

This is a good enough solution; closing this issue.
