### ISSUE TITLE
Investigate !Sync/!Send Exclusive Systems

### ISSUE THREAD

**Issue by zicklag** [bevyengine/bevy#1719]
This is a follow up issue to this [discussion](https://github.com/bevyengine/bevy/discussions/1636#discussioncomment-478637), where I ran into an issue where I have `!Sync + !Send` state struct that I pass into an exclusive system closure:

## Bevy version

c3a72e9dc85b53a1448138270c72e806fc91ec85

## Operating system & version

Ubuntu 20.04, but all platforms are effected

## What you did

```rust
use bevy::prelude::*;

struct NotSend {
    not_send: *const u8,
}

fn main() {
    let system = make_system();
    App::build().add_system(system.exclusive_system()).run();
}

fn make_system() -> impl Fn(&mut World) {
    let not_send = NotSend {
        not_send: std::ptr::null(),
    }

    move |_| {
        let _ = not_send;
    }
}
```

## What you expected to happen

The program should compile because the `!Sync + !Send` struct should never be sent across threads in an exclusive system.

## What actually happened

Program fails to compile

## Additional information

Theoretically this should work, because exclusive systems should be gauranteed to run on the same thread and the state should not need to be `Sync` or `Send`, but this needs more investigation. In the interim I am required tu `unsafe`ly implement `Sync + Send` on my struct even though it is not actually `Sync + Send` which is concerning to have laying around my codebase.

cc @Ratysz

**Comment by james7132** [comment]
With the stageless RFC being merged, the schedule and systems being moved into `Schedules` as resources inside a `World`, and a general move away from supporting `!Send` and `!Sync`  data within World, this doesn't seem very likely to move forward, as this would require all systems to be `!Send`/`!Sync` which would have strong implications on how the system scheduler would run. 

For more context, please see this discussion on Discord: https://discord.com/channels/691052431525675048/692572690833473578/1047997793375096852, and #6552.

Tentatively closing this issue due to the aforementioned change in direction.
