### ISSUE TITLE
SparseSet components double Query length when used in Without<T> filter

### ISSUE THREAD

**Issue by Byteron** [bevyengine/bevy#1788]
## Bevy version

bevy main (94c41840)

## Operating system & version

Windows 10

## What you did

When using a component in a Without<T> filter in a query, the query contains double the amount of entities.

## What you expected to happen

Each entities components should only be once in the query

## What actually happened

query iter len is double the amount of entities with those components

## Additional information

Found this while investigating the bevy rendering systems to find bottlenecks and noticed that `draw_render_pipelines_system` iterates double the amount of entities that are supposed to be drawn.

**Comment by cart** [comment]
Haha I noticed right when I posted and promptly pressed delete. Silly mistake :)

**Comment by cart** [comment]
I have a fix. The issue is that we end up inserting duplicate archetype ids into query state.

**Comment by cart** [comment]
We already do the dupe check for table ids, so its natural to add it for archetypes. But I think we _shouldn't_ need it. `new_archetype` should only be called on _new_ archetypes. But apparently we do it more than once.

**Comment by cart** [comment]
Cool I think I have a root cause: `QueryState::new_archetype` is called whenever the _stage_ encounters a new archetype. This would be fine if we knew that no system has processed archetypes prior to that. But when we first create a QueryState for a system's Query (which takes a world reference), we process the archetypes currently in the given World. 


We could "fix" this by either:

1. creating a new constructor that doesn't initialize archetypes ahead of time and allows the schedule to do it for us (cheaper, but less error-resilient)
2. add the "duplicate archetype" check to `new_archetype` (one more fixedbitset lookup, but makes new_archetype fool-proof).

This _is_ actually a safety issue as returning duplicates in query iterators allows for aliased mutable access. Fixedbitset ops are cheap and new_archetype is only called once for each new archetype, so I think (2) is the right call.
