### ISSUE TITLE
promote usage of logs rather than printing to stdout

### ISSUE THREAD

**Issue by mockersf** [bevyengine/bevy#1895]
## What problem does this solve or what need does it fill?

Examples are currently using `println!` to show what happens

## What solution would you like?

Encourage more log usage, replace all `println!` calls with logs at appropriate levels

## What alternative(s) have you considered?

just keep at that way...

## Additional context

none

**Comment by Grindv1k** [comment]
Something I would like to see in addition to this:

Documentation somewhere to let users know the syntax for filtering only their own logs.

E.g. if `RUST_LOG=debug` is used, a lot of engine output is shown.

Personally I can never remember the appropriate syntax for `RUST_LOG=debug,<but_only_my_app_syntax_here>`, so it would be nice to have it somewhere central.

And/or: Show an example which filters out only the graphics/rendering logs (iff <= info) since that part of is very verbose.
