### ISSUE TITLE
impl Send for QueryIter, if possible

### ISSUE THREAD

**Issue by lukewestby** [bevyengine/bevy#2013]
## What problem does this solve or what need does it fill?

I'm working with bevy in the browser, and while wasm multithreading isn't yet built in for bevy_tasks it may be possible to parallelize computations within a single system using [wasm-bindgen-rayon](https://github.com/GoogleChromeLabs/wasm-bindgen-rayon) and [`par_bridge`](https://docs.rs/rayon/1.5.0/rayon/iter/trait.ParallelBridge.html#tymethod.par_bridge). Currently this will not work because `QueryIter` must be `Send` in order to pass it to `par_bridge`.

e.g.

```rust
fn my_system(my_query: Query<&MyComponent>) {
    let some_result = my_query
        .iter()
        .par_bridge()
        .map(|component| ...)
        .reduce_with(|x, y| ...);
    // do something with some_result
}
```

## What solution would you like?

I'm new enough to Rust that I don't really know how to track down whether `QueryIter` can be made to be `Send` or not. I spent the better part of a day on it and didn't really get anywhere. If it's as simple as adding `unsafe impl Send` for `QueryIter` or one of its constituent types that would be great. I wrote a wrapper type around `QueryIter` and did `unsafe impl Send` for it, and the code ran without doing anything weird so that seems to indicate that it _may_ be possible, but it's only one case.

## What alternative(s) have you considered?

If it's impossible or would put undesirable constraints on the rest of the project then nevermind, we'll just live without until wasm support in bevy_tasks matures.

## Additional context

N/A

**Comment by cart** [comment]
At first glance I _think_ this should be ok. We are forced to manually impl Send/Sync on World due to some `NonNull<T>` usage (which like raw pointers, might allow aliasing, which our manual Send/Sync impls assert will not occur). QueryIter uses the internal storages directly instead of World, so it doesn't inherit those impls. I think the biggest thing to validate here is that implementing this for QueryIter doesn't allow any funny business from within the context of the system. Lifetimes should still be respected, so I'm not too worried. But I'm also not certain enough to just approve this outright :smile:

**Comment by lukewestby** [comment]
@cart thanks for taking a look! is there anything i can do, things i can validate, etc. to help get to a final yes or no?

**Comment by cart** [comment]
The first thing I would do to check for heinous safety errors would be to add the Send/Sync impls to QueryIter, then try to move QueryIter to a detached thread (which doesn't return before the end of the system). If the thread can hold the QueryIter after the system returns, we're in big trouble (however the lifetimes on QueryIter should prevent that so I expect the compiler to yell at us here). After that, the biggest thing to check is that each field in QueryIter can safely be sent to another thread (the Fetch impls in particular are where I'd pay the most attention). Our current (and past) parallel iterators all create the fetch impls _inside_ the current thread, rather than sending them _to_ a thread.

**Comment by cart** [comment]
I'll pull in @bjorn3, who has been pretty good at catching safety errors in the past.

**Comment by bjorn3** [comment]
I wonder if it would be sound to make `Tables`, `Archetypes` and `World` `Sync` (or at least those that aren't `Sync` already). That would automatically make `QueryIter` `Send` if `Q::Fetch`, `Q::State`, `F::Fetch` and `F::State` are `Send`.

**Comment by cart** [comment]
I suspect that F::Fetch isn't Send (by default) because it uses raw pointers in some cases. If we add the Send constraint to Fetcht, I think we'll need to do a lot of manual `unsafe impl Send for FetchType {}`. This is probably fine, it just increases our unsafe footprint and increases the code size of each Fetch implementation. I think Tables and Archetypes can be Send. They don't use interior mutability.

**Comment by bjorn3** [comment]
You don't need a `Send` constraint. Without `QueryIter` is automatically `Send` if `F::Fetch` is. Doing a blanket `Send` impl on `QueryIter` without requiring `F::Fetch` to be `Send` is probably unsound.

**Comment by cart** [comment]
Ah yeah I see your point. Specific instances of QueryIter will be Send, provided that the specific instance of Fetch is Send (and other fields like Archetypes are Send).

A blanket Send impl for QueryIter is basically an assertion that all present and future Fetch impls are Send (which might be true now, but might not be true in the future / users could easily violate that with their own impls). 

So regrettably, we need to manually `unsafe impl Send` for all Fetch impls that use raw pointers. This is safe because Fetch is prevented from violating Rust's mutability rules due to how / where it is constructed.

**Comment by cart** [comment]
A Send constraint on Fetch _would_ force us to remember to add the impl for all Fetch impls. Whether or not that is desirable is debatable.
