### ISSUE TITLE
Size field on SpriteBundle / Sprite component has surprising behavior

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy#2092]
## How can Bevy's documentation be improved?

The [Size](https://docs.rs/bevy/0.5.0/bevy/sprite/struct.Sprite.html) field on `Sprite` sets the absolute size of the sprite in pixels.

Intuitively, users might expect that this would instead set the relative scale, and the size would be determined automatically from the imported asset.

This issue could be closed by either changing that behavior, explicitly documenting that field or ideally both.

**Comment by concave-sphere** [comment]
There's another oddity I've run into: if you set a custom mesh and don't set a texture, the default size is (0, 0) and so nothing shows up (or maybe the geometry is all collapsed to a point).  I have to set the size to (1, 1) everywhere so that my Mesh is displayed as desired.

I haven't filed this because I suspect I am abusing the `Sprite` type and would be better off using `MeshBundle`, but if the docs are being updated, there may be something worth explaining here.

**Comment by alice-i-cecile** [comment]
Closing, as this field was removed in 0.6.
