### ISSUE TITLE
[wasm] Attempting to get an EventWriter for an unregistered event type panics with an unhelpful message

### ISSUE THREAD

**Issue by lukewestby** [bevyengine/bevy#2139]
## Bevy version

0.5.0

## Operating system & version

wasm

## What you did

Create a system like so:
```
struct Event;

fn system(mut events: EventWriter<Event>) {}
```

Set up the app, but do not register the event
```
App::build()
    .with_system(system.system())
    .run();
```

## What you expected to happen

The application is misconfigured so I expect this to panic, and ideally the message for the panic would explain that a system attempted to fetch an `EventWriter` for an unregistered event type.

## What actually happened

The application panics with the following:
```
panicked at 'assertion failed: `(left == right)`
  left: `true`,
 right: `false`: cannot recursively acquire mutex',
```

and upon further examination of the stack trace it turns out to be the failure described by #1924

**Comment by alice-i-cecile** [comment]
FYI you don't need to register the event with add_event, merely create a resource for it. I agree that the error message should be much better though.

**Comment by NiklasEi** [comment]
> FYI you don't need to register the event with add_event, merely create a resource for it.
Adding the resource would remove this particular error, but the event would not be functioning without the managing system (added e.g. via `add_event`), would it?
Since events are used a lot, could we maybe make this a custom error pointing to `add_event`? On Linux I just get "thread 'main' panicked at 'Requested resource does not exist: bevy_app::event::Events<stream::Event>'" which could be nicer in my opinion if it were more event specific.

**Comment by alice-i-cecile** [comment]
Cleaning up the error messages here would be a nice step forward, and should be quite approachable for a new contributor.

**Comment by CGMossa** [comment]
I recommend we close this;
Similar issue is #5088, and it was decided there to close.
