### ISSUE TITLE
Condense and cache system order dependencies

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy#2220]
## What problem does this solve or what need does it fill?

Suppose we have three systems A -> B -> C. Each of those arrows represents an explicit ordering dependency, but there is also a dependency A -> C.

Each step, we will be wasting working checking A -> C when it's implied by the other dependencies.

## What solution would you like?

Create a minimal representation of the system ordering graph once at run time, then cache it.

Recompute the relevant sections of this if systems are later added or removed.

## What alternative(s) have you considered?

Encouraging users to remove these redundant system dependencies makes refactoring more dangerous and can hurt code clarity. As a result, I would be cautious about promoting a user-accessible tool to detect these.

## Additional context

Adding and removing systems dynamically is not yet supported, but I expect this to be quite rare (and likely to occur when e.g. loading mods) and so the overhead on that doesn't concern me relative to the small but persistent cost of bloated graphs.

**Comment by Ratysz** [comment]
> Each step, we will be wasting working checking A -> C

Where, exactly? That's not how the executor works.

During cached data recalculation, the only place that could benefit from knowing full dependency chains is the ambiguity checker, and it already does that by building up bitsets of all ascendants/descendants; which I am fairly certain is faster than just walking a more populated graph, because it cuts a lot of corners by relying on systems being topologically sorted. Toposort itself doesn't need the extended chains either.

During execution, whenever a system completes it decrements the counters of all systems that depend on it; when the executor is trying to start more systems, it only considers those with the counter already at zero. Systems themselves don't know their ascendants (only their amount, for resetting the counter) or indirect descendants, because that's completely redundant.

There is a legacy bit of recalculation that flips the system-ascendants mapping into system-descendants mapping, which should ideally be worked out, but even it, obviously, does not benefit from knowing more than the direct relatives.

**Comment by alice-i-cecile** [comment]
That's an awesome explanation (and a clever algorithm), thank you. I'm going to close this out then.
