### ISSUE TITLE
Add pixelated Bevy to assets

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy#2279]
@dtcristo, the author of [bevy_pixels](https://github.com/dtcristo/bevy_pixels) created the awesome little pixeled Bevy shown below.

To avoid confusion with the official project, they've offered to it to Bevy to use:
> Feel free to use it for whatever official purposes you want. I created it using https://www.pixilart.com/

- [@dtcristo on Discord](https://discord.com/channels/691052431525675048/743664267856838736/848379623943045173)

As we progress on #1856, it would be valuable to have test assets of this sort, and this is both small *and* cute.
I've attached the image and .pixil file below.

[bevy_pixil.zip](https://github.com/bevyengine/bevy/files/6565567/bevy_pixil.zip)
![bevy_pixels](https://user-images.githubusercontent.com/3579909/120089533-5f042a00-c0c9-11eb-97c3-6d0be2dcaf6f.png)

**Comment by JonahHenriksson** [comment]
Really nice! It could even be used in a loading screen before a pixel game start menu.

I noticed that the colors weren't in the order of the official logo. Here is an edit I made, just in case people prefer it.

![pixel_bevy](https://user-images.githubusercontent.com/33059163/120861701-3bccf500-c577-11eb-953b-e2ce1c3bff8b.png)

**Comment by Ian-Yy** [comment]
Hi, I would like to help on this. But I don't really understand what needs to be done. Is it writing unit tests on loading assets or use this as the default loading screen?

**Comment by alice-i-cecile** [comment]
@Ian-Yy this just needs to be added to added to the `assets` folder with an appropriate license listed, and then used in a `pixel_perfect` example in the 2D folder. That example should demonstrate how to set the filtering mode to an appropriate setting for pixel art, and move the pixelated logo around a bit to verify that everything looks okay.

**Comment by Ian-Yy** [comment]
Hi @alice-i-cecile. I have created the PR. I am not sure what I should do with the appropriate license. And for `pixel_perfect`, I am just using the filter mode `nearest`. Not sure if this is okay, but I have check that the image doesn't stretch and distorted when moving. Please let me know if this is right or there's a different filter mode or direction to go. And in the docs, I keep seeing [ImageSettings](https://docs.rs/bevy/latest/bevy/render/texture/struct.ImageSettings.html) but in the 9.0-dev, it's `ImagePlugin` and implemented using `add_plugin` instead of `insert_resource` which make me so confuse.

**Comment by alice-i-cecile** [comment]
I'll reply on the PR :)
