### ISSUE TITLE
HandleUntyped::typed should return a Result

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy#2534]
## What problem does this solve or what need does it fill?

Converting from an untyped to a typed handle is very dangerous, as it panics if the type does not match.

This makes it much less safe to use in dynamic situations.

## What solution would you like?

[`HandleUntyped::typed`](https://github.com/bevyengine/bevy/blob/3af3334cfeb551782cc5b33389d6a9898908e170/crates/bevy_asset/src/handle.rs#L278) should return a Result instead. 

## What alternative(s) have you considered?

If there are significant perf reasons why this currently works the way it does, we should have a "unsafe typed_unchecked" method that skips the type check completely and then call that within the new `typed` method.

## Additional context

I'm not sure what Error type this should return; once that's determined this should be very easy to PR in.

**Comment by kroltan** [comment]
I don't think there are any perf justifications since the current method _is_ checked, it just doesn't surface that into the method signature.

**Comment by kroltan** [comment]
Regarding the return value, if we look at the standard library, there is a case for `Result<Handle<T>, HandleUntyped>`. Since the method takes `self` by value, it would be similar to these examples:
 - [`std::error::Error::downcast`](https://doc.rust-lang.org/std/error/trait.Error.html#method.downcast)
 - [`std::boxed::Box::downcast`](https://doc.rust-lang.org/std/boxed/struct.Box.html#method.downcast)
Both of those take `self` by value. A counterexample would be [`std::any::Any::downcast_ref`](https://doc.rust-lang.org/std/any/trait.Any.html#method.downcast_ref)/[`_mut`](https://doc.rust-lang.org/std/any/trait.Any.html#method.downcast_mut), but those take the input by reference.

**Comment by alice-i-cecile** [comment]
Cool, that's a neat return type. Returning `Self` as the error is not any harder to handle in the simple cases, and enables some interesting patterns for more complex workflows.

Let's roll with that for the initial PR.

**Comment by alice-i-cecile** [comment]
No longer relevant after https://github.com/bevyengine/bevy/pull/4794 :)
