### ISSUE TITLE
Include READMEs from Bevy crates as crate-level documentation

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy#2566]
## How can Bevy's documentation be improved?

With the release of [Rust 1.54](https://blog.rust-lang.org/2021/07/29/Rust-1.54.0.html), we can now do this:

```rust
#![doc = include_str!("README.md")]
```

This is great, because we have useful content in our READMEs that should be in our module-level documentation, rather than buried several levels deep on Github.

Some crates already have existing module-level description; for the most part this should be consolidated into the readme. `bevy` itself is the only exception that comes to mind; it's probably worth including some advice on contributing / navigating Github that doesn't make sense on docs.rs.

**Comment by cart** [comment]
As a counter point: this optimizes for "github browsing" workflows, which actual bevy developers won't do much. It creates a level of indirection for people who are actually working in the code. Docs that would have been available directly in the mod file currently being worked on are now somewhere else in the tree.

I like this for "crate level" documentation because it allows us to reuse README content we'd need to write anyway  (when that is desirable), but I'm not convinced that this is a win for nested modules.

**Comment by alice-i-cecile** [comment]
> I like this for "crate level" documentation because it allows us to reuse README content we'd need to write anyway (when that is desirable), but I'm not convinced that this is a win for nested modules.

Yes, my intent was to only include this for top-level crates ala `bevy_ecs`. My bad on the title; I'll make it more clear.
