### ISSUE TITLE
Support for Uint textures missing?

### ISSUE THREAD

**Issue by vsaase** [bevyengine/bevy#2696]
https://github.com/bevyengine/bevy/blob/62e4e59a864a3d2ca01e0372cb2f0ffed0d2dbf6/crates/bevy_render/src/shader/shader_reflect.rs#L134

This is the only place I could find where the texture sample type is set. Is it true that I can only use Float textures in Bevy? For displaying medical images (mostly u16 pixel) I would need to use sample_type: TextureSampleType::Uint. In the shader I use utexture2D and usampler2D, maybe this information is available to SPIRV reflection?

However when puttting a breakpoint there and inspecting the SPIRV type description I see image_format: spirv_reflect::types::image::ReflectImageFormat::Undefined.

**Comment by alice-i-cecile** [comment]
That sounds correct. it should be a reasonably simple feature to add and it's a very reasonable feature request. If you'd like to take a crack at it; work off of the `pipelined-rendering` branch, which contains our rendering rework.

**Comment by vsaase** [comment]
Thanks for the encouragement. I took a look at the `pipelined-rendering` sprite system. I could not find an interface to use custom shaders. At the moment the shader is hard_coded in `impl FromWorld for SpriteShaders` with a TODO comment above which says "this should be handled by the asset system". Does this mean SpriteShaders should be an asset and PipelinedSpriteBundle should have a handle to it?

**Comment by vsaase** [comment]
I started to make SpriteShaders an asset in my branch https://github.com/vsaase/bevy/tree/spriteshaders_asset 

At the moment it is a resource and an asset at the same time, where the view layout is still taken from the resource.
So it should be possible to use a custom shader and specify the sample type for individual sprites now.

**Comment by alice-i-cecile** [comment]
I'm going to defer to the experts on this; come say hi in `#rendering` on [Discord](https://discord.gg/82KezyXa) for more hands-on help and discussion.

**Comment by cart** [comment]
I can provide some clarity!

1. The old renderer does indeed have some reflection limitations. In some cases we need to be opinionated because there is more "pipeline configuration" than a shader can tell us. Reflecting the texture sample type is interesting because it is tied to the _texture binding_ not the _sampler binding_. But the shader defines the texture type in the sampler. Pairing an arbitrary texture and sampler is possible, but theres a one-to-many relationship afaik. To do this "right" we might even need to inspect call sites to see which texture uses which sampler. Bleh. 
2.  The new renderer favors explicitness over implicitness. Currently that means more typing, but fewer lossy abstractions and significantly clearer code. We're slowly building up solid higher level abstractions, but it is still a work in progress.
3. Custom shaders in the new renderer are what I'm currently working on. The `pipelined-rendering` branch is pretty behind at this point. Check out my [custom-shaders](https://github.com/cart/bevy/tree/custom-shaders) branch for the latest code. Its not ready yet, but it already solves a lot of the "code reuse problems". You're welcome to start exploring this, just keep in mind that this is still WIP / experimental code. There are a number of rough edges and missing pieces.
4. The [custom_shaders_pipelined example](https://github.com/cart/bevy/blob/custom-shaders/examples/shader/custom_shader_pipelined.rs) is probably the most relevant to you. Still way more explicit that this class of thing should be, but notice that its reusing bind groups / draw code from the pbr pipeline. I don't like how it compiles the pipeline in the RenderAsset prepare step ... that was just laziness on my part as I was experimenting. Our approach to shader and pipeline compilation is still very placeholder-ey.

**Comment by vsaase** [comment]
thanks! I came up with a similar solution in my branch https://github.com/vsaase/bevy/tree/spriteshaders_asset with RenderAssets and removed the SpriteShaders resource in render world. That was a good exercise to get to know Bevy. I appreciate that you are working on exactly this
