### ISSUE TITLE
Implement Bundle for every component and simplify API

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy#2974]
## What problem does this solve or what need does it fill?

The distinction between components and bundles is often lost on new users, and we end up with a lot of redundant, nearly-duplicated APIs.

## What solution would you like?

Implement Bundle for every Component, representing the one element bundle containing only that component.

Remove all duplicated API surfaces, keeping the `Component` names but accepting bundles:

- `insert` and `insert_bundle` -> `insert`
- `remove` and `remove_bundle` -> `remove`
- remove `spawn_bundle`; there's now less boilerplate and the design of this routinely confuses the mental model for new users

There are some additional benefits:
- we can remove the #[bundle] annotation in the #[derive(Bundle)] crate
- spawn_batch becomes much easier to work with for simple 0 and 1 component cases
- users cannot accidentally derive component on a standard bundle, as conflicting impls will exist

## What alternative(s) have you considered?

Just leave it as is.

## Additional context

Design credit to @BoxyUwU, @TheRawMeatball and @Frizi. Originally described here: https://hackmd.io/EvBrYLQeQbCjE2eycBlo3w

Made possible by #2254!

**Comment by cart** [comment]
I don't think we should move forward on this until we resolve the "how do Bundles relate to scenes and editor experiences" conversation (ex: https://github.com/bevyengine/bevy/issues/3833#issuecomment-1026268582 and the various discussions we've had on discord). Bundles might be promoted to "metadata that exists on entities" and might expand to include "prefab-like" contexts.

I'm also personally against this because it further blurs the lines between components and bundles, which our users constantly mess up in their mental models and in their code. `#[derive(Component)]` has helped in that regard.

Pulling in @bevyengine/ecs-team as this is pretty fundamental stuff.

**Comment by alice-i-cecile** [comment]
> I'm also personally against this because it further blurs the lines between components and bundles, which our users constantly mess up in their mental models and in their code

I agree with this:  but I actually think that this change will help.

Fundamentally, this user confusion is driven by the fact that bundles are treated as a distinct concept by our APIs: particularly spawn_bundle and insert_bundle.

I think we should:

1. Go forward with this change.
2. Change the name of the `Bundle` trait to `ComponentBundle` and use "bundle of components in our docs".
3. Eliminate `insert_bundle` and `spawn_bundle`.

This removes the concept of "bundles" from our API calls, and reinforces that `#[derive(ComponentBundle)]` results in a bundle of components, rather than this nebulous disconnected concept. 

> Bundles might be promoted to "metadata that exists on entities" and might expand to include "prefab-like" contexts.
IMO if this exists, it should not use `Bundles`: it should be a separate concept that stores a bundle internally. A "collection of components" is a foundational idea: there's no need to overload it when we can just wrap it.

**Comment by alice-i-cecile** [comment]
> > Bundles might be promoted to "metadata that exists on entities" and might expand to include "prefab-like" contexts.

> IMO if this exists, it should not use Bundles: it should be a separate concept that stores a bundle internally. A "collection of components" is a foundational idea: there's no need to overload it when we can just wrap it.

#3877 is a solid vision of what this would look like in practice.

**Comment by DJMcNab** [comment]
My thinking around this is that behaviour only makes sense in relation to a combinations of components on the entity.
And so `Bundles` are helpers to get a useful combination of components, and thus have no meaning beyond their constituent components.
This seems to me to be the only way to maintain coherent behaviour with the underlying systems operating on components.
Which encapsulates how multiple bundles of the same 'kind' (e.g. rendering: `SpriteBundle`, `PBRBundle`, camera: `OrthographicCameraBundle`, `PerspectiveCameraBundle`) don't compose.

With this view, unifying the apis which deal with `Bundle`s and `Component`s is natural.

**Comment by djeedai** [comment]
All agreeing with the above from @alice-i-cecile and @DJMcNab, but I thought this feature was further along / already implemented, so let me present another use case that is blocked until this is implemented: fluent-style component construction. In `bevy_tweening` we have an `Animator` component which animates another component. Although this _can_ be added manually, a much nicer way to do this in other libraries / languages is to do something like this (pseudo-code):

```
my_component.move_to(Vec3(1,2,3))
```

For Bevy, this could be implemented with a trait:

```rust
pub trait TransformAnimation {
  fn move_to(&self, dst: Vec3) -> (Transform, Animator);
}

impl TransformAnimation for Transform {
  pub fn move_to(&self, dst: Vec3) -> (Transform, Animator) @cart 
}
```

**Comment by urben1680** [comment]
Hello, I stumbled onto this and I noticed it would make my component-flag-components not work anymore.

Let me first describe the use case, some code snippets are simplified.

In some cases I don't want to immediately despawn an entity, component or resource because I might want to undo that with my rollback feature I work on currently. So instead of removing `T`, I add a `Despawned<T>` (zero sized type) next to it and make my systems filter for that flag to not exist if I want `T` or I check it's existence before I evaluate if `Option<T>` could be `Some`. That seems more sane to me than reallocating it into a buffer as I expect to jump back and forth quite often. 

The actual removing of `T` will be done at a later point I don't want to go into details here. Same for the case where we talk about spawning and not despawning.

Example system signatures:
```rs
fn my_system_1(r1: Res<A>, r1d: Option<Res<Despawned<A>>) //has to skip inner body if `r1d` is `Some`
fn my_system_2(query: Query<(&A, Without<(Despawned<A>, Despawned<Entity>)>)>)
```

Now when I want to work with commands, I want to use a custom command.
Instead of `commands.entity(my_entity).remove::<C>()` I add the following command:

```rs
struct RemoveComponent<C: Component>{
    entity: Entity,
    component: PhantomData<C>
}

impl<C: Component> Command for RemoveComponent<C>{
    fn write(self, world: &mut World) {
        world.entity_mut(self.entity).insert(Despawned::<C>::default());
    }
}
```

However, if `C` can be a bundle too after this PR then I wonder how I can prevent `Despawned<(C1, C2)>` to be inserted when I actually want to insert both `Despawned<C1>` and `Despawned<C2>` in that case.

**Comment by DJMcNab** [comment]
Which impl do you think will cause `(C1, C2)` to be `Component`? This PR only adds new implementations of `Bundle`.

**Comment by alice-i-cecile** [comment]
> However, if C can be a bundle too after this PR then I wonder how I can prevent Despawned<(C1, C2)> to be inserted when I actually want to insert both Despawned<C1> and Despawned<C2> in that case.

This still works fine: `Component` will continue to exist, and represent exactly one component. This PR only blurs the opposite direction: a single component will be able to be treated as a bundle, but arbitrary bundles will not be represented as components.

**Comment by urben1680** [comment]
Oh then I misunderstood this proposal! Thanks for making this clear to me.
