### ISSUE TITLE
Scale for OrthographicProjection

### ISSUE THREAD

**Issue by ahfuckme** [bevyengine/bevy#308]
Right now, the `OrthographicProjection` seems to have the units in pixels, which makes any 3d renders very small compared to the same render using `PerspectiveProjection`. Perhaps there should be a `Scale` field added to the `OrthographicProjection` and used [here](https://github.com/bevyengine/bevy/blob/7b6fbcb932f240e7789bb4ea292cff7eb3682cc9/crates/bevy_render/src/camera/projection.rs#L79) to allow one to shrink the very wide field of view.

**Comment by jpetkau** [comment]
Just ran into this too. It will use a scale attached to the entity, and `Camera2dComponents` adds a uniform scale, but since it's a *uniform* scale it scales in XYZ, which messes up the depth (in a 2D game, if scale <1.0, then sprites don't draw at all because they're outside of zmin..zmax).

At minimum it needs a nonuniform scale, which means you can't use `Camera2dComponents` (or you need to manually remove the uniform scale that it creates.)

Ideally I think `OrthographicProjection` should replace `window_origin` with a more explicit enum that covers more options, something like:

- pixels with (0,0) in lower-left, Y up
- pixels with (0,0) in top-left, Y down
- pixels with (0,0) at center, Y up
- H units tall and/or W units wide, with different aspect ratios handled as:
  (1)  H exact, adjust W to preserve aspect ratio
  (2) W exact, adjust H to preserve aspect ratio
  (3) minimum of (1) or (2)
  (4) maximum of (1) or (2) 
  (5) exactly H*W, so don't preserve 1:1 aspect ratio

**Comment by alice-i-cecile** [comment]
I believe this was solved by #400 getting merged :)
