### ISSUE TITLE
`Changed` doesn't explain any potential drawback

### ISSUE THREAD

**Issue by djeedai** [bevyengine/bevy#3082]
## How can Bevy's documentation be improved?

https://docs.rs/bevy/0.5.0/bevy/ecs/query/struct.Changed.html

The docs mention this is a performance optimization to iterate over changed entities/components only. There's no mention of what the cost of maintaining such information is. Surely this doesn't come "for free"; there must be some caching somewhere to compare with the previous frame's version and be able to tell. What's the cost? Can this be used on many different single-components (like, should I use `Changed<MyType>` for most of my own types, even if used once or twice only)? Or is it more beneficial on a single component with many instances (like the `Changed<Transform>` example? Is there a minimum order of magnitude number below which `Changed` is prohibitive compared to just iterating over all existing items without any caching?

I checked the docs on `main` too, and it's no better. It just mentions `ChangeTrackers` in addition; I'm not even understanding the difference between `ChangeTrackers` and `Changed`.

**Comment by bjorn3** [comment]
Every time you mutate a component, the "tick" at which it changed is stored. `Changed<T>` compares the stored "tick" of the component with the "tick" at which the system ran last. If it is later, this means that the component changed since the last time. This "tick" identifier is a single u32, so a 4 byte overhead per component per entity.

**Comment by djeedai** [comment]
Unless there's another alternative I'm not seeing, you can't know if a system mutated a component unless either 1) you assume that any `ResMut<>` query means a mutation (conservative, but has false positives), or 2) you do a diff of the pre- and post- version of the component. So either it's 1) and `Changed` is less powerful that it says, or it's 2) and there's a cost not mentioned. Isn't it?

**Comment by cart** [comment]
You're missing option 3: utilize rust's DerefMut implementation to automatically overwrite the tick whenever a component or resource is accessed mutably. This means just querying for these things isn't enough to trigger a mutation. You must actually mutate (according to the rust compiler). Of course, you could mutate a component by setting to the exact same value, but I think this is the correct tradeoff relative to actually diffing components.

We need recording a change to be very cheap (because mutations can happen frequently), so its literally _just_ setting the tick value. We don't collect a list of mutated entities because allocating on mutation to populate a list (and de-duplicating the list) would be prohibitively expensive. We also don't do actual-value comparisons for the same reason. The tradeoff we landed on is that iterating Changed components checks every component's tick for the given type: we iterate every component of the given type ... not just the changed ones. This happens internally and users just receive actual Changed components.

**Comment by cart** [comment]
Ah the doc in question _is_ wrong though: 

> This filter is useful for synchronizing components, and as a performance optimization as it means that the query contains fewer items for a system to iterate over.

I think something was lost in translation here by the doc author: Changed can be used _as_ a way to optimize expensive operations by only doing them for changed components. The act of iterating changed components can actually be _slightly more_ expensive than iterating all components of a given type because we need to check the tick in addition to retrieving the component for changed entities (although it might be faster in some cases because we dont actually need to retrieve unchanged components).

**Comment by djeedai** [comment]
Ok thanks for the detailed explanation. That's 1b) really, under the general umbrella of "assume modified on mutating getter". Don't get me wrong, that's absolutely the right thing to do for sure, but the details should probably be explained in the docs to call out the potential false positive (which _may_ matter I'm some cases) and the extra work you mention. I'll try to make a proposal PR.

**Comment by cart** [comment]
Sounds good to me!

**Comment by djeedai** [comment]
@cart the current docs says:

> Filter that retrieves components of type `T` that have been changed since the last execution of this system.

Is that really the case?! I'd assume if system A mutates a component, system B filtering with `Changed<T>` will observe that change in the same frame if it runs after system A, no? The change detection is per component, not per system if I understand correctly how it works (`ComponentTicks`).

**Comment by bjorn3** [comment]
A system doesn't have to run every frame. The nice thing about bevy's change detection is that skipping a system won't break change detection. It will report it the next time the system runs. That is why every system has it's own "tick" indicating when it ran the last time that is compared with the component "tick" indicating when it was changed the last time.

**Comment by djeedai** [comment]
Thanks, but that's not exactly the question. Sure, it's nice that if a system doesn't tick a frame, `Changed` still works. But I'm more interested in confirming that if _e.g._ 2 different systems are changing a component then `Changed` will be "triggered" on both changes. And also that if a system changes a component then a second system running after it in the same frame will also see the changed component. The docs currently saying "since the last execution of this system" seem to imply that `Changed` is a per-component **but also per-system** change detection; this is not the case as I understand, whatever the source of the change `Changed` will record it equally.

**Comment by djeedai** [comment]
Opened PR #3084, we can iterate on proper wording there.

**Comment by cart** [comment]
> Thanks, but that's not exactly the question. Sure, it's nice that if a system doesn't tick a frame, Changed still works. But I'm more interested in confirming that if e.g. 2 different systems are changing a component then Changed will be "triggered" on both changes.

I think @bjorn3 did pretty much answer your question by saying that each system has its own tick, which is compared against the component tick. Change detection is _per system_. If a change (which happened anywhere / in any system) occurred since the last time a system ran, the change will show up in that system's Change queries.

**Comment by cart** [comment]
Removed from the milestone because this isn't really _needed_ for the release and we're nearing the cutoff point. If it makes it in, thats cool though :)

**Comment by alice-i-cecile** [comment]
I don't think this is particularly relevant any more. Closing.
