### ISSUE TITLE
Bevy has implicit dependency on `anyhow` which users need to explicitly add

### ISSUE THREAD

**Issue by djeedai** [bevyengine/bevy#3138]
## Bevy version

Both 0.5 and `main`

## Operating system & version

Windows 10 (likely irrelevant)

## What you did

- Copy [the `custom_asset.rs` example code](https://github.com/bevyengine/bevy/blob/main/examples/asset/custom_asset.rs) into my app

## What you expected to happen

Code builds.

## What actually happened

Code doesn't build because it depends on `anyhow::Result` and `anyhow::Error`.

## Additional information

The examples are built with:

```toml
[dev-dependencies]
anyhow = "1.0.4"
```

which is why they build successfully. This means Bevy is implicitly asking users to add this dependency to their project if they want to implement the `AssetLoader` trait, whose `load()` function returns `anyhow::Result<(), anyhow::Error>>`.

We discussed this briefly with @alice-i-cecile [on Discord](https://discord.com/channels/691052431525675048/909179710599217184) and I believe that there are two possible ways to fix:

1. Acknowledge that this is by design, and Bevy does want you to add those dependencies. If so, this needs to be documented.
2. Consider this a bug, and investigate workarounds like re-exporting the `anyhow` dependency (see rust-lang's issue [Guidance on reexporting](https://github.com/rust-lang/api-guidelines/discussions/176) for details) so that Bevy users don't have to do it. Or alternatively define public aliases for those types which I _think_ would solve this too. In any case, I believe the `dev-dependencies` section is not to be used for this kind of thing, but rather for dependencies used by the example itself (as opposed to by Bevy via the example).

I have a strong preference for anything except 1. as this feels awkward and cumbersome.

**Comment by wilk10** [comment]
yeh i have run into it a bit. it's not a super big deal, but a bit odd. 
thanks a lot for the write up. 
i also would prefer option 2, if possible

**Comment by qm3ster** [comment]
nitpick: saying `anyhow::Result<(), anyhow::Error>` instead of `anyhow::Result<()>` or ~~`core::result::`~~`Result<(), anyhow::Error>` is redundant.
I'm only bringing this up because this involves *what* needs to be aliased/reexported.
At a glance, I would say `anyhow::Error`, and not the `Result<T, E = anyhow::Error> = core::result::Result<T, E>` alias.
Which means that for best docs, the return type of public functions should probably be written as `Result<OurType, ReexportedAnyhowErrorName>`.
Other preferences are possible of course, this is worth having a look at.
