### ISSUE TITLE
Add issue, feature proposals and PR template

### ISSUE THREAD

**Issue by qarmin** [bevyengine/bevy#326]
For now are empty, but sometimes providing e.g. OS version, bevy version, minimal project to reproduce is very helpful to reproduce bugs.

There should be also different templates for issues and feature proposals.

https://github.com/godotengine/godot/tree/master/.github/ISSUE_TEMPLATE

**Comment by lberrymage** [comment]
It would also be nice to have this to prevent needing commits like 972897690b0f73e0fd7ee4bbc042f7c8c44d5f8d, which added a changelog entry for past commits since the 0.1.3 release. There have been [a] [few] [changes] since then and none of them have a changelog entry, probably because people just tdon't think to.

At least adding a pull request template with

- [ ] - I have added an entry to the changelog if necessary

would be beneficial on that front.

It'll also worth considering the "automatically add a label" feature of these templates for basic labels like "bug" and "enhancement".

[a]: https://github.com/bevyengine/bevy/pull/332
[few]: https://github.com/bevyengine/bevy/pull/339
[changes]: https://github.com/bevyengine/bevy/pull/430
