### ISSUE TITLE
Type 'core::time::Duration' does not support ReflectValue serialization

### ISSUE THREAD

**Issue by shelbyd** [bevyengine/bevy#3277]
## What problem does this solve or what need does it fill?

I'm building a general purpose plugin for doing rollback networking for bevy and a game using that. To support clients reconnecting after disconnect, I need to serialize relevant state and transmit it to reconnecting clients. It's common for `Timer`s to be relevant for gameplay logic, and those require serializing `Duration`s.

## What solution would you like?

Implement `ReflectValue` serialization for `Duration` and other `core` types. 

## What alternative(s) have you considered?

To unblock myself, I can reimplement `Timer` and `Duration` with a custom `MyDuration` type that derives `Reflect`. Doing that is not ideal for a myriad of reasons, but probably necessary to continue progress on my project.

**Comment by alice-i-cecile** [comment]
This is a very reasonable requirement. If you're comfortable with it, this should be a fairly straightforward PR.

**Comment by shelbyd** [comment]
If you can point me to the relevant file(s), I'm happy to do it myself.

**Comment by alice-i-cecile** [comment]
Usually, we'd just use a `#[derive(Reflect)]` macro invocation (as seen in the [examples](https://github.com/bevyengine/bevy/blob/main/examples/reflection/reflection.rs)), but that won't work here, as we need to implement the trait for a foreign type.

Similarly, we can't put this in `bevy_core` with the other time logic, since we don't own the Reflect trait there.

I would probably start a new file (`time.rs`) in [this folder](https://github.com/bevyengine/bevy/tree/main/crates/bevy_reflect/src/impls) and implement the trait there for `Duration` and `Instant`.

The other examples in that folder should provide a nice guide, but feel free to reach out here or on your PR if you run into difficulties.

**Comment by cart** [comment]
Duration is an `std` type, so it should probably go in the existing `std` module in the impls folder, but other than that I agree with @alice-i-cecile's recommendations.

**Comment by jcornaz** [comment]
I opened a PR that solves this issue. @shelbyd, I hope you don't mind that I didn't let you solve it yourself. I just stumbled into this problem too. And since the problem it's pretty annoying, yet easy to fix, I just couldn't help but open a PR.
