### ISSUE TITLE
bevy_sprite::Rect is not the same as bevy_math::Rect

### ISSUE THREAD

**Issue by tatref** [bevyengine/bevy#335]
These 2 `Rects` are not compatible. It's also misleading, because bevy_math::Rect is in the prelude.

Could they be merged together? Should they?

**Comment by JonahHenriksson** [comment]
I don't think they should be merged together since they measure different things. `bevy_sprite::Rect` is capable of defining the width and height of a rectangle, while `bevy_math::Rect` defines the location of its sides. In this sense, `bevy_sprite::Rect` is more like a `bevy_math::Size` with a location. I also think it is misleading,and one should be renamed. I think `bevy_ui::Margins` should be removed and replace `bevy_math::Rect` since they are the same thing.
