### ISSUE TITLE
Swap to using EventWriter and EventReader in internal engine code

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy#3397]
Many of our internal systems were written before the advent of `EventWriter` and `EventReader`, and so work with either `ResMut<Events<T>>` or `Res<Events<T>>`.

These can (and probably should) generally be swapped to `EventWriter` and `EventReader` because:

1. The intent is clearer, making the code easier to later modify and read.
2. The API is smaller, making it harder for subtle bugs to be introduced.
2. Any later optimizations we might perform will rely on `EventReader` and `EventWriter`, rather than the raw resource types.

You can see an example here: https://github.com/bevyengine/bevy/blob/e48f9d8cd4562d5ea6b483764ae9288feb13cc72/crates/bevy_gilrs/src/gilrs_system.rs#L19

Finding all of these should be easy, just search for `Res<Events` and `ResMut<Events` in the code base. Fixing them should be similarly straightforward, although please leave a comment in your PR if you found any usages that could not be trivially converted.

**Comment by PaperCow** [comment]
I wasn't actually able to find any other references to `Res<Events` or `ResMut<Events` in the code base outside of the given example. It appears they were mostly removed in #1244 and #1575 but the example given in this issue was added after these PRs.

Assuming I'm not just missing some other references, I made a PR #3413 to clean up this one instance.
