### ISSUE TITLE
`OrthographicCameraBundle::with_name` creates some inconsistent camera

### ISSUE THREAD

**Issue by djeedai** [bevyengine/bevy#3487]
## Bevy version

HEAD

## Operating system & version

All

## What you did

Look at code.

## What you expected to happen

By analogy with `PerspectiveCameraBundle::with_name`, and for consistency with either `OrthographicCameraBundle::new_2d` or `OrthographicCameraBundle::new_3d`, the `OrthographicCameraBundle::with_name` should create the same camera as either `new_2d` or `new_3d` and only change its name.

## What actually happened

The camera created by `with_name` is an unrelated camera with a different scaling mode from the one of `new_3d` and a different depth calculation of the one of `new_2d`.

## Additional information

https://github.com/bevyengine/bevy/blob/601cc0cbe3dc73c0db1993184f4ec47783e83884/crates/bevy_render/src/camera/bundle.rs#L139-L161

**Comment by bytemuck** [comment]
My point of view on this is that `OrthographicCamera::with_name()` should return the same exact `OrthographicCameraBundle` that `OrthographicCamera::new_2d()` returns, but with the name passed as argument, because most orthographic cameras (in other game engines) are basically 2d cameras and it's relevant to do this in my opinion. That being said, we could maybe just call `with_name(CameraPlugin::CAMERA_2D.to_string())` inside `OrthographicProject::new_2d()`

**Comment by devil-ira** [comment]
This API no longer exists. `Camera` does not have a `name` field anymore.
