### ISSUE TITLE
Why are a lot of data structure names pluralized?

### ISSUE THREAD

**Issue by haselkern** [bevyengine/bevy#353]
Example: [TextComponents](https://docs.rs/bevy/0.1.3/bevy/prelude/struct.TextComponents.html). It is a component that represents a single text. Why is it not called TextComponent? This might be a silly issue, but I find this confusing, especially when reading code.

**Comment by Bobox214** [comment]
This is not a single component, but a bundle of multiple components allowing to describe a Text.
A created entity with this bundle will have at least a Draw component , a Translation component etc.

So all of the XXXComponents, are pluralized because they are a bundle of components and you need to be aware of it. ( You need to use .with_bundle and not .with ).

**Comment by haselkern** [comment]
Oh, so TextComponents = Components for drawing a text? In that way it makes a lot of sense! Thanks for the quick clarification!
