### ISSUE TITLE
Percentage Closer Soft Shadows

### ISSUE THREAD

**Issue by superdump** [bevyengine/bevy#3631]
# Description

- Light sources have a physical size and are not just points. This means that occluding/blocking the light rays coming from a physical source do not result in a receiving surface being either fully lit or fully in shadow, but rather from fully lit, gradually fading through the so-called 'penumbra' to being fully in shadow (known as 'umbra'). Shadows with hard edges do not look physically correct, and while many might accept them, the visual improvement from having realistic soft shadows adds a lot to the atmosphere of a scene.

## Solution

- Support **Percentage Closer Soft Shadows**
- https://github.com/superdump/bevy/tree/shadow-pcss
  - Builds on top of #3628 to add support for _PCSS_ but is buggy
  - I tried to get **Adaptive Depth Bias for Soft Shadows** (Ehm et al 2015 - https://w3-o.cs.hm.edu/users/nischwit/public_html/AdaptiveDepthBias_WSCG.pdf) working but didn't manage to fix the bugs in my implementation yet so rather resorted to explicitly re-calculating the optimal fragment depth and adaptive epsilon at each offset sampling position so that I could first get the PCSS implementation working properly.

## Next Steps

- Fix PCSS bugs
- Fix Adaptive Depth Bias for Soft Shadows approach for a very significant performance increase
- Make a PR

**Comment by torsteingrindvik** [comment]
I was looking at all issues with the mention of "shadows" in order to see if there was one that tackled issues with point light shadows.

Currently on 0.13:

![image](https://github.com/bevyengine/bevy/assets/52322338/3d22d296-53fe-4cb7-a0a3-b3c763f6df55)

I saw you mentioned point lights in a commit msg in the branch you linked to, so I'm guessing this is the right place.

Commenting in order to show that the issue is still relevant and perhaps others wondering about point lights might see this and can subscribe to the issue too.

**Comment by pcwalton** [comment]
@torsteingrindvik That is point light filtering, not PCSS, and I added it a while ago in `main`.
