### ISSUE TITLE
Panic when too many point lights exist

### ISSUE THREAD

**Issue by lee-orr** [bevyengine/bevy#3682]
## Bevy version
bevy 0.6

## Operating system & version
Windows 10

## What you did
I created a simple system like this: 
```rust

fn setup(
    mut commands: Commands,
) {
    commands.spawn_bundle(PointLightBundle {
        point_light: PointLight {
            color: Color::WHITE,
            ..Default::default()
        },
        transform: Transform::from_rotation(Quat::from_euler(EulerRot::XYZ, 0., 15., 30.)).with_translation(Vec3::Y * 3.),
        ..Default::default()
    });
}
```
and added it to the app like so `app.add_system(setup);`. This lead to the creation of an additional point light every frame

## What you expected to happen

I'd expect the lights to eventually start getting ignored, but the system to keep running

## What actually happened

The app ran for 255 frames, and panicked on frame 256 with the following error:
`thread 'main' panicked at 'index out of bounds: the len is 256 but the index is 256', *PATH*\.cargo\registry\src\github.com-1ecc6299db9ec823\bevy_pbr-0.6.0\src\render\light.rs:650:9`

## Additional information

For my situation, I fixed things by moving to a startup system. However, this should not result in a panic either way.

**Comment by superdump** [comment]
Thanks for the report. I see what the problem is and I have indirectly fixed it in my branch that implements storage buffer support for point lights as I make sure to only take the first 256 lights to write into the uniform buffer when storage buffers are not supported. See here for more information: https://github.com/bevyengine/bevy/issues/3605 It would probably be better to only take at most 256 lights from the iterator, when there is a hard limit to adhere to.
