### ISSUE TITLE
WgpuOptionsPriority::Functionality overwrites app preferences with suboptimal configuration

### ISSUE THREAD

**Issue by djeedai** [bevyengine/bevy#3686]
## Bevy version

0.6.0

## Operating system & version

Windows 10 (but issue is independent)

## What you did

Run any app on Windows 10 NVIDIA GeForce RTX 2070 with Vulkan.

## What you expected to happen

No warning.

## What actually happened

```
WARN wgpu_core::instance: Feature MAPPABLE_PRIMARY_BUFFERS enabled on a discrete gpu. This is a massive performance footgun and likely not what you wanted
```

## Additional information

I tried setting explicitly `Features::MAPPABLE_PRIMARY_BUFFERS` off in `WgpuOptions`, without success.

Eventually I ran under debugger and found that the default `WgpuOptionsPriority` value is `Functionality`, which in `bevy_render` while creating device will override any app's setting with those of the selected adapter:

https://github.com/bevyengine/bevy/blob/8e1f660e1db77434d96626d3e40ecd0edfc71b54/crates/bevy_render/src/renderer/mod.rs#L88-L92

While this makes sense for a lot of those settings, like the various hardware limits, this makes no sense for several flags which being reported by `adapter.features()` only inform the app that the GPU supports the feature, but in no way was intended to tell the app that this is an optimal feature to use. This is the case in particular for `MAPPABLE_PRIMARY_BUFFERS` which is supported on an RTX 2070 but as the warning shows is strongly discouraged. Yet the `bevy_render` code simply set `options.features = adapter.features()` indiscriminately.

**Comment by superdump** [comment]
Good catch. So we should:
1. Check for other such features that are not recommended to be used by default and disable them.
2. Respect any user-defined settings.

**Comment by superdump** [comment]
kvark from wgpu noted that enabling all supported features by default is a 'very bad practice'. I'm investigating what to do about this. (FYI @cart )

**Comment by superdump** [comment]
I just realised that as bevy’s core renderer only uses WebGL2 functionality at the moment pretty much, you could use the Compatibility priority without problem or loss of core renderer functionality, aside from the lower limits, but those could be overridden.

**Comment by superdump** [comment]
I have added this to the 0.6.1 milestone, but _only_ for the "do not automatically enable mappable primary buffers" (and any other such 'risky' features to enable by default. The rest that is about how to improve the configuration of wgpu features and options should be for 0.7.

**Comment by superdump** [comment]
Some noted unexpected bad performance that for at least one case is probably due to this issue: https://github.com/bevyengine/bevy/issues/3687

**Comment by superdump** [comment]
Here is a PR for the basic fix of not automatically enabling mappable primary buffers: https://github.com/bevyengine/bevy/pull/3698

**Comment by inodentry** [comment]
Is MAPPABLE_PRIMARY_BUFFERS an improvement on systems with resizable BAR?

**Comment by superdump** [comment]
> Is MAPPABLE_PRIMARY_BUFFERS an improvement on systems with resizable BAR?

It varies I think. I would think M1 macs could benefit quite a bit due to not even having to copy buffers, just map them and write straight into them.

**Comment by BGR360** [comment]
> I would think M1 macs could benefit quite a bit due to not even having to copy buffers, just map them and write straight into them.

wgpu fires the same warning on my M1 Pro macbook, FYI. Would that indicate that wgpu knows it not to be of any benefit for that platform? Or is it more likely that wgpu just always prints that warning even on platforms that might benefit from it?

Also, what is BAR? 😁

**Comment by superdump** [comment]
> > I would think M1 macs could benefit quite a bit due to not even having to copy buffers, just map them and write straight into them.
> 
> wgpu fires the same warning on my M1 Pro macbook, FYI. Would that indicate that wgpu knows it not to be of any benefit for that platform? Or is it more likely that wgpu just always prints that warning even on platforms that might benefit from it?

The M1 GPU is classed as a discrete GPU by wgpu for some reason. Maybe because it's in the same performance/power class as discrete mobile GPUs, even though it is integrated into a system-on-chip-like processor architecture. I think wgpu just outputs the warning for any discrete GPU when the mappable primary buffers feature is enabled.

> Also, what is BAR? 😁

Base Address Register. I am not certain of the details so this is a bit of a guess, but having a resizable base address register allows direct mapping of video RAM for operation on by the CPU. For discrete GPUs with their own dedicated video RAM which is connected to the PCI-E bus, for the CPU to operate on the data, it has to be communicated over the PCI-E bus between the CPU and video RAM. The 'Apple Silicon' processors have the CPU, GPU, and a shared memory controller on the same chip, and the shared RAM chips on the same 'package' (mounted onto the same circuit board, right next to the processor). There is no need for any transfer with this kind of unified memory architecture (I think most mobile System-on-Chip solutions have this kind of architecture too where the CPU, GPU, and a shared memory controller are built into one chip, and they communicate directly with nearby memory chips) as both the CPU and GPU can directly address (access) the data stored in the memory chips.

**Comment by bjorn3** [comment]
The BAR is a PCI concept. It is basically a part of the address space that is backed by a PCI device rather than RAM. Without resizable BAR I believe the PCI device has to pick a fixed size. Most GPU's pick 256MB as size I believe for compatibility with 32bit systems (as their total address space is only 4GB), thus only allowing direct access to 256MB of vram from the CPU. With resizable BAR it becomes possible to make it bigger at runtime on 64bit systems thus allowing the BAR to cover the entire vram.

**Comment by BGR360** [comment]
> The M1 GPU is classed as a discrete GPU by wgpu for some reason

Is there an issue open on wgpu for this yet?

**Comment by superdump** [comment]
> > The M1 GPU is classed as a discrete GPU by wgpu for some reason
> 
> Is there an issue open on wgpu for this yet?

Not yet.

**Comment by superdump** [comment]
Just a note that the categorisation of M1 as discrete has been fixed upstream and I made another PR that enabled mappable primary buffers for integrated GPUs. #3803
