### ISSUE TITLE
How to intercepts the close button event?

### ISSUE THREAD

**Issue by GISerliang** [bevyengine/bevy#3710]
## What problem does this solve or what need does it fill?

I wanted to show some tips before close app when clicked the close button.

## What solution would you like?

I tried to these codes, but not work. 
```
.add_system_set(
                SystemSet::on_update(RgsApplicationWindowState::Exiting).with_system(quit.system()),
            )

fn quit(mut app_state: ResMut<RgsApplicationWindowState>) {
    println!("quit: {:?}", app_state);
}
```

**Comment by DJMcNab** [comment]
The `WindowCloseRequested` event is (currently) handled by the `exit_on_window_close` system:
https://github.com/bevyengine/bevy/blob/458cb7a9e93dab3127bb99ce7bf8cfc3af18851d/crates/bevy_window/src/system.rs#L4-L11

To stop the close button from working, you'd want to disable this system by modifying the `WindowPlugin`'s `exit_on_close` field to `false`. This could be done with the following instead of your normal `add_plugins(DefaultPlugins)` call:
```rust
.add_plugins_with(DefaultPlugins, |group| group.disable::<WindowPlugin>())
.add_plugin(WindowPlugin {exit_on_close: false, ..Default::default()})
```

As an aside, your reasoning for wanting this seems quite stange. The reason someone will be closing your app is because they want to leave it; showing tips at that time seems quite user-hostile.
I'd recommend that you also add a way to close the app once the tip has finished. I suppose you could also have one of the tips be "to close this program, use task manager or equivalent for your system".

**Comment by GISerliang** [comment]
> The `WindowCloseRequested` event is (currently) handled by the `exit_on_window_close` system:
> 
> https://github.com/bevyengine/bevy/blob/458cb7a9e93dab3127bb99ce7bf8cfc3af18851d/crates/bevy_window/src/system.rs#L4-L11
> 
> To stop the close button from working, you'd want to disable this system by modifying the `WindowPlugin`'s `exit_on_close` field to `false`. This could be done with the following instead of your normal `add_plugins(DefaultPlugins)` call:
> 
> ```rust
> .add_plugins_with(DefaultPlugins, |group| group.disable::<WindowPlugin>())
> .add_plugin(WindowPlugin {exit_on_close: false, ..Default::default()})
> ```
> 
> As an aside, your reasoning for wanting this seems quite stange. The reason someone will be closing your app is because they want to leave it; showing tips at that time seems quite user-hostile. I'd recommend that you also add a way to close the app once the tip has finished. I suppose you could also have one of the tips be "to close this program, use task manager or equivalent for your system".

Thank you. I did not stop the user to close app, I only want to give some informations whether the user have a wrong operation.

**Comment by DJMcNab** [comment]
Can we close this issue now?

By the way, in future help questions should generally be put as a discussion

**Comment by GISerliang** [comment]
> Can we close this issue now?
> 
> By the way, in future help questions should generally be put as a discussion

Sorry, thank you so much.
