### ISSUE TITLE
Sprite asset unloaded, while still in use

### ISSUE THREAD

**Issue by YannikSc** [bevyengine/bevy#3810]
## Bevy version

0.6.0 from crates.io

## Operating system & version

ArchLinux

```
$ uname -a
Linux yannik-linux-gaming 5.16.2-zen1-1-zen #1 ZEN SMP PREEMPT Thu, 20 Jan 2022 16:18:31 +0000 x86_64 GNU/Linux
```

## What you did

To make it easier to integrate textures into a bundle, I created a component, which holds the bare minimum of information, needed, to load a sprite (e.g. sprite path, dimensions).
Together with this LoadSprite component there is a system, which gets the and "converts" it into a sprite bundle (`Query<(Entity, &LoadSprite)>`, add the SpriteBundle, remove the LoadSprite).

## What you expected to happen

Expected is, that entities, spawned that way have a visible sprite

## What actually happened

But the opposite happens, in this short timeframe between despawning an entity with a given texture and spawing a new one, the texture seems to be unloaded, due to the despawn of the old entity.

## Additional information

It's easier to understand with an example, which can be found [here](https://gitlab.com/Yannik_Sc/bricks-rs/-/blob/feature/bevy-0-6/examples/texture_invisible.rs).

### How the example works
`S`: Spawn new entity at the cursor position
`D`: Despawn all entities
`R`: Despawn all entities, and spawn a new one at the same time - The bug appears here

**Comment by alice-i-cecile** [comment]
The example was very helpful to understand what was going on, thank you. 

Generally, the pattern is to hold onto strong handles to assets that you know you're going to need in a resource, to avoid the reference-counted assets from being cleaned up.  This will happen immediately, as it's checked whenever handles are dropped, so there's no way to know that you were about to use the handle again.

This behavior and pattern absolutely need to be better documented, but unless I'm missing something, this appears to be the expected behavior.

**Comment by YannikSc** [comment]
I have, for now, changed my code so that the handle is stored in a resource, but I still have the gut feeling, that this could cause some bigger problems, especially when it comes to bigger and more complex games.

It still feels like a bug for me though. But I guess documentation could do the trick.

**Comment by alice-i-cecile** [comment]
I agree, we need some more powerful and natural tools for asset handle management. That's out of scope for this issue though, so I'm going to close this out <3
