### ISSUE TITLE
Strange CannotWriteArchetype error.

### ISSUE THREAD

**Issue by kakoeimon** [bevyengine/bevy#382]
I cannot reproduce this error so I will share my project here.
I was changing irrelevant parts of my project when this error came into existance.
Edit: I deleted and closed the issue cause the error was from my misuse of Entity and the misunderstanfing of archetype ecs.

**Comment by GabLotus** [comment]
Hey thanks for raising that issue. Can you paste some of the key parts of the code so that people can view what is going on without necessarily having to open stuff in their text editors?

**Comment by EllenNyan** [comment]
Building with #383 seems to fix this or at least give a different error: 
> thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: NoSuchEntity'

which is caused by despawning the same entity twice, once that's fixed everything seems to work fine. (note that fixing the NoSuchEntity error and then trying to build without #383 still gives the old CannotWriteArchetype error)

**Comment by kakoeimon** [comment]
I close the issue and deleted it cause it was misleading.
