### ISSUE TITLE
Adding a method to the queries to get all the components at once

### ISSUE THREAD

**Issue by Boiethios** [bevyengine/bevy#395]
Given a query `Query<(&A, &B, &mut C)>`, a single component can be get with

    if let Ok(a) = query.get::<A>(entity) {
        // etc.
    }

but that would be handy to have a method that allows to get all the components:

    if let Ok((a, b, c)) = query.get_all(entity) {
        // etc.
    }

What do you think?

Or maybe, `get` could accept an arbitrary set of components:

    if let Ok((a, c)) = query.get::<(A, C)>(entity) {
        // etc.
    }

**Comment by cart** [comment]
Sadly `query.get_all(entity)` is impossible to implement as written because the types of `entity` are not statically known.

Fortunately your suggestion for `query.get::<(A, C)>(entity)` already exists in the form:

```rust
// where the query is: Query<(&A, &C)>
if let Ok(query_one) = query.entity(entity) {
  if let Some((a, c)) = query_one.get() {
  }
}
```

Needing the two "ifs" is a little bit quirky, but its the behavior of the current hecs implementation. I'm hoping we can improve this at some point.

**Comment by jamadazi** [comment]
@cart I think the OP meant `get_all` to do what your snippet does: return all the components in the Query, not all the components of the entity overall. Just fold the behaviour into one method call, to not require the two `if let`s.

This should be doable, and would be a nice convenience.  A method could just do what the snippet above does, and return a single `Result`.

**Comment by cart** [comment]
Yeah on a second read-through it does seem like I misinterpreted @Boiethios's intent. 

Consolidation of the two calls is easy (its basically the same as what i did for query.iter() in the flat_query branch). The issue is that doing so drastically dropped performance, so I didnt feel comfortable merging the change.

**Comment by jamadazi** [comment]
Oh wow, I wouldn't have expected such a thing to not be zero-cost. That sounds like a good reason to not have the method, then; don't want to mislead people into performance pitfalls. :)

I will add your snippet to bevy-cheatsheet to give it visibility.

**Comment by Boiethios** [comment]
> Yeah on a second read-through it does seem like I misinterpreted @Boiethios's intent.

Yep, sorry for not answering before, but that's as @jamadazi said: just returning the components from the query, so the type is known.

I don't understand why it creates a performance issue, but I hope it can be done in a further engine version :)
