### ISSUE TITLE
Bare-bones app crashes with "OutOfMemory"

### ISSUE THREAD

**Issue by emiln** [bevyengine/bevy#3990]
## Bevy version

From Cargo.lock:
```
[[package]]
name = "bevy"
version = "0.6.1"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "97342ea2f3bad36be2ded1d1fbd569ff83147b70697f12f1579e87a7480afa36"
```

## Operating system & version

Linux 5.11.0-43-generic #47~20.04.2-Ubuntu SMP Mon Dec 13 11:06:56 UTC 2021 x86_64 GNU/Linux

## What you did

1.  Create new app:
    ```
    cargo new memory-test && cd memory-test
    ```
2.  Fill out Cargo.toml:
    ```
    [toolchain]
    toolchain = "stable"

    [package]
    name = "memory-test"
    version = "0.1.0"
    edition = "2021"

    [dependencies]
    bevy = { version = "0.6" }
    ```
3.  Fill out `src/main.rs`:
    ```
    fn main() {
        App::new()
            .add_plugins(DefaultPlugins)
            .run();
    }
    ```
4.  Run the app while watching its memory with `htop` or similar:
    ```
    cargo build --release && ./target/release/memory-test
    ```
5.  After a couple of minutes of steadily rising memory consumption, the app crashes at ~650MB memory usage:
    ```
    thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: OutOfMemory', /home/emil/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-core-0.12.2/src/command/mod.rs:78:49
    ```

## What you expected to happen

I expected the memory to stay completely stable and not grow for this particular app.

## What actually happened

The memory consumption grew until it crashed with the following message:

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: OutOfMemory', /home/emil/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-core-0.12.2/src/command/mod.rs:78:49
```

## Additional information

I don't expect it to be relevant, but I'm running a very barebones VM: https://dwm.suckless.org/

**Comment by DJMcNab** [comment]
It's probably an issue in our code; but that failure suggests we're not handling wgpu resources correctly.

Would you mind checking if you can reproduce running any of wgpu's examples, to confirm it's not an issue caused by your setup?

(I think that's possible since I would have expected other users to have run into this if the reproduction is that simple, although you haven't found any similar issues)

If you feel confident doing so, please test the examples from the exact version of wgpu in your dependency tree/lockfile.

I wonder if your VM [sic] isn't handling vync properly, so you're running at ridiculously high framerates, leading to this appearing.

**Comment by emiln** [comment]
I'll try to do all of those after the kids are asleep. I would honestly not be completely flabbergasted to find that DWM is letting me down in some way. After I've tested your suggestions I might try again with Ubuntu's default desktop environment and see if it goes away.

**Comment by emiln** [comment]
I'm not super well versed in how Cargo actually works, but I checked my `Cargo.lock` and found:

* `wgpu-core` to be `0.12.2`
* `wgpu-hal` to be `0.12.4`
* `wgpu-types` to be `0.12.0`
* `wgpu` to be `0.12.0`

I wasn't entirely sure how to trace those back to a specific commit, but the `gfx-rs/wgpu` repo on GitHub had a ref called `v0.12` I could checkout (and nothing more specific like e.g. v0.12.0), so I ran the examples with that.

Running their first example

```
cargo run --example cube
```

reproduces the issue completely. I'll login with Ubuntu's default desktop environment and see if that solves it.

**Comment by emiln** [comment]
Interestingly, the issue also happens on whatever Ubuntu uses as its default desktop environment (GNOME, I think).

**Comment by emiln** [comment]
It also reproduces on the built-in Wayland desktop environment in Ubuntu 20 as well. Definitely seems to go beyond the particular way the windows are handled by the window manager.

**Comment by DJMcNab** [comment]
I think it's possible that you're seeing (claimed fixed without a root cause narrowed down) https://github.com/gfx-rs/wgpu/issues/2042.

Unfortunately, I don't think we can help you much here; you will need to try and get support from the wgpu folks. I don't have any good suggestions for next steps beyond that; it might be a driver issue, so it's worth seeing if there's an update available?

Thanks for the detailed report though, and thanks for looking into it.

**Comment by emiln** [comment]
Sure thing. I do agree this seems entirely unrelated to bevy and will probably be fixed after fiddling with some combination of updates to drivers, rust version, the OS if I have to. After all, it'd definitely have made waves already if this was a common issue for many people.

Thanks for the quick response.

**Comment by emiln** [comment]
Just for reference if any other unlucky soul gets into the same situation. The following fixed the issue completely with no changes to neither code nor dependencies:

```
sudo apt update && sudo apt upgrade && sudo reboot now
```

Just tech things, innit? :shrug:
