### ISSUE TITLE
TextComponents - Position changes with length of text

### ISSUE THREAD

**Issue by CleanCut** [bevyengine/bevy#401]
On macOS, just altering [this string slice](https://github.com/bevyengine/bevy/blob/8106f770de2ae3c841651499e0637123d7ae6688/examples/ui/ui.rs#L61) causes the vertical position of the text to change!

<img width="725" alt="rising-text" src="https://user-images.githubusercontent.com/5838512/91673505-a2594a00-eaf1-11ea-9eab-329e8cb70cc6.png">

**Comment by CleanCut** [comment]
The first shot is the normal `"Text Example"`.  The second alters it to be `"Text Example -- notice anything?"`.  The third is `"Text Example -- notice anything? Even more text 1234567890"`

**Comment by CleanCut** [comment]
Suggested labels: `bug` | `ui`

**Comment by GabLotus** [comment]
I agree with you this is definitely a bug thanks for letting us know :) If anyone is reading this can you confirm the bug repros on other platforms too 😊

**Comment by TheNeikos** [comment]
I'm on Archlinux , here's the same texts:

"Text Example"
![image](https://user-images.githubusercontent.com/1631166/91872398-592b0680-ec67-11ea-95b7-c7803b624cbf.png)

"Text Example -- notice anything?"
![image](https://user-images.githubusercontent.com/1631166/91872514-7a8bf280-ec67-11ea-99fb-f16979eeb64c.png)

"Text Example -- notice anything? Even more text 1234567890"
![image](https://user-images.githubusercontent.com/1631166/91872636-968f9400-ec67-11ea-9484-b478986e2aa6.png)

Same issue here

**Comment by TheNeikos** [comment]
This happens due to how the flexbox engine interacts with fixed size elements:

- First a fixed size is computed here: https://github.com/bevyengine/bevy/blob/8106f770de2ae3c841651499e0637123d7ae6688/crates/bevy_ui/src/widget/text.rs#L40-L48
- This size is then used during layout here: https://github.com/bevyengine/bevy/blob/8106f770de2ae3c841651499e0637123d7ae6688/crates/bevy_ui/src/flex/mod.rs#L44-L68
- For example if we calculate a text with (w: 100px, h: 20px). The layout engine then says we only have 80px of actual width or we overflow. This is then handled in the  [measure closure](https://github.com/bevyengine/bevy/blob/8106f770de2ae3c841651499e0637123d7ae6688/crates/bevy_ui/src/flex/mod.rs#L47). Right now, we simply keep the aspect ratio which then reduces the height. In this case `20 * 80/100 = 16`. So, our `Node` now has a size of `(w: 80, h: 20px)`. __This is different to the calculated size!__
- When rendered, we simply divide the `node.size` by 2 to get the center and offset that with is transform. But then go on to draw with the original size: https://github.com/bevyengine/bevy/blob/8106f770de2ae3c841651499e0637123d7ae6688/crates/bevy_ui/src/widget/text.rs#L64-L81


This then results in the behavior we see now: A smaller height divided by two makes for an 'upwards' growing text, when in actuality it should be shrinking to fit the available width. 

I am not sure what the ideal solution is here. Either the text overflows, or it gets smaller and smaller. Another option is to have it break into a new line (if there is space?)

**Comment by CleanCut** [comment]
In my use-case I would like to wrap.  From my naive standpoint of never having had to implement a text layout system, it seems like wrap vs. shrink  vs. overflow should all be supported via some configurable option. I don't know how hard that is to do.

**Comment by mockersf** [comment]
I have this issue, my "fix" to have the expected placement is to set the `Style` component of the `TextComponents`, with the height equal to the font size:
```rust
TextComponents {
    style: Style {
        size: Size {
            height: Val::Px(40.),
            ..Default::default()
        },
        ..Default::default()
    },
    text: Text {
        value: "Text example",
        font,
        style: TextStyle {
            color: Color::WHITE,
            font_size: 40.,
        },
    },
    ..Default::default()
}
```
