### ISSUE TITLE
bevy_prototype_lyon become official integrated and boosted with shaders

### ISSUE THREAD

**Issue by pyweeker** [bevyengine/bevy#4013]
Hello, bevy_prototype_lyon is useful to draw shapes easily , but it is sad not to have shaders support with it.
Is it possible in future to get it integrated , and to give it tools to add shaders on shapes ?

**Comment by mockersf** [comment]
There is an RFC to have basic shapes in Bevy: https://github.com/bevyengine/rfcs/pull/12

But [`bevy_prototype_lyon`](https://github.com/Nilirad/bevy_prototype_lyon) can do a lot more than just shape. Using a shader on top of it should be possible, maybe open an issue on the plugin repo for that.

**Comment by pyweeker** [comment]
the author of bevy_prototype_lyon told it is not on the roadmap for the moment...

**Comment by james7132** [comment]
Since this issue has been opened, ve since added `bevy_gizmos` which provides immediate mode shape and wireframe mesh drawing for debug purposes. The other functionality not covered here that `bevy_prototype_lyon` supports is likely not something fully required by most Bevy apps, and can be added as a third party plugin fairly easily. This issue therefore isn't particularly actionable given the current state of both the core engine, and `bevy_prototype_lyon`.  If there's an further interest to upstream the crate into the core engine, we can reopen and rediscuss, but for now, I'm closing this as currently not planned.
