### ISSUE TITLE
Publish API Documentation for Master Branch

### ISSUE THREAD

**Issue by zicklag** [bevyengine/bevy#407]
I was just thinking that it would be useful to have the API documentation for the master branch published to GitHub pages somewhere.

I was going to explain to @lee-orr, a beginner Rustacean, what changes were going to need to happen for #397, but I noticed that some of the API that I was going to point to had not been released yet, which meant that I can't point to the documentation for it. I didn't end up needing it in that case, but it seems like it could be useful.

**Comment by CleanCut** [comment]
I suggest avoiding adding to the overhead of the project at this early stage.  There's a lot of things like this that are _nice_, but quickly add up to a lot of infrastructure complexity and maintenance.  Rather than serving up API docs for master, I think it would be more healthy to:
- Release very frequently, so there isn't much desire for referencing the master docs
- Show folks how to generate their own master docs locally (It could just be a sentence at the top of the API docs front page, for example)

**Comment by zicklag** [comment]
I'll buy that. :slightly_smiling_face: :+1:

**Comment by memoryruins** [comment]
That would be useful. I imagine something like `cargo doc --no-deps -p bevy` so that it doesn't include docs for all dependencies too (which is what I use locally).

**Comment by Moxinilian** [comment]
If the master doc are ever provided on the website, it is of utmost importance that search engines do not référence it. Amethyst had a ton of issue with people being misguided into the wrong documentation.
