### ISSUE TITLE
Redistribute contents of 2D and 3D examples crates

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy#4214]
As the engine has grown, the 2D and 3D folders have become fairly ambiguous catch-all categories.

For the most part, these examples belong in either a rendering folder, a "stress-testing" folder, or the transforms folder.

**Comment by cart** [comment]
I think 2d and 3d are useful as categories because they are almost always "distinct". A user is either building a 2d game or a 3d game. Is it really useful to put a "3d screen space ambient occlusion" example adjacent to a "sprite" example in a general purpose "rendering" folder? The intersection between those two features for a given project is "empty". Someone looking for a way to draw a sprite is probably more likely to search in a "2d" folder than a "rendering" folder.

**Comment by alice-i-cecile** [comment]
Yeah; this ties into some of the broader conversations I've had with @mockersf about "how do we organize and scale examples". Both organization methods can be useful, and we need a way to address organization of the growing list of examples without simply stopping adding them.

**Comment by mockersf** [comment]
I think we should just give up on examples organization / discoverability in the GitHub repo: https://github.com/bevyengine/bevy-website/issues/299

**Comment by alice-i-cecile** [comment]
Sounds good to me. We can do a better job of it there.
