### ISSUE TITLE
Drag and drop event doesn't occur on windows 10

### ISSUE THREAD

**Issue by Sheepyhead** [bevyengine/bevy#4412]
## Bevy version

Main, revision 28d0a400288862e344cd16baae0dfd04f358a806

## Operating system & version

Windows 10

## What you did
Ran drag_and_drop example

## What you expected to happen

The example is supposed to simply print the drag and drop event it has received

## What actually happened

Nothing. The drag and drop event seems to be broken on windows

## Additional information

This may be working on other platforms, it would be nice if someone could test linux and mac

**Comment by bjorn3** [comment]
As I understand it the issue is that the audio plugin enables multi threaded COM (probably to allow any thread to start sound and not just the main thread), while OLE drag and drop (which winit uses) mandates single threaded COM.

See https://github.com/bevyengine/bevy/issues/2096#issuecomment-833446118 and https://github.com/rust-windowing/winit/issues/1255

**Comment by Sheepyhead** [comment]
You're correct, this is the same issue. PR #3772 fixes this

**Comment by xiaohulu** [comment]
drag_and_drop example does not work on windows 11. When I drop a file to the bevy window, the console print nothing.
