### ISSUE TITLE
Changed/Added/Mutated queries not triggered depending on order of systems

### ISSUE THREAD

**Issue by mockersf** [bevyengine/bevy#442]
using branch master at [5f1fef3](https://github.com/bevyengine/bevy/commit/5f1fef333cfddde1d4dbbc223338f7ea0edc0875):

in the following example:
```rust
use bevy::prelude::*;

fn main() {
    App::build()
        .add_default_plugins()
        .add_startup_system(setup.system())
        .add_system(spawn_a.system())
        .add_system(check_for_changed.system())
        .add_system(change_a.system())
        .run();
}

#[derive(Debug)]
struct A(u32);

fn setup(mut commands: Commands) {
    commands.spawn((A(0),));
}

fn spawn_a(mut commands: Commands) {
    let new_a = A(1);
    println!("spawning {:?}", new_a);
    commands.spawn((new_a,));
}

fn change_a(mut a: Mut<A>) {
    println!("changing {:?}", *a);
    a.0 = a.0 + 1;
}

fn check_for_changed(a: Changed<A>) {
    println!("changed {:?}", *a);
}
```

The `check_for_changed` system is only called for the component spawned in the startup system.

This was not what I expected since [the documentation for ` Changed`](https://github.com/bevyengine/bevy/blob/25f62f7250a0d750068dc32533b9433f7985af98/crates/bevy_ecs/hecs/src/query.rs#L457) states that 
> Query transformer skipping entities that have not been either mutated or added since the last pass of the system

From the following workarounds, it seems to depend on the order of execution of the systems. The state of entities seems to be reseted near the end, and spawning does not happen when the system is executed but later.

Should the documentation be updated to specify that it only concerns changes in the current loop run, or can the `Changed` query actually keep track of changed since the last execution of the system where it's used?

### workarounds

```rust
fn main() {
    App::build()
        .add_default_plugins()
        .add_startup_system(setup.system())
        .add_system(spawn_a.system())
        .add_system(change_a.system())
        .add_system(check_for_changed.system())
        .run();
}
```
If I change the order of my systems so that `check_for_changed` is after `change_a`, it will be triggered for changes but not for spawns.

```rust
fn main() {
    App::build()
        .add_default_plugins()
        .add_startup_system(setup.system())
        .add_system(spawn_a.system())
        .add_system_to_stage(bevy::app::stage::POST_UPDATE, check_for_changed.system())
        .add_system(change_a.system())
        .run();
}
```
If I put the system in the stage `bevy::app::stage::POST_UPDATE`, it now catches both spawning and changes.

**Comment by thlorenz** [comment]
I'm running into related issues while playing with bevy.
I described it in detail in a comment [here](https://github.com/thlorenz/bevy-gl/blob/master/src/camera/camera_info.rs#L30-L62).

**Comment by cart** [comment]
This is expected behavior. The current change detection system is _very_ cheap, which is why we can enable it by default. But it comes at the cost that changes are only detected in "downstream" systems and they are reset at the end of each update.

#68 outlines the issue and links to some additional thoughts on it. the only "fix" for this is to maintain per-system change state across frames, but this would require additional allocations and would significantly increase the cost of change detection. Its worth considering adding "opt in" cross frame change detection, but I dont think we can justify the cost of making it the default.

Unfortunately the docs are slightly incorrect (as you pointed out).  We should fix those (which ill consider the close-criteria for this issue).
