### ISSUE TITLE
3D Alpha rendering  bug

### ISSUE THREAD

**Issue by Niedzwiedzw** [bevyengine/bevy#4501]
## Bevy version
0.7

## Operating system & version
Linux niedzwiedz-pc 5.15.28-1-MANJARO #1 SMP PREEMPT Fri Mar 11 14:12:57 UTC 2022 x86_64 GNU/Linux

## What you did
https://github.com/Niedzwiedzw/bevy-alpha-rendering-bug-showcase

## What you expected to happen

boxes shouldn't change the way they're overlapping based on camera position

## What actually happened
https://github.com/Niedzwiedzw/bevy-alpha-rendering-bug-showcase

## Additional information
![Peek 2022-04-16 23-31](https://user-images.githubusercontent.com/22037927/163692063-09ee0368-8a5f-4194-a7b8-4e97bdb4e3d2.gif)

**Comment by superdump** [comment]
You’re setting something that is using an opaque colour as transparent by setting AlphaMode::Blend. Transparent objects are rendered back to front ordered based on the model’s origin in view space. What you show in the clip is expected behaviour. Don’t mark opaque objects as transparent. Or actually use a transparent material on a transparent object and then there are known limitations to the current approach to transparency and an order-independent transparency method may help with that but there is not one implemented yet in bevy.

**Comment by superdump** [comment]
See here for more details of the limitations of transparent rendering as it is: https://github.com/bevyengine/bevy/issues/2223

**Comment by Niedzwiedzw** [comment]
ok that makes sense - I have managed to fix it in my - more complex case - where I noticed the problem by setting AlphaMode::Mask(0.5).

https://user-images.githubusercontent.com/22037927/163709426-cf449d30-cbb8-486c-b553-da52ba4ac1ec.mp4
