### ISSUE TITLE
Support !Send + !Sync Resources

### ISSUE THREAD

**Issue by farnoy** [bevyengine/bevy#456]
Hi,

I have a type that's neither `Send` nor `Sync` and I can't find a way to use this data as part of the `Schedule`. `Resources`, `System` and `IntoThreadLocalSystem` all have requirements on `Send + Sync`. Would it be possible to relax this?

**Comment by cart** [comment]
Supporting `!Send + !Sync` resources is definitely a common enough requirement that we should support it. We've already had folks hit this in a number of places and working around it results in ugly and/or unsafe/incorrect code.

**Comment by Waridley** [comment]
Could this also apply to Components? E.g. I have a component that's `Send` but `!Sync`, but I only access it in one system, so wrapping it in a `Mutex` is pointless. However, I don't know if there's any way to *enforce* in the AppBuilder that I'm only using it in one system when it's `!Sync`.

**Comment by Waridley** [comment]
Also, this will come up for web support, because `WinitWindows` are `!Send + !Sync` on WASM.

**Comment by kakoeimon** [comment]
Where is the problem with Mutex or RWLock?
About components keep in mind that send and sync are requirements of hecs.

**Comment by cart** [comment]
`Mutex<T>` and `RWLock<T>` both require T to be Send. Additionally, some resource/component types might only work correctly when they have been accessed from the main thread. i think we should try to honor the Send/Sync semantics, otherwise we might encounter undefined behavior.

Adding !Send + !Sync resources should be relatively straightforward. Supporting !Send + !Sync components will be a bit harder, but I'm 100% ok with modifying hecs to support this.

**Comment by Waridley** [comment]
I suppose wrapping a `Send + !Sync` component in a `Mutex` is *probably* not a big deal if I'm only using it in one system, since the lock should basically always succeed, costing only a couple atomic operations... Still a slight waste, but the bigger issue is probably `!Send` resources.

**Comment by kakoeimon** [comment]
I don't think this is a requirement. I mean you can use send + sync in wasm as long you do not create any threads.
For example I have used hecs with Mutex for wasm.

**Comment by smokku** [comment]
Faking it does work in a single threaded wasm runtime: https://github.com/bevyengine/bevy/blob/34c6f5f41bd2bff7867e269985a54036b8d96771/crates/bevy_winit/src/winit_windows.rs#L109

**Comment by chemicstry** [comment]
Supporting threads in wasm is a hard requirement IMO. This can work for the time being, but I'm sure other use cases for `!Send` will pop up.

I would also caution against bare `unsafe impl Send` and at least use a wrapper type which checks thread id before accessing like the one Amethyst [uses](https://github.com/amethyst/amethyst/blob/wasm/amethyst_core/src/ss.rs). That way you at least get a panic instead of undefined behavior.

**Comment by Waridley** [comment]
Yeah, the godot-rust bindings do something similar with `LocalCellData` which panics if the thread ID is not the same
