### ISSUE TITLE
Consider moving from parking_lot back to std locks

### ISSUE THREAD

**Issue by bjorn3** [bevyengine/bevy#4610]
## What problem does this solve or what need does it fill?

In the past the locks in libstd were wrappers around the OS native locks like provided by pthreads. Depending on the use case the locks of parking_lot are faster. For this reason we currently use parking_lot instead. As part of the work tracked in https://github.com/rust-lang/rust/issues/93740 libstd is currently replacing OS native locks with custom implementations. The linux implementation is slightly slower than parking_lot when there is no contention, but it is faster than both parking_lot and the pthreads implementation of glibc and musl under light to extreme contention on at least two benchmarks (https://github.com/Amanieu/parking_lot/issues/338#issuecomment-1109971426 and https://github.com/rust-lang/rust/pull/95035#issuecomment-1073966631).

## What solution would you like?

We should benchmark the new locking implementation of libstd for the purposes of bevy and switch to them if they don't regress performance. Even if they don't improve 

## What alternative(s) have you considered?

Wait until https://github.com/rust-lang/rust/issues/93740 is fully done.

**Comment by Elabajaba** [comment]
A reason why we might want to stick with parking_lot is its [deadlock detection.](https://amanieu.github.io/parking_lot/parking_lot/deadlock/index.html)

Another option might be using the debug variants of [tracing-mutex](https://github.com/bertptrs/tracing-mutex), which creates a DAG and ensures that there aren't any lock cycles (and the debug variants only do that for debug builds, but otherwise use the underlying std/parking_lot/etc primitives).
