### ISSUE TITLE
Bevy is not reading all gltf extra properties

### ISSUE THREAD

**Issue by luke-biel** [bevyengine/bevy#4823]
## Bevy version

0.7.0

## Operating system & version

EndeavourOS `VERSION=2021.08.27` with kernel v. `5.17.9-arch1-1`

## What you did

I've added a custom property to an object in blender, exported it as gltf, tried to load scene in bevy and access the property via GltfExtras.

## What you expected to happen

My system:
```
fn print_extras(q: Query<&GltfExtras>) {
    for extra in q.iter() {
        println!("{:?}", extra);
    }
}
```
would be able to find and print data attached to my object.

## What actually happened

GltfExtras component wasn't created on load.

## Additional information

Blender has created json entry:
```json
    "meshes" : [
        {
            "extras" : {
                "AttachedSensor" : "abc"
            },
            "name" : "Cube",
            "primitives" : [
                {
                    "attributes" : {
                        "POSITION" : 0,
                        "NORMAL" : 1,
                        "TEXCOORD_0" : 2
                    },
                    "indices" : 3,
                    "material" : 0
                }
            ]
        }
    ],
```
after some digging in source code I've realized that bevy reads only extras from within primitives, so change to:
```json
    "meshes" : [
        {
            "name" : "Cube",
            "primitives" : [
                {
                    "attributes" : {
                        "POSITION" : 0,
                        "NORMAL" : 1,
                        "TEXCOORD_0" : 2
                    },
                    "indices" : 3,
                    "material" : 0,
                    "extras" : {
                        "AttachedSensor" : "abc"
                    }
                }
            ]
        }
    ],
```
resulted in system printing out the data:
```
GltfExtras { value: "{\n                        \"AttachedSensor\" : \"abc\"\n                    }" }
GltfExtras { value: "{\n                        \"AttachedSensor\" : \"abc\"\n                    }" }
GltfExtras { value: "{\n                        \"AttachedSensor\" : \"abc\"\n                    }" }
```

---
Should I change the way I attach custom properties in blender or is it something that should be changed in bevy?

How I add custom property:
![Blender](https://user-images.githubusercontent.com/15006215/169694239-d952eefc-def8-4924-a0e4-14b847f1e11a.png)

Blender export settings:
![Export settings](https://user-images.githubusercontent.com/15006215/169694171-f9abb1f8-0a0c-44c1-8d22-012b1e00502b.png)

**Comment by Frizi** [comment]
Blender doesn't really have a concept of primitives. Instead, it allows assigning multiple materials to different parts of meshes. The gltf exporter slices the mesh into individual parts, but it doesn't gather any extra attributes there. Effectively, [the extras field on primitives is always empty](https://github.com/KhronosGroup/glTF-Blender-IO/blob/84b42b4b17710107095d335166364e3f85a6482f/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_primitives.py#L101).

That means, Bevy should really read the extras from the mesh node, as it's the only thing that blender can work with. But it's not clear where to put those extras.

In my opinion, the extras from `mesh` node should be applied to each mesh entity, as an individual copy. Most of the time it will be only a single primitive anyway, unless you use multiple materials per mesh. For other cases, it's better to have those copied than to exist only on some of the meshes.

For now, the next best thing is to put the custom properties on the parent node (`Cube` node directly in `Collection`). It will be created on the parent entity of the meshes. You can then work from there in your system logic and query the child meshes.

**Comment by OriginLive** [comment]
Hi, how do you add your property? I see the same extra info if i click on the cube or it's mesh. I can't read it either

**Comment by DreamplaySE** [comment]
> That means, Bevy should really read the extras from the mesh node, as it's the only thing that blender can work with. But it's not clear where to put those extras.
> 
> In my opinion, the extras from `mesh` node should be applied to each mesh entity, as an individual copy. Most of the time it will be only a single primitive anyway, unless you use multiple materials per mesh. For other cases, it's better to have those copied than to exist only on some of the meshes.

Reviving this issue since I recently stumbled upon this problem while trying to use blender as a level-editor. The issue with applying them to the primitives is that primitives themselves are obviously also able to have extras on them. Not pasting over them/primitives pasting over mesh is in my opinion a necessity, and merging doesn't seem like an option. A solution is to create a second component to store the mesh-extras on. This would be useful as well since you could query for it separately, but obviously it would be adding of another component which one might like to avoid. The question then also becomes if it's best if the mesh-extras should be on the primitive entities, or rather the GLTF node-entity that links to the mesh. I personally feel the second is more appropriate since multiple cloned instances seems clunky.

I haven't contributed to bevy before, but I'd like to help sort this out if I could get some help on a direction to take this.

**Comment by nicopap** [comment]
I've encountered this limitation in #8158 and solved it by defining a `GltfMeshExtras`. It seems reasonable to extend this to all other properties.

Alternatives:

- Merge the json of each extras into a single `GltfExtras`. Bad and innelegant, because it requires reading the extras, adding
- Have a bunch of specialized `Gltf*Extras` types like `GltfMeshExtras`, `GltfPrimitiveExtra` etc.
- Have an `GltfExtras { pub types: EnumMap<NodeType, String> }` (or maybe `Option<String>` fields)

What do people think? I think it's a major limitation of the current bevy gltf importer, since it prevents using the standard-defining way of extending the file format.

**Comment by DreamplaySE** [comment]
> I've encountered this limitation in #8158 and solved it by defining a `GltfMeshExtras`. It seems reasonable to extend this to all other properties.
> 
> Alternatives:
> 
>     * Merge the json of each extras into a single `GltfExtras`. Bad and inelegant, because it requires parsing the string as json, build a different json object and re-serialize it.
> 
>     * Have a bunch of specialized `Gltf*Extras` types like `GltfMeshExtras`, `GltfPrimitiveExtra` etc.
>       
>       * You could also have a generic value and define it this way: `GltfExtras<T: ExtrasTarget> { pub data: String, pub(crate) _type: PhantomData<T> }`.
> 
>     * Have an `GltfExtras { pub types: EnumMap<NodeType, String> }` (or maybe `Option<String>` fields)
> 
> 
> What do people think? I think it's a major limitation of the current bevy gltf importer, since it prevents using the standard-defined way of extending the file format.
> 
> @DreamplaySE I'd be glad to help you. I think having multiple independent components is the best option. You can take a look at he following as a starting point on how to do it. https://github.com/nicopap/bevy/blob/a0d37d20ff79fd55a982de50f6748627dac30954/crates/bevy_gltf/src/loader.rs#L784-L793

Funnily enough, I actually already did it (created GLTFMeshExtras and GLTFMaterialExteas) but didn't have time to update the issue. I have been using it to test as a patch in my game and it's worked well, especially with a connected system that automatically deserializes it to a serde type of choice. I think integrating deserialization would be ideal.

I still don't like how it forces duplication of data though, but maybe it's the best way. If it's done, your generic way seems like the most cute option.

**Comment by nicopap** [comment]
Replacing `String` by [`Cow<'static, str>`](https://doc.rust-lang.org/stable/std/borrow/enum.Cow.html) or `Arc<str>` might help avoid needless allocation. After all, those are not for writing at all. Cart has (rightfully) been voicing concern over the amount of allocation gltf loading does, replacing `String` by a smart pointer would help reduce allocation cost to the minimum necessary.

**Comment by nicopap** [comment]
@DreamplaySE Any progress on a potential PR? It is now blocking for #8158

**Comment by DreamplaySE** [comment]
Hey sorry I've been busy with work but I should have it posted within the next few days/beginning of next week.

**Comment by nicopap** [comment]
Yeah also it's not blocking anymore, don't worry about it. I'm sorry for bothering you :sweat_smile:

**Comment by kaosat-dev** [comment]
has anybody done some more work on this ?
If not I would try and implement this using @nicopap 's solution.
I thought I could get around this, but turns out it is blocking for a few of the things I want to add for the blender_gltf_workflow tools :D 

The "types" of GltfExtras I would add are:
* GltfMeshExtras
* GltfPrimitiveExtras
* GltfMaterialExtras
* GltfSceneExtras
