### ISSUE TITLE
Parallelize the core pipeline passes with wgpu's RenderBundles

### ISSUE THREAD

**Issue by james7132** [bevyengine/bevy#5042]
## What problem does this solve or what need does it fill?
The single threaded nature and random-access in the render phase exclusive system can be a heavy bottleneck for both rendering and the game engine as a whole, particularly with more complex or involved scenes. Even with pipelined rendering enabled, single-threading the render phase can easily bottleneck heavier games.

## What solution would you like?
`wgpu` supports the concept of replayable command buffers in the form of [`RenderBundle`](https://docs.rs/wgpu/latest/wgpu/struct.RenderBundleEncoder.html). This supports writing to an intermediate secondary command buffer that can then be replayed on an actual `RenderPass`.

This initial design calls for having a parallel component to `RenderPhaseI<I>` called `RenderPhaseBundle<I>` which wraps a `Option<RenderBundle>`. This bundle will be generated by a non-exclusive read-only system that runs before the render graph is executed. Each of these systems, being read-only, can run in parallel, allowing each phase and view to encode commands in parallel. These `RenderBundles` can then be collected en masse when executing the `RenderGraph` and dispatched via `RenderPass::execute_bundles` after merging and sorting the lists of bundles.

A followup to use `ThreadLocal` to create thread-local queues of `RenderBundles` can be used alongside `bevy_tasks`'s parallel iterators to further chunk up large rendering tasks into smaller chunks. These chunks need to be annotated with the start index within the phase , and sorted after collection before applying to ensure the commands are applied in the correct order.

As of writing ,replaying bundles scales linearly with the number of recorded commands, but these should be reduced to a small constant time in the future.

## What alternative(s) have you considered?
Batching and instancing both can be used in particular cases to speed up the render phase, but are both situational depending on the scene's layout and requires deeper pipeline and data representation changes. Even with batching and/or instancing, allowing different phases to run in parallel will likely still be a win, particularly in large mixed scenes.

Fully bindless rendering is also an option, but is currently platform limited.

**Comment by JMS55** [comment]
I want to note that this issue is about reducing the _CPU_ time spent recording rendering commands for the GPU to execute, by parallelizing it where possible. 

---

The design this issue proposes is to use a render bundle per phase item, and produce the total list of render bundles for the phase in parallel. That's part of the solution, but not all of it.

(1) Wgpu RenderPasses with many draw commands (prepass, main pass, maybe the shadow map pass) are expensive to record themselves, and we would like to parallelize the draw command recording within these passes. This is what this issue proposes to solve.

(1.1) 1 render bundle per draw command per frame is inefficient, though. Ideally we batch together multiple draw calls (meshes) within each render bundle, and reuse unchanging/static render bundles across frames. Similarly, 1 render bundle per phase item is not ideal. It would be better to have a threadpool building a smaller set of render bundles, with 1 per thread.

(2) Using one command encoder/buffer for all nodes and executing the nodes in serial is inefficient. Instead, we should use 1 command encoder / buffer per node, and run the nodes in parallel. We can then take the command buffers produced by the nodes and submit them once at the end.

(2.1) Except generating 1 command buffer per node is inefficient when it comes to executing on the GPU. Nodes that are simple and light on GPU-work should probably share a command encoder/buffer with another pass.

(2.2) Submitting all the finished command buffers at the end is also inefficient. We have the opportunity to increase the overall FPS by submitting some GPU work early, and letting the GPU process it overlapping with the CPU then recording more commands for the next task. 

---

A sample trace on an 8-core CPU might look like this (profiling obviously needed):
* CPU records shadow map passes using 
  * 1 command encoder for the overall node
  * X render passes for the X different lights and cascades
  * 8 threads in a threadpool, where for each render pass, you divide the overall draw calls into batches of 8, and record 1 RenderBundle per thread each processing a batch of draw calls
* Submit shadow map command buffer to the GPU, GPU starts computing the shadow pass
* CPU records prepass using
  * 1 command encoder for the overall node
  * 1 render pass
  * 8 threads in a threadpool, where you divide the overall draw calls into batches of 8, and record 1 RenderBundle per thread each processing a batch of draw calls
* ...
* CPU records TAA, bloom, tonemapping, etc into one command buffer and submits

---

The elephant in the room is that (1) is entirely working around the fact that recording many draw calls and render passes is expensive on the CPU. Moving culling to the GPU using compute shaders, using multi draw indirect, using binding arrays to reduce bind group counts (bindless) and batching draws, etc greatly reduces the CPU cost in the first place, which may render (1) unnecessary, leaving us with just (2): overlapping CPU and GPU rendering work with multiple command buffers and queue submission. However, some of these features are not available on all GPUs, and WASM/WebGPU have other considerations as well.

**Comment by JMS55** [comment]
We've since implemented batching and instancing, and soon multithreading command encoding https://github.com/bevyengine/bevy/pull/9172. Not sure if render bundles are worth it at this point.

**Comment by james7132** [comment]
Agreed that the recent batching changes and the sorting changes that maximize the impact of batching have sort of made going for this approach for parallelization potentially moot.

We may want to look into ways of batching and preparing in parallel instead, as that's where the majority of the cost has shifted.
