### ISSUE TITLE
Maybe add separate feature that disables some soundness checks for performance?

### ISSUE THREAD

**Issue by SUPERCILEX** [bevyengine/bevy#5207]
## What problem does this solve or what need does it fill?

Go vroom.

## What solution would you like?

In https://github.com/bevyengine/bevy/pull/5121, I saw some discussion about disabling the checks in release mode. For games, I think there are actually 3 different tracks: debug, release, public release. Release builds can be sent to QA, but you still want them to crash if things go wrong. However, you want your public release builds to be as fast as possible and never crash. Creating a feature designed to remove some costly soundness checks gives you that flexibility.

**Comment by Nilirad** [comment]
I think that in many cases the gains are so marginal that are not worth the work to implement and test that feature, and the risk of hidden bugs.

**Comment by james7132** [comment]
This is already sort of done. ECS code definitely has a large number of `#[cfg(debug_assertions)]` that have additional sanity and safety checks that are not enabled in release mode. In actual release mode, almost all of these code paths have zero checks. If you make a build that optimizes, but enables debug assertions on these crates, it'll retain the safety checks, but enable higher levels of optimizations. One of the common options of enabling dependency-only optimizations likely already satisfies the requirements for a split between release and public release.

**Comment by james7132** [comment]
We already omit soundness checks and push a lot of the responsibility onto the caller on all low level ECS code. There's a few remaining unwraps that could be removed but already have been replaced with a debug mode checked version in some PRs (i.e. #4800). For the most part, any sanity check we could omit in release builds has already been removed. So unless you're proposing exposing more of the unsafe internals in userspace code, we already are doing this.

For example, Query iteration does bounds checking as it would be unsound not to. We cannot omit it there. Using Query::get is in a similar spot as omitting the checks would likely result in UB. If you *know* you can enforce the invariants of Query::get_unchecked, feel free to use the unsafe option, but you need to be sure that those invariants hold.

Overall, I don't think this issue is actionable. We're already stripping out every possible check we can already.

**Comment by SUPERCILEX** [comment]
Oh, I forgot about the unchecked query API. Makes sense!
