### ISSUE TITLE
`headless_defaults` example displays an empty window

### ISSUE THREAD

**Issue by LegNeato** [bevyengine/bevy#5260]
## Bevy version

[518408dfdaa8884ba86a71512de2a7d57848413d
](https://github.com/bevyengine/bevy/commit/518408dfdaa8884ba86a71512de2a7d57848413d)

## What you did

Run `cargo run --example headless_defaults`

## What went wrong

It isn't headless...a window is displayed:
<img width="1392" alt="Screen Shot 2022-07-09 at 1 32 30 PM" src="https://user-images.githubusercontent.com/368904/178116705-8d74af17-195d-43f9-97a2-0066eb504722.png">

I expected no window to be displayed.

**Comment by DJMcNab** [comment]
The examples readme says that the example is:

> An application that runs with default plugins, but without an actual renderer.

The purpose of the example is to test that everything works if no wgpu backends are set, which is required because 

This issue and the other comment (https://github.com/bevyengine/bevy/issues/3155#issuecomment-1133596519) suggests that people are struggling to understand this example, so it could probably do with a rename - maybe `no_renderer`? 
As far as I can tell, there was no discussion of this in #3439 - @Shatur do you have any thoughts on the name?

**Comment by Shatur** [comment]
> so it could probably do with a rename - maybe no_renderer

Yes, it makes more sense. And I think we also should note in the example description that the window will be present.

**Comment by LegNeato** [comment]
Cool, will do.
