### ISSUE TITLE
Support `Option<EventReader>` and `Option<EventWriter>` as system parameters

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy#5302]
## What problem does this solve or what need does it fill?

These types are much more ergonomic (and harder to mess up) than the raw `Events` resource.
This is particularly true for `EventReader`, as it stores an internal cursor.

When working with event streams that may or may not exist, it would be very convenient to be able to request this data if and only if it exists.

## What solution would you like?

Implement `SystemParam` for these types, following the implementation for `Option<Res>`.

## What alternative(s) have you considered?

Users can workaround this by using a `ManualEventReader`.

**Comment by JoJoJet** [comment]
I would like to claim this issue.

**Comment by GarettCooper** [comment]
Oops, sorry @JoJoJet. I should have claimed it.

**Comment by JoJoJet** [comment]
@GarettCooper no worries, I didn't start working on it.

**Comment by mockersf** [comment]
> These types are much more ergonomic (and harder to mess up) than the raw `Events` resource. This is particularly true for `EventReader`, as it stores an internal cursor.

Could you expand on that? The second sentence in particular is very nebulous to me.

> When working with event streams that may or may not exist, it would be very convenient to be able to request this data if and only if it exists.

While it's possible to add new event types during runtime, it doesn't make a lot of sense to do so, and all helpers / doc on it adds events at app creation. When do you have to work with event streams that may or may not exist?

I think it's better to just crash when the user forgot to register the events rather than force them to handle an option

**Comment by alice-i-cecile** [comment]
> Could you expand on that? The second sentence in particular is very nebulous to me in how it would relate to an option.

Working with `Res<Events<T>>` is frustrating, as you must manually track how many events you have read in that system. `EventReader` is the intended design to get around this, but does not support event streams that may or may not exist (see below). 

> While it's possible to add new event types during runtime, it doesn't make a lot of sense to do so, and all helpers / doc on it adds events at app creation. When do you have to work with event streams that may or may not exist?

This is for library code, in particular, for `leafwing_input_manager`. I want to be robust to platforms that do not support all input event types. As a result, all of the input streams are option-ified. This worked great for resources like `Input`, but when I needed to add an `Events` equivalent I ran into trouble.

I suspect that this pattern will be relatively common when trying to make library code robust to unusual setups, but very rare in  end user apps.

> I think it's better to just crash when the user forgot to register the events rather than have them handle an option

In general I agree with this, but not for library code. There are genuine cases where the event stream *cannot* meaningfully exist (what does the `MouseWheel` event mean on Nintendo Switch?), and I'd really like to avoid forcing users to create dummy event streams to get their libraries to stop crashing.

**Comment by mockersf** [comment]
> In general I agree with this, but not for library code. There are genuine cases where the event stream _cannot_ meaningfully exist (what does the `MouseWheel` event mean on Nintendo Switch?), and I'd really like to avoid forcing users to create dummy event streams to get their libraries to stop crashing.

A bluetooth mouse works on the Nintendo Switch, so `MouseWheel` should mean the same than every where else.

If there are platforms where some input events don't exists, I don't think handling them with options is the right way, it would be best to use compilation checks on target / platform. But Bevy currently doesn't do that, and add them all no matter the platform. with most modern platform anyway, you can connect any input device to the platform

> This is for library code, in particular, for `leafwing_input_manager`. I want to be robust to platforms that do not support all input event types.

So it's better to not have them as options then, because all platforms should support all input event types
