### ISSUE TITLE
Children are invisible unless parent has Visibility and ComputedInvisibility

### ISSUE THREAD

**Issue by rparrett** [bevyengine/bevy#5334]
## Bevy version

main, also
c8aa047ccae81c2dd24f5847824854f5466a5813 (commit prior to #5310)

## What you did

```rust
use bevy::prelude::*;

fn main() {
    App::new()
        .add_plugins(DefaultPlugins)
        .add_startup_system(setup)
        .run();
}

fn setup(mut commands: Commands, asset_server: Res<AssetServer>) {
    commands.spawn_bundle(Camera2dBundle::default());
    commands
        .spawn_bundle(TransformBundle::default())
        // .insert(ComputedVisibility::default())
        // .insert(Visibility::default())
        .with_children(|parent| {
            parent.spawn_bundle(SpriteBundle {
                texture: asset_server.load("branding/icon.png"),
                ..default()
            });
        });
}
```

## What went wrong

Prior to #5310, the above code worked as-is and displayed the bevy logo.

After #5310, the logo is not displayed unless the two commented-out lines are uncommented.

## Additional information

If this is expected behavior, we should mention that in the migration guide and close this.

This may have implications for other bits of documentation / examples.

**Comment by rparrett** [comment]
Indeed, it seems that `many_foxes` and perhaps other examples are broken due to this.

**Comment by cart** [comment]
I think for now this is expected behavior. We only propagate visibility down hierarchies that have visibility/computedvisibility chains. The Transform system has the same behavior. The naive solution to the problem (walk the whole unfiltered entity tree and check each one for visibility component existence) doesn't feel particularly good to me, as checking each entity in World would be pretty expensive for very large worlds. 

Maybe we add a convenience VisibilityBundle to help make it easy to build these chains.

We could also consider adding some sort of VisibilityRoot / TransformRoot marker to cheaply identify arbitrarily nested things with inheritance behaviors. But that also requires manual action and increases complexity of the system.

Short term, I think we should fix the examples, update the migration guide to call out this case, and add a VisibilityBundle.
