### ISSUE TITLE
`SystemLabel` proc-macro no longer allows for generic enums

### ISSUE THREAD

**Issue by SarthakSingh31** [bevyengine/bevy#5362]
## Bevy version

Since  c43295af80bb3a7e9b455500d76d13454a037ca0

## The Problem

I was trying to update `bevy_mod_raycast` to bevy main but ran into a problem with this

https://github.com/bevyengine/bevy/pull/4957/files#diff-b131f1941aa2edc166d44e3411ad3e04c125bd541288357846e6c2e018b46b80R133-R142

change to the `SystemLabel` proc-macro.

https://github.com/aevyrie/bevy_mod_raycast/blob/0a5d1e3334285eaf85e97adc28b14cbb50ab1b48/src/lib.rs#L82-L89

needs a variant with a data field to store the `PhantomData` but this change makes that impossible.

## Possible solutions

1. Make the `SystemLabel` proc-macro detect if the variant is unreachable by insuring that it has a field with type `::std::convert::Infallible`.
2. Add a `ignore` attribute to the `SystemLabel` proc-macro.

**Comment by alice-i-cecile** [comment]
Broken by #4957. @JoJoJet, any opinions?

**Comment by JoJoJet** [comment]
I don't want to magically change behavior based on types since that can be potentially surprising. Instead I think the simplest solution is to just allow 
```
#[derive(Label)]
enum MyEnum {
    One,
    #[label(ignore_data)]
    Two(/* Any data, potentially non-phantom */),
}
```

This would simply tell the derive macro to ignore the fields of that variant when comparing labels. Thought I suspect this may have implications for equality which I'll look into more.
