### ISSUE TITLE
Dev docs are undiscoverable

### ISSUE THREAD

**Issue by djeedai** [bevyengine/bevy#5390]
## How can Bevy's documentation be improved?

Dev docs are very difficult to find, and probably unknown from most devs.

- I discovered their existence randomly browsing the [Bevy 0.7 release notes](https://bevyengine.org/news/bevy-0-7/#dev-docs)
- I can never remember the link, and that blog post is the only place where I know the link exists
- It's not even prominent in that blog post, it's way down after many other things

I'm not sure what can be done here, if a link from the main website or a link from docs.rs would be useful, but as is their value is quite low.

**Comment by Nilirad** [comment]
This is probably a side effect of not wanting them to be indexed by search engines.

**Comment by CGMossa** [comment]
Link to [dev-docs](http://dev-docs.bevyengine.org/) just for people coming into this issue.

**Comment by james7132** [comment]
As mentioned by @Nilirad, this is partially intentional. We didn't want new users to accidentally stumble onto them and get frustrated when the book and publicly released version of the engine doesn't match the docs. 

I'd actually suggest against putting a link in the README, and instead in the CONTRIBUTING file instead, even if the latter is harder to find and currently pretty lengthy already. The core audience of the dev docs are either Bevy contributors or ecosystem crate devs looking to update their crates near a release.

**Comment by djeedai** [comment]
The core audience is currently nobody; it took me several months and some luck to discover those.
