### ISSUE TITLE
Broken doc link in `bevy_reflect`

### ISSUE THREAD

**Issue by nicopap** [bevyengine/bevy#5536]
## How can Bevy's documentation be improved?

The link to `bevy_utils::get_short_name` in "short name" in the description of the `short_name` method is broken:
- https://docs.rs/bevy/latest/bevy/reflect/struct.TypeRegistration.html#method.short_name

The link seems to refer to `bevy::reflect::bevy_utils::get_short_name` instead of the top level crate.

**Comment by hintron** [comment]
I think this is a dup of bug #3654. See https://github.com/bevyengine/bevy/issues/4511#issuecomment-1261661298.

This is an inter-crate doc link (bevy_reflect --> bevy_utils), and rustdoc seems to not be able to handle that. It thinks it's a local link, producing <https://docs.rs/bevy/latest/bevy/reflect/bevy_utils::get_short_name> instead of <https://docs.rs/bevy/latest/bevy/utils/fn.get_short_name.html>. There are many other examples of this all throughout the docs. I have yet to find an inter-doc link that works (but maybe there are some).

**Comment by nicopap** [comment]
You are right. lol. Seems like I was a bit inattentive. Anyway, I just took a look at the dev bevy doc (https://dev-docs.bevyengine.org/bevy/utils/fn.get_short_name.html) and it looks like the doc link doesn't exist anymore.

**Comment by nicopap** [comment]
Nope, can reproduce with a local doc `cargo doc --open`, (btw, please use local doc over web doc, this fixes the issue you are mentioning) the issue here is to do with something else.

**Comment by nicopap** [comment]
Seems to be indeed a duplicate
