### ISSUE TITLE
16-bit PNG displays incorrectly

### ISSUE THREAD

**Issue by emosenkis** [bevyengine/bevy#554]
I used code copied from the example [`texture_atlas.rs`](https://github.com/bevyengine/bevy/blob/ad7613c67485ad468d33f1b68452c076b70db826/examples/2d/texture_atlas.rs) and the source image is [here](https://github.com/emosenkis/budge/blob/d9ce02c83faee72ebd7f69711b2d63e6b6874b31/lib/bitmaps/heart.png) - I then edited it with Gimp by changing the mode to RGB and the depth to 16- or 32-bit. This is how it displayed:
![image](https://user-images.githubusercontent.com/1794126/93916775-b2400480-fd12-11ea-9183-13dbca57917b.png)

**Comment by GuiAmPm** [comment]
This is probably due to an how the format is dealt with on the method `copy_texture` on texture_atlas_builder:
https://github.com/bevyengine/bevy/blob/b8f8d468db4f17896d63772816e3a21a22cf682e/crates/bevy_sprite/src/texture_atlas_builder.rs#L76

The format used is the atlas' and assumes that the source texture has the same format.
Here especially:
```
let texture_begin = texture_y * rect_width * format_size;
let texture_end = texture_begin + rect_width * format_size;
```

Maybe the source image should be converted to the same format as the atlas?

**Comment by GuiAmPm** [comment]
The problem as originally described seems to be fixed.

**Comment by ebiggs** [comment]
I tried using a png with a color depth of 16 bits and rather than display it incorrectly the app crashed and displayed this message:

texture binding 1 expects sample type = Float { filterable: true }, but given a view with format = Rgba16Uint

**Comment by targrub** [comment]
I get "`ERROR bevy_sprite::texture_atlas_builder: Error converting texture from 'Rgba16Uint' to 'Rgba8UnormSrgb', ignoring`" when running the `texture_atlas` example on the texture from @ebiggs.  Close this now?

**Comment by nicopap** [comment]
yep. This can be closed. I mean, we still panic on 16 bits precision PNGs, but it's a different kind of issues.
