### ISSUE TITLE
Unnecessary &mut in Query.iter

### ISSUE THREAD

**Issue by OriolMunoz** [bevyengine/bevy#561]
Right now, the signature of Query.iter is

`pub fn iter(&mut self) -> QueryBorrowChecked<'_, Q>`

However, changing it to

`pub fn iter(&self) -> QueryBorrowChecked<'_, Q>`

still compiles (a lot of warnings suggesting to drop the "mut" in systems appear, though).

This would be good for ergonomics, as instead of declaring queries as mutable in systems we wouldn't have to.
The following example:
```
fn greet_people(
    time: Res<Time>, mut timer: ResMut<GreetTimer>, mut query: Query<(&Person, &Name)>) {
    for (_person, name) in &mut query.iter() {
            println!("hello {}!", name.0);
        }
}
```
would then be:
```
fn greet_people(
    time: Res<Time>, mut timer: ResMut<GreetTimer>, query: Query<(&Person, &Name)>) {
   for (_person, name) in &mut query.iter() {
            println!("hello {}!", name.0);
        }
}
```
You still need to &mut query.iter() as `QueryBorrowChecked.iter()` _does_ take it mutably.

I have the change in a local branch, if my proposal makes sense, I can fix the warnings and open PR and update the docs.

**Comment by cart** [comment]
I agree that we could get away with this today and it would still be safe because we do run-time borrow checking. I ultimately want to remove the run-time checks completely as an optimization, which will require us to rely on lifetimes / mutable borrows. So while its safe now, it would be a breaking to remove runtime checks.

Instead, I think we can start moving the api in the direction it will take with compile-time borrow checking, which should make the api a bit more usable. Specifically, now the Bevy 0.2 has "read only" query traits, we can make "read only queries" immutable borrows (`query.iter()`) and write queries mutable borrows (`query.iter_mut()`)

**Comment by OriolMunoz** [comment]
That makes sense to me :slightly_smiling_face:
