### ISSUE TITLE
Moveable DirectionalLights

### ISSUE THREAD

**Issue by hankjordan** [bevyengine/bevy#5789]
## What problem does this solve or what need does it fill?

`DirectionalLight` shadow casting is tied to the world origin.
If you move a camera too far away from the origin, shadows disappear.

## What solution would you like?

Allow the `Transform` component of any entity with a `DirectionalLight` to apply to its shadow casting.
Then, users could update the transform as the camera moves around the world.

## What alternative(s) have you considered?

You might be able to update the frustrum of the `DirectionalLight` manually, but I was unable to get this to work.

**Comment by rparrett** [comment]
An alternative solution is proposed in #3629

**Comment by superdump** [comment]
I implemented updating the projection based on the camera position here: https://github.com/superdump/bevy/commit/688b265380ef3620a6fcf852de2a76b5fe639ca7 it basically ensures the view frustum is covered but quality is poor because there’s too little shadow map resolution close to the camera and too much far away. So I wanted to instead get cascade shadow maps working.

**Comment by ramirezmike** [comment]
>You might be able to update the frustrum of the DirectionalLight manually, but I was unable to get this to work.

In case anyone wanted to try this approach, I experimented with this a bit. The DirectionalLight transform's translation seems to have no effect, but the rotation does. Once you have your rotation set for the angle of shadows, you just need to update the "box" in [DirectionalLight's](https://docs.rs/bevy/latest/bevy/pbr/prelude/struct.DirectionalLight.html) [shadow_projection](https://docs.rs/bevy/latest/bevy/render/camera/struct.OrthographicProjection.html) to cover where you're looking.

This might be tricky depending on what you're trying to do, but in my game I have a car heading in the positive x-axis direction, so I added a system that updates the directional light so that its shadow_projection.left is the car's X coordinate + 100.0 and the shadow_projection.right is the car's X coordinate - 100.0.

Here's a picture of it at the origin and then after driving to 2,544 X

![shadow](https://user-images.githubusercontent.com/1421719/193458421-64c4dcd3-43a7-404e-afae-8a5ae6b7ed7b.jpg)
