### ISSUE TITLE
Touch input does not report window

### ISSUE THREAD

**Issue by aevyrie** [bevyengine/bevy#6011]
## Bevy version

0.8

## What you did

Read touch input from `Touches`.

## What went wrong

None of the touch inputs report what window is being interacted with. When registering a touch input on a windowing OS, bevy doesn't distinguish between touches on a primary or secondary window. A potential workaround is to query all windows to find the active one, but this can cause bugs when using multitouch.

## Additional information

Running on Windows 11, though this bug is caused by design, not OS-specific.

**Comment by DevinLeamy** [comment]
Hi, I'd like to solve this issue! 

Adding a `window_id: WindowId` field to `TouchInput` and `Touch` seems natural, but we run into a dependency cycle trying to import `bevy_window::WindowId` into the `bevy_input` crate. Would it be sufficient to instead have a `primary_window: bool` field? Or is some magic we can do to import `WindowId`?

**Comment by aevyrie** [comment]
We need to use the `WindowId` to properly handle multi-window use cases. I'd suggest looking at the other input events that specify the window. It's possible touches need to be moved into the window crate, or lifted out into another crate.

**Comment by DevinLeamy** [comment]
Of the events in `bevy_input`, `Touch` is the only event that would need to report the window where the event is coming from. In other words, it's the only event not driven by a separate input device (eg. `keyboard` or `mouse`). 

The `Touch` event, therefore, is much better suited to being a kind of `Window` event (and be in `bevy_window`) because (like a `CursorMoved` event, for instance) it describes an interaction with a window.

> It's possible touches need to be moved into the window crate, or lifted out into another crate.

I reckon `Touch` should be moved into the `bevy_window` crate.

**Comment by DevinLeamy** [comment]
@aevyrie @alice-i-cecile Does this sound reasonable?

**Comment by aevyrie** [comment]
Yeah, tough call. I agree that touches should be tied directly to windows, similar to cursor events. I think it would be reasonable to keep window events (cursor/touch) in `bevy_window`, then re-export them from `bevy_input` so all input events can be found in the input crate.

**Comment by DevinLeamy** [comment]
Totally agree that all non-window input events that are currently in `bevy-window` (`CursorEntered`, `CursorLeft`, `CursorMoved`) should, at the very least, be exported by `bevy_input`. 

`bevy_window`, however, is dependent on `bevy_input` because of the `close_on_esc(input: Res<Input<KeyCode>>, ...)` system, which makes importing/re-exporting from `bevy_window` by `bevy_input`, a bit of a problem.

We could change `close_on_esc` to use some `WindowESC` event that gets written elsewhere, but that doesn't seem ideal.

> Alternatively, we could take an optional dependency on `bevy_window`, add the info ...

@alice-i-cecile What do you mean by this? Rust doesn't allow circular dependencies, so using an optional dependency on `bevy_window` how do we import `WindowId` into `bevy_input`?

**Comment by NthTensor** [comment]
If you like, I can open a PR fixing the touch system if/when the referenced engine PR is merged.
