### ISSUE TITLE
`Duration` and `Instant` should live in `bevy_time`, not `bevy_utils`

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy#6027]
These are obviously part of our time-like functionality, and should be stored with those functions.

**Comment by DJMcNab** [comment]
The docs page at https://docs.rs/bevy/latest/bevy/utils/struct.Duration.html is terrible.

For context, this is because of https://github.com/bevyengine/bevy/pull/895, which means we re-export `Instant` and `Duration` from [`instant`](https://crates.io/crates/instant).
However, on native platforms (which docs.rs uses), that `Instant` is just a type alias for `std` instant.

This seems like a significant footgun, whether or not we put lipstick on it by moving crates.

**Comment by mockersf** [comment]
A few team actually got their foot gunned during Bevy Jam #2 by using `Instant` from std and discovering at the last instant that they need to use the one reexported by Bevy to work in wasm

**Comment by DJMcNab** [comment]
> at the last instant

Surely you mean the last Instant?

I'm not surprised. It's really haphazard. I certainly didn't know about this.

**Comment by mockersf** [comment]
> > at the last instant
> 
> Surely you mean the last Instant?

Indeed. And don't call me Shirley.
