### ISSUE TITLE
Make bevy_scene dependency on serde optional

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy#6030]
In bevy_scene, the dependency to serde is not optional and the code is always enabled... but it would be nice to make it optional. maybe another PR 🙂

_Originally posted by @mockersf in https://github.com/bevyengine/bevy/pull/6023#discussion_r974714724_

**Comment by LinusKall** [comment]
I've never contributed before, but I would like to give this a shoot!

**Comment by LinusKall** [comment]
Would it be a good idea to make custom ``SceneSerializer`` and ``SceneDeserializer`` implementations in a new module or make variants within the ``serde.rs`` module?

**Comment by alice-i-cecile** [comment]
Thanks! For this particular issue I think we can probably do a very scoped change :) This line is the suspicious one: https://github.com/bevyengine/bevy/blob/2b80a3f279d1273fbcface9e075637fe681a38d2/crates/bevy_scene/Cargo.toml#L24

[Here's](https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html) the reference page I use when mucking about with dependencies.

**Comment by LinusKall** [comment]
Thank you!

I've changed ``serde`` to be optional, but is that enough? Wouldn't it also be necessary to define a feature that we can use to "activate" ``serde`` again?

I'm also uncertain because wouldn't the case of this ``serde`` feature being "deactivated" have to be handled? That is why I'm wondering about custom implementations.

Perhaps I'm just missing something? 😅

**Comment by alice-i-cecile** [comment]
Oh right! You need to add a serde feature, then add it to the top-level `bevy` feature. Check out what was done in these commits: https://github.com/bevyengine/bevy/pull/6023/commits

**Comment by LinusKall** [comment]
Hi,

I've taken a look and it seems like most things could be solved by using ``#[cfg(feature = "serialize)]``. 

The only thing that needs to be handled differently is the ``AssetLoader`` implementation for the ``SceneLoader`` struct, this is because it uses the ``SceneDeserializer`` struct.

I'm thinking that perhaps this implementation and the current ``Plugin`` implementation for the ``ScenePlugin`` could be connected to the ``serialize`` feature.

Then I could make a "blank" Plugin implementation that does nothing when the ``serialize`` feature isn't activated.

Would this be reasonable?

**Comment by alice-i-cecile** [comment]
Yep, that seems basically correct. Feel free to open PRs early (and stick them in draft mode); it's often easier to figure out the exact technical details when there's a change set in front of you :)

**Comment by LinusKall** [comment]
Okay, I'll try opening a PR tomorrow! :)
