### ISSUE TITLE
Cannot easily spawn an entity with one component

### ISSUE THREAD

**Issue by smokku** [bevyengine/bevy#607]
If I try spawning an entity with just one component, I get the following error:
```
error[E0277]: the trait bound `Pawn: bevy::bevy_ecs::DynamicBundle` is not satisfied
  --> examples/balls.rs:69:20
   |
69 |     commands.spawn(Pawn { controller: 1 }).with(Ball {
   |                    ^^^^^^^^^^^^^^^^^^^^^^ the trait `bevy::bevy_ecs::DynamicBundle` is not implemented for `Pawn`
```

I need to spawn a one element tuple:
```rust
commands.spawn((Pawn { controller: 1 },)).with(Ball {
```

There is no way of coming up to that solution from the error message.

Bevy's selling point is ECS ergonomics - i think this needs to be fixed.

**Comment by memoryruins** [comment]
Since there are multiple components in your example, could do `.spawn((Pawn, Ball))`, but I understand there can be a preference to use the methods since it allows quickly commenting out `with`s. `spawn(()).with(component)` works but also isn't entirely ergonomic.

We could add a method like  `Commands::spawn_with(&mut self, component: impl Component)`, and then `spawn` could be renamed to `spawn_with_bundle` for clarity.

To add `spawn_with` to your app today, an option is to use a function or add this to an extension trait.

```rust
trait CommandsExtension {
    fn spawn_with(&mut self, components: impl Component) -> &mut Self;
}

impl CommandsExtension for Commands {
    fn spawn_with(&mut self, component: impl Component) -> &mut Self {
        self.spawn((component,));
        self
    }
}

fn system(mut commands: Commands) {
    commands.spawn_with(Pawn);
}
```

Note: make sure during bevy upgrades that any new inherent methods on `Commands` don't shadow your extension methods' names since Rust will prefer the inherent method first.

**Comment by visualcode-t** [comment]
Another simple current option is to just create a tuple with a bool.

**Comment by cart** [comment]
Yeah there is unfortunately no way to make spawn() work with both tuples and individual components (because a component could be, itself a tuple). So they are ambiguous to rustc.

I like @memoryruins idea to make "bundles" a clear part of the api and to add a new api for spawning single components.

**Comment by smokku** [comment]
Thank you for the explanation.
I also like the idea of making the bundle spawning more clear. "Explicit is better than implicit."

BTW, I didn't know you can extend an imported type like that. Thank you @memoryruins for this example. :-)

**Comment by CleanCut** [comment]
This sounds like a fun change to make, so I figured I'd give it a shot. Please take a look at https://github.com/bevyengine/bevy/pull/611 and let me know if I'm going in the right direction.

**Comment by alice-i-cecile** [comment]
This is fixed now that #611 is merged in and can be closed.

**Comment by memoryruins** [comment]
#611 was closed, not merged. The discussion in it contains good points to consider when this issue is picked back up again.

**Comment by alice-i-cecile** [comment]
This should be greatly improved or closed by #1562.

**Comment by ledyba** [comment]
https://github.com/bevyengine/bevy/pull/1703 (seems improved version of https://github.com/bevyengine/bevy/issues/1562 ) has been closed.
So  was this issue solved?

**Comment by alice-i-cecile** [comment]
Yes, you can now do: 
```rust
commands.spawn().insert(MyComponent)
```
No weird tuple shenanigans needed.
