### ISSUE TITLE
Add `app.update_with_instant`

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy#6146]
## What problem does this solve or what need does it fill?

When writing tests (or working with networking or machine learning code), you often want to advance the app a single time, and manually set the new time in order to have precise control over .

## What solution would you like?

```rust
impl App {
   /// Runs the app's schedule once, manually setting the [`Time`] resource to the provided value.
   ///
   /// This is ordinarily done automatically, but setting this time value directly can be useful when writing tests,
   /// dealing with networking code, or similar. 
   fn update_with_instant(&mut self, instant: Instant){
     todo!();
   }
}
```

## What alternative(s) have you considered?

One might attempt to set the `Time` value either before or after calling `app.update()`. Neither will work effectively, as the time will automatically be set during `CoreStage::First`, and that is the value that will be used by your systems.

The actual workaround is to add a system during `CoreStage::First` (but after the ordinary system's time), that sets the `Time` resource directly each time `App::update()` is called.

**Comment by Lucidus115** [comment]
I can't really think of a good way to implement this. Well I have some ideas but they require access to the `Time` resource from the bevy_app crate. The problem is that you need to add bevy_time as a dependency which would cause cyclic package dependency errors because bevy_time depends on bevy_app. Maybe the solution is obvious and doesn't require the `Time` resource directly, I'm not sure.

**Comment by alice-i-cecile** [comment]
IMO put it in `bevy_time` using a trait extension method :)

**Comment by 2ne1ugly** [comment]
Can this issue be closed?
It's not the method itself but it seems like #6159 provided the way to create one by needs
