### ISSUE TITLE
found crate bevy compiled by an incompatible version of rust

### ISSUE THREAD

**Issue by paspielka** [bevyengine/bevy#6262]
## Bevy version
0.8.3

## \[Optional\] Relevant system information
macOS Big Sur
rust version 1.64.0

**Comment by mockersf** [comment]
Could you add more details to your issue?

Also, there isn't a version 0.8.3 of Bevy, where did you find it?

**Comment by paspielka** [comment]
Hey 0.8.3 is a a mistake I meant 0.8.1

**Comment by james7132** [comment]
Reviewing this, Bevy's official MSRV is "latest stable" Rust, which is currently 1.65. If the latest release we have, v0.9.0 cannot compile on 1.65 alongside the prerequisite build dependencies external to Rust/cargo, we can probably keep this issue open. Otherwise this issue is wholly unactionable. As this has been almost a month without further information, I'm closing this issue until @paspielka provides more information.
