### ISSUE TITLE
Don't remove WGPU labels in release mode

### ISSUE THREAD

**Issue by JMS55** [bevyengine/bevy#6389]
## What problem does this solve or what need does it fill?

Debugging graphics often requires RenderDoc or NSight. Using those tools is much easier when every resource and render pass has a label. Debugging graphics also often requires running in release mode, to not get horrible FPS. 

Currently, bevy seems to strip WGPU labels in release mode, making debugging difficult.

## What solution would you like?

Add a feature to keep debug labels in release mode. Or maybe an extra optimized-debug profile or something.

**Comment by inodentry** [comment]
No, disagree. Release mode is for releasing bevy apps. Not something to use just because you want better perf. It shouldn't contain stuff for use doing development.

I agree that bevy is unusably slow when compiled without rust compiler optimizations. Hence, I highly recommend you just add some compiler optimizations to your debug mode config, instead of using release mode for development. Debug mode doesn't have to mean "slow".

Just put this in `Cargo.toml` or `.cargo/config.toml` (the latter might be more convenient, so you don't touch files that are tracked by git):
```toml
[profile.dev]
opt-level = 3
```

Keep release mode without dev stuff, please.

**Comment by JMS55** [comment]
Good point, I forgot you could do that. No need for this feature then.
