### ISSUE TITLE
Audio Example doesn't work on web

### ISSUE THREAD

**Issue by DasLixou** [bevyengine/bevy#6836]
Running the [Audio Example](https://github.com/bevyengine/bevy/blob/latest/examples/audio/audio.rs) on the [bevy website](https://bevyengine.org/examples/audio/audio/), but it doesn't play the music.

**Comment by minecrawler** [comment]
Also no audio for me:
![image](https://user-images.githubusercontent.com/1130708/205441392-7000f332-f53d-4bbf-99fb-9d35521ee8e7.png)

**Comment by harudagondi** [comment]
The audio works only if you refresh and immediately click on the example. This is because audio is not allowed to be played automatically. You must interact with the example the moment before it attempts to start playing the audio. See `AudioContext` in the web docs.

The best solution imo is to force users to click on the game window before starting any example, like how some flash game sites work.

**Comment by DasLixou** [comment]
> The audio works only if you refresh and immediately click on the example. This is because audio is not allowed to be played automatically. You must interact with the example the moment before it attempts to start playing the audio. See `AudioContext` in the web docs.
> 
> The best solution imo is to force users to click on the game window before starting any example, like how some flash game sites work.

I did a simple PR which should resolve that issue. But we should also put a message into the docs somewhere so other people don't run into the same issue

**Comment by mockersf** [comment]
https://github.com/bevyengine/bevy_github_ci_template/issues/17 mentions a workaround on the JS side, maybe something similar can be done directly in rust in bevy_audio

**Comment by SolarLiner** [comment]
Closing this as the chosen solution is to require users adding a piece of JS code for web builds (and is integrated in several templates, including the official one)
