### ISSUE TITLE
Add default values for resources

### ISSUE THREAD

**Issue by wzjsun** [bevyengine/bevy#7006]
## What problem does this solve or what need does it fill?

I am developing a UI framework with bevy, but I find that I have many resources. Adding them to the world is a very troublesome thing, and it is easy to make mistakes. I often forget to add some resources, resulting in an error when running

## What solution would you like?

These resources have implemented Default or FromWorld, I hope to automatically add the default values of these resources in the world when adding the system to the schedule。

I think it is easy to set the default value. Can you consider implementing it.

**Comment by nicopap** [comment]
The proposition is to provide some sort of API to "automatically" add resources a system need when the system is added. I'd be happy to hear why you think this is easy? To me it seems very difficult to do.

I don't think we want this. Because this could be a footgun, for example for some resources that implement `Default`, you sometimes want to provide a different value than the default as initial value. Maybe add a method on systems or `App` so that when a given system is added, its resources are also initialized? (but at this point we might as well just initialize the resources) It could look like this

```rust
fn res_system(res1: Res<MyRes1>, res2: ResMut<MyRes2>, res3: Res<MyRes3>) {

}
fn res4_system(res4: Res<MyRes4>, res5: ResMut<MyRes5>, res6: Res<MyRes6>) {

}
fn main() {
  // ...
  app
    // Need to manually add MyRes1 MyRes2 MyRes3
    .add_system(res_system)
    // MyRes4 MyRes5 and MyRes6 are automatically added
    .add_system_and_resources(res4_system)
    // alternative:
    .add_system(res4_system.with_resources_initialized())
  // ...
}
```

Also, currently bevy **panics** when a resource a system requires is not present, which let the user quickly figure out what is wrong and fix, it's not like it's a subtle problem very hard to figure out and takes hours to fix, what is missing and how to fix it is in the panic message.

**Comment by SkiFire13** [comment]
To expand on why this would be very difficult: currently the implementations for `Res`/`ResMut` are fully generic on `T: Resource`, i.e. implementing `FromWorld` is not required. Thus the code that should do this default initialization has no way to know if it can do so or not.

The only way I can think this would (pseudo) work without the user specifying anything is to use some sketchy autoref-based specialization when deriving `Resource` (and even then it would not always work for generic resources).

**Comment by nicopap** [comment]
@SkiFire13 What about an `InitRes<T: Resource + FromWorld>` system param? It would initialize the resource on addition and otherwise completely act like `Res` for everything. This also makes the initialization explicit as part of the system signature.

**Comment by wzjsun** [comment]
@nicopap 
The usage in my imagination is like this：
```rust
fn res_system(res1: Res<MyRes1>, res2: ResMut<MyRes2>, res3: Res<MyRes3>) {

}
fn main() {
  app
    // Automatically add MyRes1 MyRes2 MyRes3
    .add_system(res_system)
}
```
As you said, we sometimes want to provide a different value than the default as initial value. At this time, we can insert corresponding values before or after adding the system:

```rust
fn main() {
  app
    // Insert different value
    .insert_resource(MyRes1)
    // Because MyRes1 has been inserted, the default value will not be overwritten here
    .add_system(res_system)
    // Even though MyRes2 already has a default value, we still have the opportunity to insert a new value for it
    .insert_resource(MyRes2)
}
```
Although Bevy will throw panic when the current system resources do not exist, adding resources is like a mechanical task, which makes people feel unhappy (this can be an automated work)

In the field where I currently use ecs, in most cases, I want resource to be initialized to a default value. In rare cases, I want it to have a different value. I think it is ergonomic to automatically set a default value for resource.

In terms of implementation, generic specialization should be able to initialize the default value for the resource that implements Default or FromWorld, but not the resource that implements Default or FromWorld. If the value does not exist, it will panic：
```rust
unsafe impl<T: Resource> SystemParamState for ResState<T> {
    default fn init(world: &mut World, system_meta: &mut SystemMeta) -> Self {
       // Panic when the resource does not exist
    }
}

unsafe impl<T: Resource + FromWorld> SystemParamState for ResState<T> {
    fn init(world: &mut World, system_meta: &mut SystemMeta) -> Self {
       // Set default value when the resource does not exist
    }
}

```

**Comment by nicopap** [comment]
1. Not possible in stable rust
2. Even in unstable rust, this requires "specialization" but assigning different behavior to different specialization is not recommended

See <https://play.rust-lang.org/?gist=c2b5c7aa958e4225572ef5d2269881ac>

**Comment by wzjsun** [comment]
Yes, ”specialization“ cannot be used in stable trust, so consider adding resource defaults in the future？（I don't quite understand why it is not recommended to assign different behaviors to different specializations）

**Comment by james7132** [comment]
> I don't quite understand why it is not recommended to assign different behaviors to different specializations

It violates the interface's public facing contract unless extremely well documented and violates the principle of least surprise for API design. Given language features like deref-elision, it's pretty easy to create unpredictable behavior using specialization for otherwise subtle changes. 

Likewise, the behavior of adding a `SystemParam` that initializes a resource introduces ordering uncertainty during app construction. If multiple systems use the same resource initialization parameter, which one runs first? If the `FromWorld` implementation for that type is not idempotent, the behavior of those systems is ill-defined, which, again, leads to subtle bugs.

**Comment by wzjsun** [comment]
@james7132 
OK, I understand roughly what you said, thank you.

**Comment by wzjsun** [comment]
I think an InitRes<T: Resource + FromWorld> param is a good solution, I simply implemented it in my own project and used it in many systems, and everything has been very smooth so far.

**Comment by james7132** [comment]
Even if we had a `InitRes<T>` and `InitResMut<T>`, and even if it's easy enough to implement, this is likely not something we should probably be encouraging given the potential for confusion given how 

It should be possible to implement this in a third party crate if you really want to. `SystemParam` should be implementable outside of bevy_ecs.

Alternatively, if the functionality you have is packagable into a generic plugin. I'd suggest using that instead of relying on a system param to handle your initialization.
