### ISSUE TITLE
rename `bevy_reflect`'s `Array`

### ISSUE THREAD

**Issue by soqb** [bevyengine/bevy#7059]
## What problem does this solve or what need does it fill?

The term "array" in Rust is used most commonly to describe a linear array defined by Rust's array syntax (e.g. `[u8; 4]`) which has a strict, stable in-memory layout. Less frequently and more conceptually, the term may also describe a span of homogeneously-sized elements (typically bytes) in memory (`{ start: *const T, end: *const T }` is occasionally thought of as an array).

We have a data type in `bevy_reflect` (i.e. a variant of `ReflectRef` with a matching trait providing core functionality) called `Array`. Importantly, the `Array` trait is a supertrait of `List`.

Although the trait provides the same core functionality as a Rust array (it has a fixed-length and access-by-index), the name "array" is confusing:
- Types implementing `Array` are not necessarily fixed-length as arrays are. In fact, all types implementing `List` have variable length.
- Types implementing `Array` are not necessarily backed by an array (by either definition) either and this could lead to dissonance trying to understand the relationship between `bevy_reflect` and the type.
  - `Vec` is backed by the second definition of array described above  but this is an implementation detail subject (although unlikely) to change.
  - `LinkedList`s are spatially disjoint, heap-allocated nodes and definitely not arrays except in the most general possible case.
  - `VecDeque` is perhaps the worst offender, implemented IIRC similarly to `Vec` but where the first element of the underlying array is not necessarily the first element in the deque.

## What solution would you like?

Rename the `Array` trait, `DynamicArray`, and the `Array` variant of `ReflectRef`, `ReflectMut` and `ReflectOwned` as well as any conceptual docs using the term "array" in this context.

A name I proposed was `Sequence` inspired by serde's primitive data type of the same name, although the word is rarely used in my experience and serde's sequence does not have to provide a length during serialisation (similar to the `Iterator` trait).

## What alternative(s) have you considered?

Leave name as is. Potential confusion may be mitigated by clear docs.

## Additional context

Originally briefly discussed with @MrGVSV [on discord](https://discord.com/channels/691052431525675048/1002362493634629796/1054847758856626216).

**Comment by alice-i-cecile** [comment]
I'm on board with this rename.

**Comment by soqb** [comment]
perhaps also `Indexable` or `Elements`?

**Comment by alice-i-cecile** [comment]
IMO sequence > indexable >> elements.

**Comment by stefanmitic** [comment]
Just wanna make sure I'm on the right track before I submit anything since I'm new around here (Hi! 😃).

The main affected files are `bevy_reflect/src/array.rs` containing the Array trait and accompanying implementations and `bevy_reflect/src/reflect.rs` containing the enums? And also everything affected by the rename operation.

If this is correct I would like to tackle this change as my first submit. If not could you please point me in the right direction?
Thanks!

**Comment by alice-i-cecile** [comment]
@stefanmitic this seems correct: feel free to make the PR and we'll verify there!

**Comment by MrGVSV** [comment]
Thinking on this some more, I wanted to point out another option could be to separate `List` from `Array`. 

I think the only reason they're connected is because they share similar methods and logic. However, because of this we have a few issues:
1. As mentioned in the issue, `List` implementors break the apparent "contract" that `Array` is fixed-length
2. It's not immediately clear what certain reflection methods expect/return, including (but not limited to) `Reflect::reflect_ref`, `Reflect::get_type_info`, and `Reflect::apply`
3. It's not immediately clear how other traits should be implemented, such as `FromReflect` and `Typed`
4. There is an unfortunate collision between `Array::clone_dynamic` and `List::clone_dynamic`

If we separated them then most of these issues go away. Consumers of `dyn Array` could be more confident that `Array::len` is generally fixed (obviously it's up to the implementor to uphold that), and there would be no question of how those reflection traits work— they work in the same way as for other reflection kinds. 

Additionally, it might make future work simpler since we no longer need to worry about possile complexities around subtraits of subtraits (if any).

The only downside (at least the only one I can think of right now) is that we can no longer pass data around as both `dyn List` and `dyn Array`. However, this is already severely limited as `Reflect::reflect_ref` and friends can only return one or the other. This means that the only way to pass data as both traits is to start with a concrete type and then cast it to the desired trait object. This cannot be done on a `dyn Reflect`, `dyn List`, or `dyn Array` without a concrete type to cast to and from.

And if we really want to, we could add a `List::into_array` method to turn it into something like an `ArrayList(Box<dyn List>)` struct, where `ArrayList` implements `Array` using the contained `dyn List`.

So separating them could be a potential solution here. Any thoughts on this?

**Comment by alice-i-cecile** [comment]
This is a compelling argument: by simplifying the trait hierarchy we can clearly seperate the two different classes of data structure.

I think this is more intuitive and gets rid of complexity that doesn't seem to be pulling its weight.

**Comment by soqb** [comment]
i like this course of action.

i'll leave this issue open for now until one suggesting the split opens up (if not i'll make one myself).

**Comment by soqb** [comment]
closed in favour of #7121.
