### ISSUE TITLE
Teardown/exit systems

### ISSUE THREAD

**Issue by Testare** [bevyengine/bevy#7067]
## What problem does this solve or what need does it fill?

We have systems that run once at the start of an App, the startup systems. What is missing is the opposite: Systems that run once at the end of the program. A specific example of this would be an app that changes terminal state to raw mode at the start, but needs to change it back at the end. Or a game that saves on exit.

## What solution would you like?

I think it would be nice if there were the ability to add exit systems to the App in a similar fashion as the way we add startup systems to the App.

## What alternative(s) have you considered?

You can currently get pretty much the same behavior by having a system with EventReader<AppExit>. Unfortunately, this behavior depends heavily on system scheduling, as once AppExit is written, and game loop completes, the system exits. To run this after the user exits the window, for example, I had to look up the WindowsPlugin and find out that it added the "exit_on_all_closed" system in the CoreStage::PostUpdate stage. Then I had to add the exit system to the `CoreStage::Last` stage.

So, while this might not be the highest priority since this functionality isn't /necessary/ for anything, it would be nice if there was a simpler way to do it where I wasn't worried that I was going to miss the AppExit event being emitted.

## Additional context

I had first asked about this on reddit when trying to figure out a solution to a specific problem of mine: https://www.reddit.com/r/bevy/comments/zzjex9

I've discovered the solution provided, but it has been pointed out this might be a good thing to create an issue for on Github, either to implement exit systems for the App or at the very least provide a little more information on the AppExit page for how to create these exit systems within the current framework.

**Comment by alice-i-cecile** [comment]
This is a good issue. My opinion is that this should just be another schedule (akin to the new startup schedule), which the default runner evaluates once before exiting.

**Comment by AxiomaticSemantics** [comment]
Should consider some some function registration and call it outself of the schedule in bevy_app, for Plugin exit also, like the newly added thread creation and exit handlers.

**Comment by mockersf** [comment]
The rust idiomatic way would be to implement [`Drop`](https://doc.rust-lang.org/std/ops/trait.Drop.html) for all the things that need something to happen. For your terminal mode, you would add a resource `TerminalMode` that would set it back in its `Drop` impl for example.

For a game that saves on exit, that's mostly a bad idea and pretty much no game does it that way: first, you have no actual guarantee that your "on exit" system will actually run, it's just a best effort as there are a lot of way for the user to force exit your game without going through it. Second, writing to a file is a blocking operation, which you don't want to do in a system anyway, so that means starting an async task... and you don't want to do that, you're exiting now. The usual way around that is to have an auto save feature that will write a save file every x minutes / frames / actions / whatever.

**Comment by Testare** [comment]
Those are some valid points! I had not considered implementing `Drop`, nor had I considered that `Drop` would still execute if the app was exited through a window closing, and I have verified that it does indeed work in the code. Perhaps if exit systems are not implemented, a note about *that* would be a good addition to the documentation for `AppExit`?

That said, I still have a couple points to defend this Idea: The biggest one is that I find that this might be a contention point between Rust idioms and ECS idioms: To my understanding, the principle idea of ECS is that behavior is not contained in the components, but in the systems. But perhaps `Drop` might be a special case.

And I'll admit that saving on exit could be a bad idea, the examples of it that I was thinking of actually probably do it through clever use of other systems. Perhaps a better example would be a multiplayer client sending a "LOGOUT" message to the server? While the server would probably eventually get the idea when the client stopped sending keep-alive messages or other input, it's possible they would delay, which could even lead to bad things happening to the player while they weren't connected. It could also prevent the player from logging in on another device until the timeout occurred.

This can still be solved with a `Drop` trait implementation though, so really the thing that needs to be determined is if "Drop" implementations or exit systems would be more idiomatic for the Bevy engine in particular.

**Comment by valaphee** [comment]
And after App.run() you could also do other stuff, which is not resource dependent.

**Comment by Testare** [comment]
> And after App.run() you could also do other stuff, which is not resource dependent.

I've tried this, all the code in the main loop after the call to `run()` doesn't seem to get executed.

**Comment by valaphee** [comment]
> > And after App.run() you could also do other stuff, which is not resource dependent.
> 
> I've tried this, all the code in the main loop after the call to `run()` doesn't seem to get executed.

For winit, you have to configure this with:
`.insert_resource(WinitSettings {
    return_from_run: true,
    ..default()
})`

**Comment by Testare** [comment]
Oooooh, well that's good to know! 

Well, it's good to know we have more ways of configuring this for the app developer side, but if you're trying to vend a plugin for additional game functionality, it's less than ideal to say " be sure to configure your other plugins this way and add this code after the `App.run()`. We have options that can do this by having a system listen to `AppExit` events that runs after exits (Though figuring out scheduling is less than ideal), and we can do it by implementing `Drop` for our components (Which is idiomatic Rust, and might have issues if you have multiples of those components).

I personally still think the major question is still "Should we add explicit exit systems, or should we update AppExit documentation to point out that implementing `Drop` might be more rust-idiomatic, or both?" Once we solve that question, it looks like implementation wouldn't be too complicated.

**Comment by alice-i-cecile** [comment]
Both is my preference, in separate PRs.

**Comment by stephenmartindale** [comment]
Here is some further points of input from a [discussion on *Discord*, this afternoon](https://discord.com/channels/691052431525675048/1063454009769340989).

1. Nothing about `App::run()` suggests it may or may not return:

   - it will return in the *headless* case (or without `winit`)
   - it won't in the default `winit` case
   - it doesn't return `!` (like `std::process::exit()`, which does, and is thus self-documenting) or even something like `Result<!, AnError>` in the `winit`-powered case.
   - its documentation makes no mention of any of the above.

   The user is expected to have "arcane knowledge" – In Safe Rust! – and the compiler cannot help them.

2. There is `winit::WinitSettings::return_from_run` BUT...

   - You must discover that that exists! Likely, one discovers this via [the example: `app/return_after_run.rs`](https://github.com/bevyengine/bevy/blob/v0.9.1/examples/app/return_after_run.rs) which I will discuss, further, later.
   - Its [own documentation](https://docs.rs/bevy/latest/bevy/winit/struct.WinitSettings.html#structfield.return_from_run) basically tells you not to use it.
   - [`winit`'s documentation tells you not to use it, too.](https://docs.rs/winit/latest/winit/platform/run_return/trait.EventLoopExtRunReturn.html#tymethod.run_return)
   - (Aside: I'm guessing that both of those have something to do with work-arounds for Windows SPA apartment-model processes and message-loop limitations...)

   That's a whole lot of nuance for a *Bevy* user to need to know in order to get expected behaviour from `App::run()`!

3. The `WindowClosed` event is very easy to discover in the documentation BUT...

   - It isn't useful. Any system reading it won't be run because the schedule won't be executed once the primary window is down.
   - This is also not mentioned in documentation on `WindowClosed`
   - Neither is a "proper way" presented. In the window-related examples, I found nothing.

4. The aforementioned [`app/return_after_run.rs` example](https://github.com/bevyengine/bevy/blob/v0.9.1/examples/app/return_after_run.rs) is probably the next most discoverable resource BUT...

   - It does not contain any relevant comments or mention the recommendation to avoid using `winit::WinitSettings::return_from_run`.
   - It actively illustrates `return_from_run` as the solution, which it isn't if the documentation (and `winit`'s) are accurate.
   - it would not substitute for `WindowClosed` because, by that time, the entities are gone from the ECS

**Comment by alice-i-cecile** [comment]
Awesome summary. I would love to see a PR or 4 tackling those docs issues, although there's clearly fundamental issues with how this is designed.

**Comment by stephenmartindale** [comment]
@alice-i-cecile : I have partially addressed the missing docs. (№ 1 and № 2) along with adding a disclaimer to `app/return_after_run.rs` in https://github.com/bevyengine/bevy/pull/7228

**Comment by alice-i-cecile** [comment]
@here, I'd appreciate a second set of eyes on #7228: I think this will help significantly with the confusion (even though I still want a first-class feature for this).

**Comment by Testare** [comment]
I know I'm a little late to the party, but the documentation clear up in that commit looks good for clearing up the confusion with why code doesn't always execute after `App::run()` =]

**Comment by Testare** [comment]
Created the PR to mention `Drop` in the documentation for `AppExit`, as well as link to the information about App:run() not returning added by @stephenmartindale. #7347

I was going to add information about how the `Windows` systems that write `AppExit` events are scheduled in `CoreStage::PostUpdate`, and putting exit systems in `CoreStage::Last` would probably be best, but I believe that stages are on the way out anyways...

**Comment by Testare** [comment]
Decided to try implementing it myself and put out a PR! But it looks like I'll need to wait for stageless to be merged before it can actually be implemented. Also sounds like it is still "`S-Controversial`" whether/how this should be implemented...

In any case, it seems like the conversation is continuing in the PR #7355.

**Comment by Testare** [comment]
Closing this issue. The main desire has been fulfilled, documentation has been updated to better direct those in the future, the main use case has problems such as dubious support on different platforms, and the edge cases that we might try to solve later and being solved by other features (like  #7857).

**Comment by rlidwka** [comment]
> Closing this issue. The main desire has been fulfilled

There are exit systems now? Can you link to relevant documentation?

I actually need to tear down FFI resources in a particular order at the end of the program, and I haven't found anything relevant in Bevy docs so far.

**Comment by rlidwka** [comment]
> Are you able to handle tearing down FFI resources through a rust Drop trait on a resource?

Yes. But I need them to be dropped in a specific order. So I have to rely on the fact that bevy resources are dropped in the reverse order to how they are inserted. I would hope to solve that issue with exit systems ordering.

**Comment by Testare** [comment]
I closed the PR I made for this #7355. In that PR concerns were raised that exit systems have no guarantee of being executed on certain platforms or in response to certain user actions, and using feature flags would not work to solve this issue.

A more likely candidate is #8595. You can review it and push for it to be merged, would that not solve the problem just as well?

**Comment by Testare** [comment]
I also haven't tested this, but you can also try making an "FfiTeardown" schedule, and then adding that to the main schedule using [MainScheduleOrder](https://docs.rs/bevy/latest/bevy/app/struct.MainScheduleOrder.html) after the `Last` schedule?

**Comment by rlidwka** [comment]
> I also haven't tested this, but you can also try making an "FfiTeardown" schedule, and then adding that to the main schedule using [MainScheduleOrder](https://docs.rs/bevy/latest/bevy/app/struct.MainScheduleOrder.html) after the Last schedule?

I have no idea what that supposed to help with... Anyways, I have a workaround via `Drop`, which works for now (until someone looks at it funny). So I think we can put this issue to rest until someone else needs it.

**Comment by dubrowgn** [comment]
I just wanted to add my +1 for this feature. My use cases are sending bidirectional disconnect messages on exit, and shutting down other threads gracefully.

Drop may be idiomatic rust, but as mentioned by @Testare, it's not idiomatic ECS. If I bring something up in a and ECS system, I would expect to bring it down in an ECS system. Systems give you access to the entire ECS world in a way that drop just can't. Not to mention you can't implement drop on external types, so you have to wrap those resources and box/unbox all of their usages, just so you can implement what bevy already does really well: the ability to run a function against the ECS world.

An "exit" schedule would be more intuitive, you get access to all the ECS world stuff the same way as always, and you don't have to futz with any wrapper types. Seems like a win to me.

**Comment by joshka** [comment]
Hey there, I'd like to reopen this issue for more comments / use cases.

In https://github.com/joshka/bevy_ratatui/pull/6 (bevy_ratatui makes it possible to write a bevy app that targets the terminal)

Terminal apps need:
- deterministic order of startup and shutdown
  - Alternate screen mode (e.g. the mode that neovim puts you in where the information displayed does not affect your terminal when exiting)
  - Raw mode (i.e. immediate reaction to keyboard input, and ignore newline characters etc.)
  - Mouse capture (report mouse events on the std input)
  - Various extra protocols (like kitty text protocol which allows reporting of key release and repeat events)
- configuration of the above items in a way that works for plugin startup

Looking at the current implementation, the Startup systems are run specially in the main schedule by using a local bool to detect if it's the first time run. The startup labels have their own storage in the MainScheduleOrder:
```rust
pub struct MainScheduleOrder {
    /// The labels to run for the main phase of the [`Main`] schedule (in the order they will be run).
    pub labels: Vec<InternedScheduleLabel>,
    /// The labels to run for the startup phase of the [`Main`] schedule (in the order they will be run).
    pub startup_labels: Vec<InternedScheduleLabel>,
}
```

I wonder if it might make sense to add a shutdown labels section (I'm using shutdown instead of teardown / exit as it seems to make more sense that those terms to me - correct me if I'm wrong here), and perhaps replace Main::run_main() with Main::run_startup(), Main::run(), Main::run_shutdown(), which are called in the right order by the runners.

I'm not 100% certain I quite understand well enough to interaction between these pieces to work out what exactly needs adding to make this idea work and whether this is a sane idea.

Other scenarios that would need to also be handled in a way that's order dependent:
- logging (tracing) likely always needs to be the one of the absolute last things that shuts down (I call this out specifically, as in a Ratatui app, we don't want the default logging approach to log to the terminal, so these logs will likely go to an in memory buffer for display as well as to a file, which needs to be closed out correctly).
