### ISSUE TITLE
Document how to configure cascaded shadow maps in different situations

### ISSUE THREAD

**Issue by superdump** [bevyengine/bevy#7362]
In the cascaded shadow maps #7064 PR, there were some situations raised that require or would benefit from different cascade configuration to the default which focuses on a perspective camera at head height.

One example was a top-down or isometric type view where a lot of the scene objects are within a small depth range and distributed across the screen with no objects close to the camera. In this case probably fewer or even just one cascade with a higher shadow map resolution could be a better choice.

I think it would be good to try out such situations, tweak the settings, maybe adjust the projection’s near plane as @robtfm suggested in the PR discussion as that impacts the view frustum and if I remember correctly also the cascade projection bounds.

**Comment by rparrett** [comment]
Here's a little playground I was using: https://gist.github.com/rparrett/0b8a2de7443d41941ad6463e2a42c331

<img width="1280" alt="image" src="https://user-images.githubusercontent.com/200550/214649173-afc386ff-32c1-4d5c-a08a-61ceb09175bc.png">

I'm not sure if the cascades are following the near plane.

**Comment by danchia** [comment]
@rparrett you're right - it currently doesn't follow the near plane, but that shouldn't be too large a change. Just need to fix this https://github.com/bevyengine/bevy/blob/c9a53bf5dd7e6ff628b97d4011039f1780878137/crates/bevy_pbr/src/light.rs#L378 line most likely.

@superdump if it feels more natural, I think it would make sense to allow users to configure the near plane direct in `CascadesShadowConfig`

**Comment by rparrett** [comment]
> Just need to fix this

I attempted that (I think the other bounds need the near plane added as well), but I think there must be something more to it, because the shadows were not even wiggling when adjusting the near plane in the playground above.

At the time I believe this might be due to the "raw bounds" being used here:

https://github.com/bevyengine/bevy/blob/c9a53bf5dd7e6ff628b97d4011039f1780878137/crates/bevy_pbr/src/render/light.rs#L1231

But I was in a bit over my head.

Additionally, there's a question over what `shadow_maximum_distance` should mean. If it's meant to be "distance from the start of the first cascade" then I think `calculate_cascade_bounds` needs to be aware of the near plane. Either way, the docs could use a bit of clarification.

**Comment by superdump** [comment]
shadow_maximum_distance is view z distance from the camera position

**Comment by superdump** [comment]
@danchia that sounds reasonable and you’re probably right that that line you referenced plays a significant role in the calculation of the cascade projections.

**Comment by superdump** [comment]
Though perhaps if adjusting that near plane, we’d need to adjust the way the cascades are calculated in general. The first cascade far bound needs to be > the near plane, and then subsequent cascades need to have far bounds coming after that that scale in a sensible way across the range.
