### ISSUE TITLE
texture_binding_array example's WgpuFeature gating is not working

### ISSUE THREAD

**Issue by rparrett** [bevyengine/bevy#7374]
## Bevy version

master

## Relevant system information

m1 macos, compiling for wasm

## What you did

(with [`wasm_server_runner`](https://github.com/jakobhellermann/wasm-server-runner))
`cargo run --example texture_binding_array --release --target=wasm32-unknown-unknown`
open in browser and open javascript console

## What went wrong

I expected to see this friendly error message: <https://github.com/bevyengine/bevy/blob/main/examples/shader/texture_binding_array.rs#L41>

Instead, I see two issues:
1. This example seems to require at least one additional feature: `TEXTURE_BINDING_ARRAY`
2. bevy panics earlier than `setup` anyway, possibly when building `MaterialPlugin::<BindlessMaterial>`
    
    Even when augmenting the feature gate with `TEXTURE_BINDING_ARRAY`, bevy panics before showing the error from the example

**Comment by superdump** [comment]
Good catch! @cryscan this one too? :)

**Comment by Elabajaba** [comment]
Iirc this is because Bevy currently tries to create a wgpu device with unsupported features, because it isn't checking if the adapter supports the features which will cause a panic.

We really need to break up wgpu creation to allow users to query the adapter for supported features before creating the device, as there are going to be times where you don't want to run if an adapter doesn't support a feature, and times where it's fine and you can just fall back to a different path (eg. think using Int16 in shaders as an optimization, and falling back to Int32 if Int16 is unsupported).

**Comment by robtfm** [comment]
seems like the feature we are checking is fine, but it needs to be in main(), after adding default plugins and before adding the material plugin (the material plugin builds the pipeline, which creates the bind group, which panics if the feature is not available).

we're not building a device with unsupported features, rather trying to use features that we haven't requested because they're not supported

**Comment by superdump** [comment]
As noted on Discord, bevy default behaviour on native is to enable all the features of the adapter, as queried by wgpu, that are supported. The only exception is mappable primary buffers as that can have a negative performance impact on discrete GPUs and we can't detect when it will.
