### ISSUE TITLE
Try to optimize `image` crate compile times

### ISSUE THREAD

**Issue by cart** [bevyengine/bevy#76]
We need the ability to load additional image formats (such as hdr images). #75 added support for hdr, ported png over, and added the (potential) to support a bunch of other formats. Sadly compile time also had a measurable regression:

```
optimized dev build:
before: 239 deps, 2m 17s
after: 252 deps, 2m 50s
```

`image` seems like the best crate for the job and is the de-facto ecosystem standard, but we should try to figure out what makes it so expensive and investigate ways to cut down the cost.

Macroquad is also using it and they have great compile times, so we might be able to learn from their usage.

**Comment by bushrat011899** [comment]
I think this issue has been inadvertently addressed over the year. I just did a quick benchmark on my own development machine (laptop, i5-1240p, 32GB of RAM, Windows 10), and `image` doesn't appear to be a bottleneck to compilation time for `bevy_render` right now.

Below is the output when running `cargo clean; cargo build --release --timings` in the `bevy_render` crate (after filtering out anything that compiles in less than 5 seconds).

<html><body>


Targets: | bevy_render 0.12.0-dev (lib)
-- | --
Profile: | release
Fresh units: | 0
Dirty units: | 231
Total units: | 231
Max concurrency: | 16 (jobs=16 ncpu=16)
Build start: | 2023-08-21T22:25:28Z
Total time: | 97.2s (1m 37.2s)
rustc: | rustc 1.71.1 (eb26296b5 2023-08-03)Host: x86_64-pc-windows-msvcTarget: x86_64-pc-windows-msvc


</body>
</html>

![bevy_render](https://github.com/bevyengine/bevy/assets/2217286/8bb89dab-b39f-4c0c-b270-5fe533414e5f)

The `image` crate takes 10 seconds to compile, out of the total 97 seconds. However, it's not blocking the compilation of any other crates; `wgpu`, `serde`, and their dependencies take the entire build time, with `image` happening simultaneously. If I'm understanding this data correctly, that would mean even getting `image` to zero seconds wouldn't actually affect the total build time of `bevy_render`. 

Ideally, @cart could perform the same benchmarks they did when opening this issue to compare to confirm my suspicions?

**Comment by mockersf** [comment]
The critical path will depend on the number of cores you have. In your case, with 16, you have enough to build enough crates in parallel that `image` is not blocking. It's still taking almost 10 seconds, which is not good, but sadly not among the top contender anymore...

**Comment by bushrat011899** [comment]
> It's still taking almost 10 seconds, which is not good, but sadly not among the top contenders anymore...

This is why I think this issue might need to be updated or closed. It sounds like the problem is no longer trying to speed up `image`, but rather anything that would have a significant impact on compilation time.

**Comment by bushrat011899** [comment]
To follow-up, I've re-run the exact same test, except limiting the number of concurrent jobs:

```bash
cargo clean; cargo build -j {n} --release --timings
```

# 2 Jobs

<html><body>


Targets: | bevy_render 0.12.0-dev (lib)
-- | --
Profile: | release
Fresh units: | 0
Dirty units: | 231
Total units: | 231
Max concurrency: | 2 (jobs=2 ncpu=16)
Build start: | 2023-08-22T03:21:43Z
Total time: | 264.7s (4m 24.7s)
rustc: | rustc 1.71.1 (eb26296b5 2023-08-03)Host: x86_64-pc-windows-msvcTarget: x86_64-pc-windows-msvc


</body>
</html>

![bevy_render_j2](https://github.com/bevyengine/bevy/assets/2217286/a54f3a64-f243-44b1-9337-84a95134b81e)

# 4 Jobs

<html><body>


Targets: | bevy_render 0.12.0-dev (lib)
-- | --
Profile: | release
Fresh units: | 0
Dirty units: | 231
Total units: | 231
Max concurrency: | 4 (jobs=4 ncpu=16)
Build start: | 2023-08-22T03:39:20Z
Total time: | 156.5s (2m 36.5s)
rustc: | rustc 1.71.1 (eb26296b5 2023-08-03)Host: x86_64-pc-windows-msvcTarget: x86_64-pc-windows-msvc


</body>
</html>

![bevy_render_j4](https://github.com/bevyengine/bevy/assets/2217286/1d2ec40b-9af0-4a08-a9ee-4c063fc70803)

# 6 Jobs

<html><body>


Targets: | bevy_render 0.12.0-dev (lib)
-- | --
Profile: | release
Fresh units: | 0
Dirty units: | 231
Total units: | 231
Max concurrency: | 6 (jobs=6 ncpu=16)
Build start: | 2023-08-22T03:44:13Z
Total time: | 129.0s (2m 9.0s)
rustc: | rustc 1.71.1 (eb26296b5 2023-08-03)Host: x86_64-pc-windows-msvcTarget: x86_64-pc-windows-msvc


</body>
</html>

![bevy_render_j6](https://github.com/bevyengine/bevy/assets/2217286/cb24d145-0bf5-47ad-b557-13a4e18d94be)

# 8 Jobs

<html><body>


Targets: | bevy_render 0.12.0-dev (lib)
-- | --
Profile: | release
Fresh units: | 0
Dirty units: | 231
Total units: | 231
Max concurrency: | 8 (jobs=8 ncpu=16)
Build start: | 2023-08-22T03:47:52Z
Total time: | 118.9s (1m 58.9s)
rustc: | rustc 1.71.1 (eb26296b5 2023-08-03)Host: x86_64-pc-windows-msvcTarget: x86_64-pc-windows-msvc


</body>
</html>

![bevy_render_j8](https://github.com/bevyengine/bevy/assets/2217286/ad8dbeb7-20d9-4562-8fe6-3f9276e9f42e)

# 10 Jobs

<html><body>


Targets: | bevy_render 0.12.0-dev (lib)
-- | --
Profile: | release
Fresh units: | 0
Dirty units: | 231
Total units: | 231
Max concurrency: | 10 (jobs=10 ncpu=16)
Build start: | 2023-08-22T03:51:25Z
Total time: | 108.2s (1m 48.2s)
rustc: | rustc 1.71.1 (eb26296b5 2023-08-03)Host: x86_64-pc-windows-msvcTarget: x86_64-pc-windows-msvc


</body>
</html>

![bevy_render_j10](https://github.com/bevyengine/bevy/assets/2217286/c843c081-3465-476c-a852-658dd2432edc)

# 12 Jobs

<html><body>


Targets: | bevy_render 0.12.0-dev (lib)
-- | --
Profile: | release
Fresh units: | 0
Dirty units: | 231
Total units: | 231
Max concurrency: | 12 (jobs=12 ncpu=16)
Build start: | 2023-08-22T03:54:45Z
Total time: | 104.8s (1m 44.8s)
rustc: | rustc 1.71.1 (eb26296b5 2023-08-03)Host: x86_64-pc-windows-msvcTarget: x86_64-pc-windows-msvc


</body>
</html>

![bevy_render_j12](https://github.com/bevyengine/bevy/assets/2217286/6366a002-c423-43be-a4d2-28ae1e0d3602)

# 14 Jobs

<html><body>


Targets: | bevy_render 0.12.0-dev (lib)
-- | --
Profile: | release
Fresh units: | 0
Dirty units: | 231
Total units: | 231
Max concurrency: | 14 (jobs=14 ncpu=16)
Build start: | 2023-08-22T03:58:11Z
Total time: | 99.0s (1m 39.0s)
rustc: | rustc 1.71.1 (eb26296b5 2023-08-03)Host: x86_64-pc-windows-msvcTarget: x86_64-pc-windows-msvc


</body>
</html>

![bevy_render_j14](https://github.com/bevyengine/bevy/assets/2217286/aa172187-d0f6-4214-b4d4-9d4a874f2f4a)

# 16 Jobs

<html><body>


Targets: | bevy_render 0.12.0-dev (lib)
-- | --
Profile: | release
Fresh units: | 0
Dirty units: | 231
Total units: | 231
Max concurrency: | 16 (jobs=16 ncpu=16)
Build start: | 2023-08-22T04:02:31Z
Total time: | 97.6s (1m 37.6s)
rustc: | rustc 1.71.1 (eb26296b5 2023-08-03)Host: x86_64-pc-windows-msvcTarget: x86_64-pc-windows-msvc


</body>
</html>

![bevy_render_j16](https://github.com/bevyengine/bevy/assets/2217286/f42e9eaf-d4bc-42b1-91b3-acc7d289de05)

# 256 Jobs (Take With Salt!)

<html><body>


Targets: | bevy_render 0.12.0-dev (lib)
-- | --
Profile: | release
Fresh units: | 0
Dirty units: | 231
Total units: | 231
Max concurrency: | 48 (jobs=256 ncpu=16)
Build start: | 2023-08-22T04:09:42Z
Total time: | 107.5s (1m 47.5s)
rustc: | rustc 1.71.1 (eb26296b5 2023-08-03)Host: x86_64-pc-windows-msvcTarget: x86_64-pc-windows-msvc


</body>
</html>

![bevy_render_j256](https://github.com/bevyengine/bevy/assets/2217286/d263959f-f434-442a-912c-bfff8bb5ebba)

# Interpretation

On my machine, it looks like `bevy_render` reaches "peak" concurrency utilisation around 12 jobs. Based on how the "256" job ran, it appears that the minimum possible compilation time for `bevy_render` is around 80 seconds if my particular CPU actually had an unlimited number of cores. This is based on the j256 run taking 100 seconds, and `wgpu` taking 20% longer due to CPU over-utilisation (when compared to j12).

In all tests, it appears the two real bottlenecks are:
* `ash -> wgpu-hal -> wgpu-core -> wgpu` ~80 seconds
* `bevy_reflect -> bevy_ecs` ~20 seconds

In my opinion, these two bottlenecks are the real areas that should be focussed on for improving `bevy_render` compilation time.

**Comment by cart** [comment]
Yeah I'm down to close this. It doesn't seem actionable or particularly helpful.
