### ISSUE TITLE
App crashes at startup

### ISSUE THREAD

**Issue by LiamGallagher737** [bevyengine/bevy#7620]
## Bevy version

main branch 9ef840e

## Relevant system information

```ignore
`AdapterInfo { name: "NVIDIA GeForce RTX 3060 Ti", vendor: 4318, device: 9353, device_type: DiscreteGpu, driver: "NVIDIA", driver_info: "522.06", backend: Vulkan }`
```

```ignore
`SystemInfo { os: "Windows 10 Home", kernel: "19044", cpu: "AMD Ryzen 7 5800X 8-Core Processor", core_count: "8", memory: "31.9 GiB" }`
```
## What you did

Created a new project with the following code
```rs
use bevy::prelude::*;
fn main() {
    App::new()
        .add_plugins(DefaultPlugins)
        .run();
}
```
This is the Cargo.toml
```toml
bevy = { git = "https://github.com/bevyengine/bevy", rev = "9ef840e" }
```

## What went wrong

The app crashed right after the window opened with the following error
```ignore
thread 'main' panicked at 'called glDebugMessageCallback but it was not loaded.', E:\rust\.cargo\registry\src\github.com-1ecc6299db9ec823\glow-0.12.0\src\gl46.rs:4234:5
```

## Additional information

A workaround is to add the following when setting up `DefaultPlugins`

```rs
.set(RenderPlugin {
    wgpu_settings: WgpuSettings {
        backends: Some(Backends::PRIMARY),
        ..Default::default()
    },
    ..default()
}),
```

Here are two relevant discord threads
https://discord.com/channels/691052431525675048/1073274796697198622
https://discord.com/channels/691052431525675048/1073786235996352632

**Comment by alice-i-cecile** [comment]
We should investigate changing the default `WgpuSettings` to the workaround.

**Comment by superdump** [comment]
We just moved to enabling all backends. What I find odd is that it claims to be using the Vulkan backend but hits this panic about GL. I wonder why. Perhaps some probing is done. That has the potential to panic? @cwfitzgerald?

**Comment by cwfitzgerald** [comment]
This is https://github.com/gfx-rs/wgpu/issues/2540

**Comment by Elabajaba** [comment]
Summarizing discussions on this from discord:

This appears to be because it tries to load libEGL.dll and libGLESv2.dll, which means that if it can't find them locally, it also tries searching in your PATH for them, and because Angle is common there's a chance that those are somewhere in your PATH. (https://github.com/google/angle)

The problem is that it's finding old versions of those dlls (because people package Angle once and don't bother updating it...) and trying to use them (and they're so outdated they don't support `glDebugMessageCallback`, they only support `glDebugMessageCallbackKHR`) which seems to be the root cause of this crash.

**Comment by LiamGallagher737** [comment]
This is now fixed after an update for glow.
