### ISSUE TITLE
a lot of new buffers created all the time after #599

### ISSUE THREAD

**Issue by mrk-its** [bevyengine/bevy#764]
**Bevy version**
current master (4645da30c8 or later)

**Operating system & version**
Ubuntu 20.04

**What you did**

Apply this patch to print a line on stdout when new buffer is created:
```
diff --git a/crates/bevy_wgpu/src/renderer/wgpu_render_resource_context.rs b/crates/bevy_wgpu/src/renderer/wgpu_render_resource_context.rs
index ab5048da..2e3df8e6 100644
--- a/crates/bevy_wgpu/src/renderer/wgpu_render_resource_context.rs
+++ b/crates/bevy_wgpu/src/renderer/wgpu_render_resource_context.rs
@@ -185,6 +185,7 @@ impl RenderResourceContext for WgpuRenderResourceContext {
     }
 
     fn create_buffer(&self, buffer_info: BufferInfo) -> BufferId {
+        println!("create_buffer");
         // TODO: consider moving this below "create" for efficiency
         let mut buffer_infos = self.resources.buffer_infos.write();
         let mut buffers = self.resources.buffers.write();
@@ -203,6 +204,7 @@ impl RenderResourceContext for WgpuRenderResourceContext {
     }
 
     fn create_buffer_with_data(&self, mut buffer_info: BufferInfo, data: &[u8]) -> BufferId {
+        println!("create_buffer_with_data");
         // TODO: consider moving this below "create" for efficiency
         let mut buffer_infos = self.resources.buffer_infos.write();
         let mut buffers = self.resources.buffers.write();
```
and run
```
cargo run --example sprite
```

**What you expected to happen**

there should be constant number of buffers allocated

**What actually happened**

New buffers are created all the time (for `sprite` example it is like ~3 new buffers per frame)

**Additional information**

This behavior was introduced in #599 (4645da30c8)

**Comment by mrk-its** [comment]
@julhe could you take a look?

**Comment by julhe** [comment]
Okay, this seems because I made this a `ResMut<>` https://github.com/bevyengine/bevy/blob/f81208adaaf4eb6d87ef053feef87b6cc6a7e11f/crates/bevy_render/src/mesh/mesh.rs#L459

This causes https://github.com/bevyengine/bevy/blob/f81208adaaf4eb6d87ef053feef87b6cc6a7e11f/crates/bevy_render/src/mesh/mesh.rs#L470-L473

to be triggered every frame, finally leading to the constant buffer recreation.

Problem is that I need to have the `Mesh` mutable, to set https://github.com/bevyengine/bevy/blob/f81208adaaf4eb6d87ef053feef87b6cc6a7e11f/crates/bevy_render/src/mesh/mesh.rs#L506

So the only option I see is to store `attribute_buffer_descriptor_reference` outside of `Mesh`, so we can go back to `Res<>`.  

But where? 🤔
