### ISSUE TITLE
`scene_viewer` crashes when running a gltf that includes a camera.

### ISSUE THREAD

**Issue by Elabajaba** [bevyengine/bevy#7889]
## Bevy version

Bevy main 47ddd4a8ce98b20ce14b67f6579b1c201a08bc77

## What you did

Run the `scene_viewer` example with a gltf that includes a camera (exporting the default blender scene and make sure to check Include->Cameras when exporting works)

## What went wrong

It crashes.

## Additional information

```
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: QueryDoesNotMatch(6039v0)', D:\programming\bevy\crates\bevy_render\src\render_phase\draw.rs:268:54
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'Compute Task Pool (7)' panicked at 'A system has panicked so the executor cannot continue.: RecvError', crates\bevy_ecs\src\schedule\executor\multi_threaded.rs:194:60
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', D:\programming\bevy\crates\bevy_tasks\src\task_pool.rs:376:49
thread 'Compute Task Pool (7)' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', crates\bevy_render\src\pipelined_rendering.rs:136:45
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', D:\programming\bevy\crates\bevy_tasks\src\task_pool.rs:376:49
```

**Comment by geieredgar** [comment]
I would have bet it was related to my changes with the prepass shader for shadows thing, but a git bisect led to this commit being the cause: 912fb5886908373db2b7c0140ae15961ccd92f72. I will look into it.

**Comment by geieredgar** [comment]
Ok, found the issue: The problem is that the gltf loader does not create a `Camera3dBundle` which would have included the new `Tonemapping` component. Because it is missing the view query in `queue_mesh_view_bind_groups` does not include the camera and does not insert the required `MeshViewBindGroup` component which later results in the `QueryDoesNotMatch` error inside `draw`.

I will open a PR fixing this.
