### ISSUE TITLE
DynamicScene Serialization broken by Windows-as-Entities

### ISSUE THREAD

**Issue by hankjordan** [bevyengine/bevy#7990]
## Bevy version

`0.10.0`

## What you did

```rust
use bevy::{
    prelude::*,
    scene::serde::SceneSerializer,
};
use serde::Serialize;

fn save(world: &World) {
    let registry = world.resource::<AppTypeRegistry>();
    let scene = DynamicScene::from_world(world, registry);

    let ser = SceneSerializer::new(&scene, registry);

    let mut buf = Vec::new();
    ser.serialize(&mut rmp_serde::Serializer::new(&mut buf))
        .unwrap();
}

fn main() {
    App::new()
        .add_plugins(DefaultPlugins)
        .add_startup_system(save)
        .run();
}
```

## What went wrong

The `DynamicScene` fails to serialize.

`called 'Result::unwrap()' on an 'Err' value: Syntax("no registration found for dynamic type with name bevy_window::cursor::CursorIcon")`

## Additional Information

It is only possible to reproduce this bug when there is a window open.

**Comment by MeoMix** [comment]
Thanks for fixing this issue. I'm curious if the problem is more prolific? I run into a similar issue with math:

tfarmpkg-c56c13763289bdd6.js:388 panicked at 'called `Result::unwrap()` on an `Err` value: Message("no registration found for dynamic type with name bevy_math::rect::Rect")', src/scene.rs:308:63

I'm pretty new to playing around with all the scene save/load stuff though, so maybe my expectations of what should / shouldn't work out of the box are incorrect.
