### ISSUE TITLE
100% height nodes overflow below certain window height

### ISSUE THREAD

**Issue by doup** [bevyengine/bevy#8017]
## Bevy version

- 0.11.0-dev (7d9cb1c4ab210595c5228af0ed4ec7d095241db5)

## What you did

- A `root` wrapper with:
```
flex-direction: column;
size: 100% 100%;
padding: 8px
gap: 8px;
background-color: black;
```
- Inside, two rows with:
```
size: 100% 50%;
gap: 8px;
```
- Inside these rows, two columns, each with:
```
size: 100% 100%;
background-color: gray;
```

## What went wrong

**WIDTH** works correctly. But **HEIGHT overflows**.

When window height is big enough, everything is OK:

![image](https://user-images.githubusercontent.com/188612/224271491-bffda9cb-b830-4103-a898-427cb10ccf16.png)

When **window height is below certain value** (not sure which one, maybe `window.height + 2 * gap`?) it start to overflow:

![image](https://user-images.githubusercontent.com/188612/224271799-c3b7a15d-cc29-4381-94ea-c36ace7a1502.png)

## Additional information

Related issues??

- #4237
- #7994

<details>
  <summary><strong>Working HTML example</strong></summary>

```
<!DOCTYPE html>
<html>
  <head>
    <title>Bevy Percent Height</title>
    <style>
      /* Reset */
      * {
        box-sizing: border-box;
      }

      html,
      body {
        padding: 0;
        margin: 0;
      }

      .root {
        display: flex;
        flex-direction: column;
        gap: 8px;
        width: 100vw;
        height: 100vh;
        padding: 8px;
        background-color: black;
      }

      .row {
        display: flex;
        gap: 8px;
        width: 100%;
        height: 50%;
      }

      .col {
        width: 100%;
        height: 100%;
        background-color: grey;
      }
    </style>
  </head>
  <body>
    <div class="root">
      <div class="row">
        <div class="col"></div>
        <div class="col"></div>
      </div>
      <div class="row">
        <div class="col"></div>
        <div class="col"></div>
      </div>
    </div>
  </body>
</html>
```
</details>

![image](https://user-images.githubusercontent.com/188612/224272251-b702a648-4b28-4c44-beb1-50f10f25a99d.png)

**Comment by nicoburns** [comment]
@doup I'll look into this later, but consider using `Stretch` alignment rather than 100% width/height where possible. This example works fine if you remove the `height: 100%` from the inner nodes. Although, having said that, this is really useful for generating test cases for Taffy. So perhaps it is good to continue as you are.

**Comment by nicoburns** [comment]
This is fixed in Taffy `v0.3.7` please `cargo update` to get the fix.

**Comment by doup** [comment]
Shouldn't this be kept open until Taffy is upgraded?

**Comment by nicoburns** [comment]
@doup It doesn’t really need to be because the fix is in a semver-compatible patch release. So users can get the fix by running `cargo update`, and any newly created projects will get it automatically. It’s still a good idea to bump the version req in bevy, but it’s effectively fixed even without that.

**Comment by doup** [comment]
Ah, I though that `X.Y.Z` pinned to patch. I see it's actually a range: `>=0.3.5, <0.4.0` 👍
