### ISSUE TITLE
Scrolling in ui example doesn't work

### ISSUE THREAD

**Issue by rparrett** [bevyengine/bevy#8056]
## Bevy version

0.10, main, bisected to 76058bcf3346e085c0883c892e6111e20657e4f0

## Relevant system information

```
AdapterInfo { name: "Apple M1 Max", vendor: 0, device: 0, device_type: IntegratedGpu, driver: "", driver_info: "", backend: Metal }
SystemInfo { os: "MacOS 13.1 ", kernel: "22.2.0", cpu: "Apple M1 Max", core_count: "10", memory: "64.0 GiB" }
```

## What you did

`cargo run --example ui`

Move pointer over scroll area, two-finger scroll with touchpad

## What went wrong

No scrolling

**Comment by ickshonpe** [comment]
The upgrade to Taffy 3 broke the scrolling list because in Taffy 3 `Dimension::Undefined` is removed and `Val::Undefined` is mapped to `Dimension::Auto`. The example was giving the list container a max height of `Val::Undefined` which previously in Taffy internally would have been translated to  `Dimension::Points(0.)` but now becomes `Dimension::Auto` which means that instead of taking the height of its parent, the list container takes the height of its content that is the height of the entire list. So the list widget believes the list fits inside the container and can't be scrolled.
