### ISSUE TITLE
Reduce/remove the use of  `anyhow` in the engine

### ISSUE THREAD

**Issue by james7132** [bevyengine/bevy#8140]
I'd really like for us to reduce our use of `anyhow`. IMO it's a crate that end-users should be using, not the libraries they're depending on.

_Originally posted by @james7132 in https://github.com/bevyengine/bevy/pull/8065#discussion_r1142590436_

**Comment by paul-hansen** [comment]
I think it's only used for asset loading, I'm guessing there's something it was used to work around or it might just have been easier to get going. Since we don't return these errors to the user it's possible its an okay choice for that use case. 

If possible it _would_ be nice for users to be able to access the Error returned when an asset fails to load. Adding an error field to the [Failed variant of LoadState](https://docs.rs/bevy/latest/bevy/asset/enum.LoadState.html#variant.Failed) would make a lot of sense from an API perspective, but I'm not sure that's feasible since custom assetloaders would need to provide their own error types. Might be able to use boxed traits etc. Example use case of this is for the Bevy editor, being able handle certain asset errors would allow things like clicking on the error message in the Bevy editor and opening up your preferred IDE at the line the error happened on for that asset (for human readable formats).

I've been trying to avoid thinking about this too much until @cart reveals his new asset rework though as he may have already solved this.

**Comment by MrGVSV** [comment]
`anyhow` is annoying, but I see its purpose. It'd be nice if we at least re-exported it so users don't need to add it as dependency themselves when making custom asset loaders.

**Comment by paul-hansen** [comment]
> It'd be nice if we at least re-exported it so users don't need to add it as dependency themselves when making custom asset loaders.

I think this was already done in https://github.com/bevyengine/bevy/pull/5359 !
When implementing `AssetLoader::load` you can now just use:
```rust
fn load<'a>(
        &'a self,
        bytes: &'a [u8],
        load_context: &'a mut LoadContext,
    ) -> BoxedFuture<'a, Result<(), bevy::asset::Error>> {
```

**Comment by cart** [comment]
Yeah anyhow is the tool we currently use when we need an api to accept "any" error. I'm open to something custom that provides a similar API, given reasonable justification.

**Comment by james7132** [comment]
> Yeah anyhow is the tool we currently use when we need an api to accept "any" error. I'm open to something custom that provides a similar API, given reasonable justification.

`std::io::Error` supports this by storing a `Box<dyn Error>` internally, which we can also do, and what `anyhow` does by default. IMO we should be a bit more scoped than transparently returning every possible error.

**Comment by cart** [comment]
Makes sense to me!
