### ISSUE TITLE
Migration guide from X to Y and how to update your code

### ISSUE THREAD

**Issue by troligtvis** [bevyengine/bevy#819]
**What problem does this solve or what need does it fill?**
Avoiding getting a lot of issues on GH where API have changed and give you a panic! _no pun intended_

**Describe the solution would you like?**
Migration guide explaining what has been modified, removed or added between version x to y and how to update your code

**Additional context**
I know that [Bevy news](https://bevyengine.org/news/bevy-0-3/) gave us a blogpost of changes. But it feels like not everyone is going through all the PR to find exactly how the API have been changed, i.e #810  (I had the same thing happening to me just now and went to the issues by chance and found it)

This might just be a nice to have and is not suitable this early in the development. Just by looking at the changes between `0.2.1` and `0.3.0` it has been quite a few 😅 I guess this would be something to think about when we reach a more stable version like `1.0.0` and above :)

**Comment by pksunkara** [comment]
It's a coincidence that I came across this. I know this issue is basically asking a documented version of CHANGELOG, but let me say a few words on how I am planning to do the migration guide on [clap](https://github.com/clap-rs/clap) in the coming future. (I am a  maintainer on it).

Using [rust-analyzer](https://github.com/rust-analyzer/rust-analyzer), I have built a tool called [cargo-up](https://github.com/pksunkara/cargo-up) that can automatically upgrade your code if the dependency describes their changes.

I am planning to finish it off, polish it and then release it when clap v3 releases (currently v2). The main motivation behind the tool is to decrease the churn for users of the library. Once clap v3 is released, users can go to their codebase that uses clap v2 and run `cargo up dep clap` and voila, all the codebase is updated to use clap v3.

It's not documented yet, but if anyone is interested, they can check the current shortcuts for breaking change description [here](https://docs.rs/cargo-up/0.0.3/cargo_up/struct.Version.html) and the actual breaking change description code [here](https://github.com/clap-rs/clap/blob/master/clap_up/src/lib.rs).

**Comment by troligtvis** [comment]
Closing this due to this addition: https://github.com/bevyengine/awesome-bevy/pull/38
