### ISSUE TITLE
Issues opened through Github Discussions "open issue" are  not marked as S-Needs-Triage

### ISSUE THREAD

**Issue by nicopap** [bevyengine/bevy#8646]
I've triaged a couple issues that had 0 labels, and it seems they were converted from discussions.

Is it possible to label those?

**Comment by mnmaita** [comment]
@nicopap I assume this falls outside of the issue templates in the repo so that's why they might be created with no labels. I suppose I could create a) a workflow that runs on every "issue from discussion" event, if there's an event that triggers GH workflows for that or b) a CRON job that marks all unlabeled issues with the needs triage label with a certain periodicity (daily I'd assume). LMK if you are thinking on a different solution so we can find the best one.

**Comment by alice-i-cecile** [comment]
That analysis is correct :) Personally, I'm unsure if it's worth making a tool to fix it; unlabelled is almost as easy to search for as Needs Triage.

**Comment by alice-i-cecile** [comment]
I'm going to call this Won't-Fix. I haven't found this hard to sort through and it's not worth adding another tool to maintain this. Maybe one day Github itself will fix this.
