### ISSUE TITLE
Audio PlaybackSettings volume setting doesn't correspond to human perception of volume well

### ISSUE THREAD

**Issue by Telov** [bevyengine/bevy#8835]
## Bevy version 0.10.1
If I set volume to 0.01 only then will it be subjectively about 3-5 times quieter than on default. 3-5 as in lowering volume on youtube to 33% or 20%

How to reproduce:

```rust
use bevy::{prelude::*};

fn main() {
    App::new()
        .add_plugins(DefaultPlugins)
        .add_startup_system(produce_sound)
        .run();
}

fn produce_sound(
    audio: Res<Audio>,
    asset_server: Res<AssetServer>
) {
    let sound_effect_1 = asset_server.load("audio/pluck_001.ogg");

    let playback_settings = PlaybackSettings {
         repeat: false,
         volume: 0.003f32, //this value for me lowers sound subjectively to about 2%, try different values
         speed: 1f32,
     };
     audio.play_with_settings(sound_effect_1.clone(), playback_settings);
    }
}
```
audiofile: https://fastupload.io/pKOtqjihV6SkJlH/file

**Comment by harudagondi** [comment]
As far as I understand, this is intentional. The documentation of the original [`rodio`] docs is as follows:

> Changes the volume of the sound.
>
> The value 1.0 is the “normal” volume (unfiltered input). Any value other than 1.0 will multiply each sample by this value.

Audio volume is logarithmic. This means that if the volume is set to 0.01 compared to the original 1.0, the sound will be exactly two times quieter than the default[^1], not 100x quieter.

My opinion is that this isn't a problem. However this should probably be indicated in the documentation. **OR**, probably make a more intuitive setter method based on [`Volume::Relative`].

[`Volume::Relative`]: https://dev-docs.bevyengine.org/bevy/audio/enum.Volume.html#variant.Relative
[`rodio`]: https://docs.rs/bevy_audio/latest/bevy_audio/trait.AudioSinkPlayback.html#tymethod.set_volume

[^1]: If `10^x = 0.01`, then `x = -2`, which means two times quieter.

**Comment by GitGhillie** [comment]
With an amplitude (volume) of 0.01 your power would be 0.01^2 = 0.0001.
Which would be 10,000 times less loud, or 10log(0.0001) = -40 dB which will be very quiet.

**Perceived** doubling of audio goes by every 10 dB, so if we go the other way, -10dB:
10^(-10/10) = 0.1 power ratio, sqrt(0.1) = 0.316 amplitude ratio. So you would have to set the volume to 0.316 to halve the perceived audio.

**Comment by GitGhillie** [comment]
`If I set volume to 0.01 only then will it be subjectively about 3-5 times quieter than on default.`

And when I try this I'm definitely getting different results, 0.01 is barely audible, almost less than 1% on youtube.
So maybe it's not just a documentation issue.

**Comment by GitGhillie** [comment]
@Telov Do you have the same issue with this file? The download link for yours seems to have expired https://github.com/bevyengine/bevy/blob/main/assets/sounds/Windless%20Slopes.ogg
