### ISSUE TITLE
Initialize bevy_gilrs in a background thread

### ISSUE THREAD

**Issue by bjorn3** [bevyengine/bevy#888]
**What problem does this solve or what need does it fill?**

At startup about 180ms is spent enumerating all gamepad devices.

**Describe the solution would you like?**

See title

**Describe the alternative(s) you've considered?**

Most of the time is spent in udev, over which we don't have any control, so optimizing udev won't be possible.

**Additional context**

https://gist.githubusercontent.com/bjorn3/09d26f0455bb22a5f1c8c7d68b6941db/raw/84141ac4a1827d841818ad3cc94085e1dc2e5f40/breakout_release.perf

**Comment by amberkowalski** [comment]
From what I see [`gilrs::Gilrs`](https://docs.rs/gilrs/0.8.0/gilrs/struct.Gilrs.html) is not Send or Sync so this wouldn't be possible, since it's not safe to move across threads. The only solution would be for you (or someone) to see if there are any optimizations that can be made within Gilrs itself.

**Comment by james7132** [comment]
Filed an issue upstream with gilrs: https://gitlab.com/gilrs-project/gilrs/-/issues/130.

An investigation of the backing implementation does seem to suggest it could be made `Send`/`Sync`. Right now it's considered not Send due to `udev` APIs on Linux being `!Send`, but like gilrs' Windows/MacOS implementations it could be sent to a separate worker thread instead.

**Comment by james7132** [comment]
Closing this out as Gilrs already initializes itself on a separate thread internally on all but Wasm, which has it's own threading challenges.
