### ISSUE TITLE
Items marked with `#[world_query(ignore)]` are not stateful in `Query`

### ISSUE THREAD

**Issue by urben1680** [bevyengine/bevy#8892]
It might not be a bug but intended behavior, but in that case it might be worth to consider a change here.

The following code panics:
```rs
#[derive(WorldQuery)]
#[world_query(mutable)]
struct Foo{
    entity: Entity,
    #[world_query(ignore)]
    expensively_calculated: Option<()>
}

let mut app = App::new();
app.world.spawn_empty();
app.add_system(|mut query: Query<Foo>|{
    query.for_each_mut(|mut item|{
        item.expensively_calculated = Some(());
    });
    query.for_each(|item|{
        assert!(item.expensively_calculated.is_some()); //panics, change to expensively_calculated is forgotten
    });
});
app.update();
```
This might be no issue in most cases as many users for-each their query just once, but I think stateful items would offer some use cases for [iter_combinations_mut](https://docs.rs/bevy/latest/bevy/ecs/system/struct.Query.html#method.iter_combinations_mut) where the field contains an expensively calculated value.

```rs
#[derive(WorldQuery)]
#[world_query(mutable)]
struct Foo{
    entity: Entity,
    #[world_query(ignore)]
    expensively_calculated: Option<()>
}

let mut app = App::new();
app.world.spawn_batch([();3]);
app.add_system(|mut query: Query<Foo>|{
    let mut inits = 0;
    let mut combinations = query.iter_combinations_mut();
    let mut init_if_needed = |value: &mut Option<()>|{
        if value.is_none(){
            inits += 1;
            *value = Some(());
        }
    };
    while let Some([mut a1, mut a2]) = combinations.fetch_next() {
        init_if_needed(&mut a1.expensively_calculated);
        init_if_needed(&mut a2.expensively_calculated);
        //make use of values here
    }
    assert_eq!(inits, 3); //panics, was initialized 6 times
});
app.update();
```
The amount of unneeded initialization grows rapidly with the number of entities if the number of entities per combinations remains low. Instead of a number equal to the number of entities as the optimal outcome, it is the binomial coefficient of entities over combination length.

An alternative solution for this issue today is an `HashMap<Entity, Data>` inside the system where the data is stored, though that becomes tricky with parallel iterations.

**Comment by nicopap** [comment]
So for precision. The value returned by `query.get` or iterated over by `query.iter` is `Foo::Item`, not `Foo`.

A `WorldQuery::Item` is stateless. In that it is created on the spot for each iteration of `QueryIter` or return value of `query.get`. It is then immediately deleted as soon as it leaves scope.

This also means that the query item doesn't take any room in memory. It's a "view", a bunch of pointers to relevant memory positions.

I personally wouldn't expect `WorldQuery::Item` to hold internal state. Where would that state go?

What is your use-case? Maybe you have a better alternative than a `HashMap`.  What about storing the "expensively calculated" value as a component on the entity?

Typically your query is limited to "all entities with component x,y,z" `Query<(&X, &Y, &mut Z)>`.

Change this to "all entities with component x,y,z, cache" `Query<(&X, &Y, &mut Z, &mut Cache)>`.

And then use `Cache` like you would be using the `ignore` field in the `WorldQuery` derive.

You need to be careful that the `Cache` exists on the entities you are processing. Ideally, you use a bundle to make sure that those "backstage" components exist on entities with the `X`, `Y` and `Z` components.

This is a pattern often used in bevy. For example, `ComputedVisibility`, `Aabb`, `GlobalTransform` cannot be set by the user. They are computed by an internal bevy system once when their dependencies (`Visibility`, `Transform`) change. Since they are _expansive_ to compute, they are stored in a component and only updated when necessary (using change detection typically). Nothing prevents you from doing something similar with your own components!

**Comment by alice-i-cecile** [comment]
Yeah 🤔 This is an interesting suggestion, but I would be pretty surprised to see an implicitly created `Local` to cache the state here.

I think the correct fix is either the pattern suggested above or to use a `SystemParam` derive instead, adding the data you want to cache as a `Local`.
