### ISSUE TITLE
Spawning a child entity in or after POST_UPDATE won't be properly registred as child of the parent

### ISSUE THREAD

**Issue by lassade** [bevyengine/bevy#891]
**Bevy version**
0.3 (commit fae628797fb2dba7a95a323c44c0118875b87f1c)

**Operating system & version**
Fedora 31

**What you did**
Spawn a child entity during or after POST_UPDATE stage
You should only use the `spawn` function and then manually add the parent ...

**What you expected to happen**
The entity `GlobalTransform` should reflect it's parent movement

**What actually happened**
The entity was sitting still in the origin (0, 0, 0) while it's parent was moving around

**Additional information**

**Comment by SvenTS** [comment]
I think this happened in the following commit: https://github.com/bevyengine/bevy/commit/43aac1a78480e196f9b8b29339a34d78bc44b663

In the parent_update_system (which runs in POST_UPDATE) a query filter was added like this:
`mut changed_parent_query: Query<(Entity, &Parent, Option<&mut PreviousParent>), Changed<Parent>,>,`
Changed is reset after each frame, so the entities in question are no longer picked up in the next frame as before. I think removing Changed here does no great harm, because the system has to verify anyway that the value actually changed (Changed only tracks mutable access).

**Comment by lassade** [comment]
I think you are right but I also thinkg this pr #907 shouldn't be the right call for it. I think the `parent_update_system` should instead run at the end of each stage just like the command buffer;

**Comment by cart** [comment]
> I think the parent_update_system should instead run at the end of each stage just like the command buffer;

It would fix this specific issue, but I would very much prefer to not run the same system in every stage. That seems unnecessary and a bit hack-ey. Ideally I think it makes more sense to make Parent/Child updates transactional to avoid the issue entirely (or remove the Changed filter like #907 does, which is probably the better short term solution).

**Comment by lassade** [comment]
Yeah, I guess the perf won't take that big of a hit

**Comment by alice-i-cecile** [comment]
If #68 is fixed this should be resolved.
