### ISSUE TITLE
Support With<Bundle> rather than just With<Component>

### ISSUE THREAD

**Issue by ItsDoot** [bevyengine/bevy#9215]
## What problem does this solve or what need does it fill?

Now that all `Component`s are `Bundle`s, it seems like this could be done, in theory.
It would potentially reduce Query type complexity:

```rust
pub fn my_system(Query<&Name, (With<Foo>, With<Bar>, With<Baz>)>) {}
// vs
pub fn my_system(Query<&Name, With<(Foo, Bar, Baz)>>) {}
```

## What solution would you like?

Implement `With<T: Bundle>` and `Without<T: Bundle>`, rather than `With<T: Component>`.

## What alternative(s) have you considered?

Continue to work under status quo.

**Comment by IceSentry** [comment]
Here's some prior discussion on the subject https://github.com/bevyengine/bevy/issues/2620

**Comment by alice-i-cecile** [comment]
This is definitely feasible, and should be easy to implement.

However, whether it's a *good* idea is hotly contested. Querying for "all entities with this bundle" is a common pattern in beginners coming from more OOP backgrounds, but tends to push towards less idiomatic, less behavior-first system design.

**Comment by fgrust** [comment]
I just started contribution to bevy, so my question might be a fool. :)

How to bundle in the following case. or should we skip this case?

```rust
pub fn my_system(Query<&Name, (With<Foo>, Without<Bar>)>) {}
```

**Comment by alice-i-cecile** [comment]
That wouldn't be able to be expressed using bundles :)

**Comment by tguichaoua** [comment]
What if instead of `With<T: Bundle>`, we have `With<T: TupleOfComponents>`[^1].

`TupleOfComponents` is a marker trait implemented for single component and for tuple where each members is an component.

So `With<(A, B, C)>` becomes a shortcut for `(With<A>, With<B>, With<C>)` but `With<MyBundle>` is still disallowed.


[^1]: There is certainly a better name than `TupleOfComponents` 😅

**Comment by JMS55** [comment]
Agree with `With<Bundle>` being an anti-pattern. `With<(A, B, C)>` or `With<A, B, C>` would be nice though.

**Comment by CraigPersonal100** [comment]
> This is definitely feasible, and should be easy to implement.
> 
> However, whether it's a *good* idea is hotly contested. Querying for "all entities with this bundle" is a common pattern in beginners coming from more OOP backgrounds, but tends to push towards less idiomatic, less behavior-first system design.

While this is true, it would still be nice as an option for rapid prototyping or very simple games, where modularity isn't as important. It also might help beginners transition by letting them use a more OOP style approach, and then they can refactor later once they realize they want to share behavior across all entities with specific components.

It should be fairly easy to refactor game code that is written with Bundle Queries, and split it into smaller systems for each component.

**Comment by blueforesticarus** [comment]
> > This is definitely feasible, and should be easy to implement.
> > However, whether it's a _good_ idea is hotly contested. Querying for "all entities with this bundle" is a common pattern in beginners coming from more OOP backgrounds, but tends to push towards less idiomatic, less behavior-first system design.
> 
> While this is true, it would still be nice as an option for rapid prototyping or very simple games, where modularity isn't as important. It also might help beginners transition by letting them use a more OOP style approach, and then they can refactor later once they realize they want to share behavior across all entities with specific components.
> 
> It should be fairly easy to refactor game code that is written with Bundle Queries, and split it into smaller systems for each component.

I am having trouble thinking of a case where `With<Bundle>` is useful, since you still need to spell all out the components you need access too. Anytime you might be tempted to do something like `With<MonsterBundle>` you could almost certainly do `With<Monster>`, since your entity needs something identifying it as a monster (and if it doesn't then With<MonsterBundle> would be a footgun anyway). 

_However, if bundle Queries were re-evaluated, then we would also want `With<Bundle>` for consistency._

**Comment by ItsDoot** [comment]
Closing out in favor of #15327 as it better centralizes information, arguments, and the context of today.
