### ISSUE TITLE
resource_removed run condition does not trigger after or_then resource_exists

### ISSUE THREAD

**Issue by andriyDev** [bevyengine/bevy#9239]
## Bevy version

Version 0.11.0

## \[Optional\] Relevant system information

Rust version: cargo 1.70.0 (ec8a8a0ca 2023-04-25)
OS: Windows 10
Using `dynamic_linking` feature and optimizations for bevy as described in the docs:
```toml
[profile.dev.package."*"]
opt-level = 3

[profile.dev]
opt-level = 1
```

## What you did

```rust
use bevy::input::common_conditions::input_just_pressed;
use bevy::prelude::*;

fn main() {
    App::new()
        .add_plugins(DefaultPlugins)
        .add_systems(
            Update,
            remove_my_res.run_if(input_just_pressed(KeyCode::Space)),
        )
        .add_systems(
            Update,
            run_and_clear_on_delete
                .run_if(resource_exists::<MyRes>().or_else(resource_removed::<MyRes>())),
        )
        .insert_resource(MyRes)
        .run();
}

#[derive(Resource)]
struct MyRes;

fn remove_my_res(mut commands: Commands) {
    commands.remove_resource::<MyRes>();
}

fn run_and_clear_on_delete(my_res: Option<Res<MyRes>>) {
    dbg!(my_res.is_some());
}
```

## What went wrong

I want a system that can keep doing something as long as a resource exists, and then clear things up when the resource is deleted. So I add a run condition to my system to run if the resource exists or if the resource was just removed. Then in my system, I switch based on whether my resource is present or not.

What actually happens is that the system only shows the resource existing (in the example, the dbg! always print true). The weirdest part is if I SWAP the order of the `resource_exists` and `resource_removed`, suddenly everything works as expected (in the example, the dbg! prints true until printing false just after the resource is removed). The order of the systems SHOULD NOT matter!

**Comment by andriyDev** [comment]
I made my own versions of `resource_exists` and `resource_removed` to check if maybe Bevy has some special casing for the normal `resource_exists` and `resource_removed` conditions. No such luck! These conditions result in the same (wrong) behavior above.

```rust
fn my_resource_exists<T: Resource>(res: Option<Res<T>>) -> bool {
    res.is_some()
}

fn my_resource_removed<T: Resource>(res: Option<Res<T>>, mut existed: Local<bool>) -> bool {
    if res.is_some() {
        *existed = true;
        false
    } else if *existed {
        *existed = false;
        true
    } else {
        false
    }
}
```

**Comment by tguichaoua** [comment]
This misbehaviour is due to `or_else` being [is short-circuiting](https://docs.rs/bevy/latest/bevy/ecs/prelude/trait.Condition.html#method.or_else) and also because `resource_removed` must be run at least once when the resource exists to set up its internal state (the [`existed` variable](https://docs.rs/bevy_ecs/0.11.0/src/bevy_ecs/schedule/condition.rs.html#633)).
But because `resource_exists` return `true`, `resource_removed` is never called when the resource exists.

`resource_exists::<MyRes>().or_else(resource_removed::<MyRes>())`

|`Res<T>` lifecycle | `resource_exists<T>` | `resource_removed<T>` | `existed` | result |
|-|-|-|-|-|
| didn't exists | return `false` | return `false` | `false` | `false` |
| is created | return `true` | not executed | `false` | `true` |
| exists | return `true` | not executed | `false` | `true` |
| removed | return `false` | return `false` because `existed` is `false` | `false` | `false` |
| didn't exists | return `false` | return `false` | `false` | `false` |

`resource_removed::<MyRes>().or_else(resource_exists::<MyRes>())`

|`Res<T>` lifecycle | `resource_removed<T>` | `existed` | `resource_exists<T>` | result |
|-|-|-|-|-|
| didn't exists | return `false` | `false` | return `false` | `false` |
| is created | return `false` | set to `true` | return `true` | `true` |
| exists | return `false` | `true` | return `true` | `true` |
| removed | return `true` because `existed` is `true`  | set to `false` | not executed | `true` |
| didn't exists | return `false` | `false` | return `false` | `false` |

**Comment by andriyDev** [comment]
Oh dang that makes so much sense! That is a very tricky issue to spot! It would be nice if resource_removed used `Local`  and maybe that could be detected and warned against (although that would probably be way too complicated).

I'll close this since this is just intended (albeit non-intuitive) behavior.
