### ISSUE TITLE
thread 'main' panicked at 'Unable to find a GPU! Make sure you have installed required drivers!', crates\bevy_wgpu\src\wgpu_renderer.rs:37:14

### ISSUE THREAD

**Issue by adminSxs** [bevyengine/bevy#924]
**Bevy version**
0.3.0
**Operating system & version**
Windows 7

**What you did**
when I run the exeample hello_world.rs ,occur `thread 'main' panicked at 'Unable to find a GPU! Make sure you have installed required drivers!', crates\bevy_wgpu\src\wgpu_renderer.rs:37:14`

**Comment by Moxinilian** [comment]
What hardware configuration do you have? Have you checked you've installed the according drivers?

**Comment by adminSxs** [comment]
> What hardware configuration do you have? Have you checked you've installed the according drivers?

![image](https://user-images.githubusercontent.com/15902505/100216520-56ca0700-2f4d-11eb-9f4a-2ca7db6b5cac.png)

**Comment by cart** [comment]
Yeah I have a feeling that your current setup doesn't support Vulkan. You might need to update your drivers. Maybe you need to update your os.

**Comment by memoryruins** [comment]
Because this is Windows 7, it is likely limited to DirectX 11, even though Intel HD Graphics 630 should be able to handle DX12/Vulkan on Windows 10. Currently, Bevy does have have a BackendBit enabled that would allow fallback to DX11.

https://docs.rs/wgpu/0.6.2/wgpu/struct.BackendBit.html#associatedconstant.PRIMARY
https://github.com/bevyengine/bevy/blob/1f3d50619be31578a9ada10778b2f9ffe95d9567/crates/bevy_wgpu/src/wgpu_renderer.rs#L25-L37

One path forward would be to enable DX11 backend and see if it resolves this issue, though note that text is currently rendered incorrectly when DX11 is enabled https://github.com/bevyengine/bevy/issues/758

**Comment by vincenterc** [comment]
hi, @memoryruins , would you please teach me how to enable DX11 backend because my gpu does not support vulkan?

**Comment by mockersf** [comment]
closing to centralise in #3191
