### ISSUE TITLE
drain_filter rename missing from migration guide

### ISSUE THREAD

**Issue by spectria-limina** [bevyengine/bevy#9242]
The migration guide for 0.10 to 0.11 does not cover that the [`drain_filter`](https://docs.rs/bevy/0.10.1/bevy/utils/hashbrown/struct.HashMap.html#method.drain_filter) function on `HashMap`, among others, was renamed to [`extract_if`](https://docs.rs/bevy/latest/bevy/utils/hashbrown/struct.HashMap.html#method.extract_if).

There's a behaviour change so this is not a simple textual replacement.

**Comment by alice-i-cecile** [comment]
This is due to an upstream breaking change in `hashbrown`, as I understand it. I don't think we should be putting serious energy into reporting on / collating changes for those crates, although if one is submitted I'd probably accept it.


 Secondly, migration guide issues should be created at https://github.com/bevyengine/bevy-website.
