### ISSUE TITLE
Missing `remove_by_id`

### ISSUE THREAD

**Issue by WinstonHartnett** [bevyengine/bevy#9261]
The untyped API seems to be missing the comparable `EntityMut::remove_by_id` or `EntityCommands::remove_by_id` methods. There are, however, `World::remove_resource_by_id` and `World::remove_non_send_by_id` for some reason.

**Comment by ryand67** [comment]
I'd love to try this one :)

**Comment by TimoCak** [comment]
i would like to solve this isssue in a decent way as my first contribution but i'm actually really new at bevy. So could someone verify my approach maybe.

I already defined a method called `EntitiyMut::remove_by_id(&mut self, component_id)` which takes a `component_id` and uses the instance of the world attribute to call the already existing method `World::remove_resource_by_id`. With that i can remove the wished component. 
![grafik](https://github.com/bevyengine/bevy/assets/74780331/9cbfd849-f859-447f-9760-5212c53f2ef9)

For `EntityCommands` (if its necessary) i don't have a solution right now.

**Comment by Selene-Amanita** [comment]
@TimoCak There is no `insert_by_id` method on `EntityCommands` either, having `remove_by_id` on `EntityMut` would already be an improvement, don't hesitate to make a PR for it!

I don't think your implementation is right though. I think you're supposed to do something similar to the implementation of the `remove` method, but instead of `for component_id in bundle_info.components().iter().cloned()` you have only one component_id.

**Comment by mateuseap** [comment]
I'd like to work on this and open a PR, if possible :)

**Comment by urben1680** [comment]
I stumbled on these methods missing today as I would like to use them. Currently I consider to instead store `fn(&mut World)` commands instead to generate component removals at a place I don't have the type anymore. Is the PR by @mateuseap still wip?
