### ISSUE TITLE
`MapEntities` reflect macro is unhygienic

### ISSUE THREAD

**Issue by grace125** [bevyengine/bevy#9294]
## Bevy version

0.11

## What you did

Tried to reflect `MapEntities` as such:

```rust
use bevy::{prelude::*, ecs::entity::{EntityMapper, MapEntities}};

fn main() {
    
}

#[derive(Component, Reflect, Default)]
#[reflect(Component, MapEntities)]
pub struct A(Vec<Entity>);

impl MapEntities for A {
    fn map_entities(&mut self, entity_mapper: &mut EntityMapper) {
        for e in self.0.iter_mut() {
            *e = entity_mapper.get_or_reserve(*e);
        }
    }
}
```

## What went wrong

Got error[E0412]: cannot find type `ReflectMapEntities` in this scope

**Comment by MrGVSV** [comment]
This actually is expected behavior. All the `#[reflect]` macro does is prepend `Reflect` to the given identifier (in this case, `MapEntities`) and uses it as normal. Unfortunately, it's not possible for it to know where `ReflectMapEntities` comes from, and so the user needs to manually import it into scope themselves.

This is very briefly mentioned in the [docs](https://docs.rs/bevy_reflect/latest/bevy_reflect/derive.Reflect.html#reflectident).

**Comment by grace125** [comment]
Oh okay, my bad

**Comment by grace125** [comment]
Oh okay, my bad

**Comment by grace125** [comment]
Oh okay, my bad

**Comment by MrGVSV** [comment]
No worries! It's an easy part to miss in the docs.
