### ISSUE TITLE
resource.value is private

### ISSUE THREAD

**Issue by thetrav** [bevyengine/bevy#9305]
## How can Bevy's documentation be improved?

https://docs.rs/bevy/latest/bevy/ecs/system/trait.Resource.html

This documentation shows examples of accessing the resource value via Res.value, however it appears that is a private field.

I'm afraid I'm not clever enough to know the best way to access the value of a resource, I was hoping the reference would tell me

**Comment by nicopap** [comment]
So `value` is not a field of `Res`, but a field of `MyResource`. 

When you do
```rust
#[derive(Resource)]
struct MyResource { value: u32 }

fn read_resource_system(resource: Res<MyResource>) {
    assert_eq!(resource.value, 42);
}
```
You are actually accessing `MyResource.value`, not `Res.value`. This is because `Res` implements the `Deref` trait.

If you have a different resource type, you should directly access the resource type's field like so:
```rust
#[derive(Resource)]
struct Zoobawoop { boopy: u32 }

fn read_resource_system(resource: Res<Zoobawoop>) {
    assert_eq!(resource.boopy, 42);
}
```
Hope this explains how to use `Res`.

**Comment by thetrav** [comment]
Yes my mistake, thanks for your help
