### ISSUE TITLE
WebGL2 rendering broken: correct transform are not used

### ISSUE THREAD

**Issue by mockersf** [bevyengine/bevy#9375]
## Bevy version

`main` since https://github.com/bevyengine/bevy/pull/9254

## \[Optional\] Relevant system information

On WebGL2, all browsers

## What you did

Run one of the 3d examples, easily visible on the `pbr` example

## What went wrong

<img width="1295" alt="Screenshot 2023-08-05 at 12 53 14" src="https://github.com/bevyengine/bevy/assets/8672791/fef54a6b-3d76-4752-add3-7709920923e3">

**Comment by superdump** [comment]
I'll have a look and see if I can find out what's up.

**Comment by superdump** [comment]
Well, my bad for testing the GpuArrayBuffer stuff on WebGL2 via applying the limits. I thought I’d tested it on web at some point and seen it work.

The problem is that WebGL2 GLSL only supports gl_InstanceID which is the index within the range of instances being drawn. So for example, if you’re drawing instances 10..12 in rust notation, the gl_InstanceID values would be 0..2.

naga and wgpu currently don’t implement any workaround for this shortcoming such that the wgsl instance_index builtin gets translated to plain gl_InstanceID. They would have to provide the base instance via a uniform and polyfill this into the shader.

As we’re doing one draw per instance at the moment, this would mean wgpu+naga would have to provide a new uniform per draw. I don’t know if it would do this via a buffer or using the direct uniform submission that exists in GL. Either way, it adds back at least some if not all of the per-draw binding overhead that GpuArrayBuffer and instance_index were trying to avoid.

One way that it would still be achieved on WebGL2 is when we get to the ‘encode instance index into the upper bits of the index buffer indices’ part of batching.

For now I suppose it’s going to be worth testing whether direct uniform submission by value is faster than rebinding a uniform buffer or updating its dynamic offset to see if it’s worth keeping the approach anyway. And a short term fix will be to basically have WebGL2 one way or another go back to a dynamic offset per MeshUniform. Sad.

**Comment by superdump** [comment]
Talking with @cwfitzgerald it sounds like when instance_index is properly polyfilled in naga+wgpu then the uniform for the base index would always be pushed regardless of whether we use it or not, so we may as well use it.

**Comment by superdump** [comment]
And while I was looking into implementing that in wgpu and naga, I noticed that push constants could be used as a workaround for now, as they are translated to uniforms, which is exactly what I would implement anyway. Just that the workaround introduces more ugliness into bevy. :/
