### ISSUE TITLE
UI root nodes are impossible to order

### ISSUE THREAD

**Issue by rparrett** [bevyengine/bevy#9791]
## Bevy version

main (0.12-dev)

## What you did

Spinning this issue off from testing in #9764.

```rust
use bevy::prelude::*;

fn main() {
    App::new()
        .add_plugins(DefaultPlugins)
        .add_systems(Startup, setup)
        .add_systems(Update, add_another_component)
        .run();
}

fn setup(mut commands: Commands) {
    let style = Style {
        width: Val::Percent(33.33),
        ..Default::default()
    };

    commands.spawn(Camera2dBundle::default());

    commands.spawn((
        NodeBundle {
            style: style.clone(),
            background_color: Color::RED.into(),
            ..Default::default()
        },
        AnotherComponent,
    ));

    commands.spawn(NodeBundle {
        style: style.clone(),
        background_color: Color::GREEN.into(),
        ..Default::default()
    });

    commands.spawn((
        NodeBundle {
            style: style.clone(),
            background_color: Color::BLUE.into(),
            ..Default::default()
        },
        AnotherComponent,
    ));
}
```

## What went wrong

Nodes appear in order R-B-G. There's no ordered storage for them like `Children` for non-root nodes. They are added to taffy in the order of query iteration.

## Additional information

This could be fixed by something like #8574.

**Comment by nicoburns** [comment]
https://github.com/bevyengine/bevy/pull/9637 makes root nodes render entirely independently of each other (with `Taffy.compute_layout` called separately on each root), which I reckon is the way to go here. Then the order doesn't matter, except for z-order.

**Comment by ickshonpe** [comment]
Yeah this a priority issue I think. It might seem trivial but it's natural for users to assume the ordering of UI entities is stable. It would be easy for someone to waste hours and hours debugging a layout where nodes get reordered when they add a marker component. Especially if the reordering causes a UI node to render underneath another node and disappear.

**Comment by nicoburns** [comment]
Now that #9637 has landed, the example (adding `height: Val::Percent(100.0)` to make it render anything at all) renders as follows:

Before:
<img width="1392" alt="Screenshot 2023-09-19 at 23 32 14" src="https://github.com/bevyengine/bevy/assets/1007307/518c0937-95b4-4bab-8765-10dc433674c8">

After:
<img width="1392" alt="Screenshot 2023-09-19 at 23 32 15" src="https://github.com/bevyengine/bevy/assets/1007307/a90ad770-23b4-4265-9db3-9b8d3db10670">

So the nodes render on top of one another, and x/y layout is unaffected by node order. The z-ordering is still affected and unstable due to this issue, but this can be overridden using the `ZIndex` component.

**Comment by rparrett** [comment]
#9637 definitely fixes or at least makes this redundant in my eyes.
