### ISSUE TITLE
Remove `ZIndex::Global`

### ISSUE THREAD

**Issue by ickshonpe** [bevyengine/bevy#9875]
## What problem does this solve or what need does it fill?

* It doesn't seem very useful, particularly since #9637 was merged.

* Almost no one seems to use it. I can't think of anything it allows you to do, that you can't do without it. CSS only has a local ZIndex.

* It's quite expensive for something no one uses. `ui_stack_system` constructs a new tree of `StackingContext`s each update. Without `ZIndex::Global`, we could update the UI stack in a single walk of the layout tree.

## What solution would you like?

Remove it.

**Comment by oceantume** [comment]
I agree that global z-index is not necessary. There are other ways to achieve what it brings to the table, so it's not a necessary feature, especially if it comes a measurable performance hit even when unused.

It's not true that Web (CSS) only has local zindex though. That would imply that a child can't render on top of its parent, which is possible. Instead, it has a pretty complex system of [stacking contexts](https://web.dev/learn/css/z-index/) with rules that are notoriously hard to reason about. When I worked on this feature I didn't want to replicate that complexity, but I still added global z-index because I figured it could be useful as a simplified system. 

Whether this really is a desired feature is debatable though. On simple UIs it's generally not needed, but on the Web, this is often used for rendering deeply nested dropdowns and modals on top of everything else without having to add them to the root (body), and keeping the hierarchy which has effects other than just positioning and ordering (e.g. style inheritence, selectors, etc)

**Comment by ickshonpe** [comment]
> I agree that global z-index is not strictly necessary. There are other ways to achieve most of what it brings to the table at the moment by using multiple roots, so it's not a necessary feature, especially if it comes a measurable performance hit even when unused.
> 

I think I've solved this so that we can have `ZIndex::Global` has no significant performance cost. Just working on a new implementation.

> It's not true that Web (CSS) only has local zindex though. That would imply that a child can't render on top of its parent, which is possible. Instead, it has a pretty complex system of [stacking contexts](https://web.dev/learn/css/z-index/) with rules that are notoriously hard to reason about. When I worked on this feature I didn't want to replicate that complexity, but I still added global z-index because I figured it could be useful as a simplified system.
> 

Ah ok, my naive understanding of CSS was that ZIndex was local and created new stacking contexts to rearrange items that shared the same parent, unless there was some other property that created a new stacking context such as `transform`.

> Whether this really is a desired feature is debatable though. On simple UIs it's generally not needed, but on the Web, this is often used for rendering deeply nested dropdowns and modals on top of everything else without having to add them to the root (body), and keeping the hierarchy which has effects other than just positioning and ordering (e.g. style inheritence, selectors, etc)

I strongly prefer the simplicity of ordering elements only by their position in the layout tree. Perhaps with the right API there might be a better way to do propagation of properties and events etc across the hierarchy without `ZIndex::Global`, I'm not sure.

**Comment by ickshonpe** [comment]
Okay changed my mind on this but not exactly:
`ZIndex::Global` should definitely be removed, `ZIndex` shouldn't be an enum. 
Instead, we have a separate `GlobalZIndex` component. This fixes all the remaining performance issues.

**Comment by viridia** [comment]
@ickshonpe Wanted to mention that `ZIndex` is the only ui component that doesn't implement `PartialEq`. This came up because I was writing unit tests for styling which needed to compare results.
