### ISSUE TITLE
Consider using Mint for external mathmatical types.

### ISSUE THREAD

**Issue by StarArawn** [bevyengine/bevy#99]
Instead of forcing people to use nalgebra/glam/etc it might be nice for the external facing math types to use mint which would allow users to use any math library that supports mint:

Mint:
https://github.com/kvark/mint

Math libraries that support mint:
https://github.com/kvark/mint/issues/11

**Comment by cart** [comment]
I'm open to the idea (this isn't the first time I've considered mint), but I'm not yet convinced interop is worth the price of the additional to/from conversion complexity mint adds. I really like how straightforward the glam types are. And folks that want to use other math libs can already convert their types to glam (either by defining their own conversions or by doing PREFERRED_LIB -> mint -> glam).

I'm pretty sure users could get the exact same interop interface (with the same number of conversions), by using a PREFERRED_LIB -> glam converter. The only difference is that glam would be the "interop language" instead of mint.

Additionally mint only provides types, not functionality, so we would need to convert back to glam types internally whenever complex behaviors are required.
