### ISSUE TITLE
add_startup_system_to_stage fails on trivial examples

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy#998]
**Bevy version**

rev = "c7b9ad50970edf7587f97dc574f19e2978784822" 

**Operating system & version**

Windows 10

**What you did**
```rust
use bevy::prelude::*;

fn main() {
	App::build()
	.add_startup_system_to_stage(stage::FIRST, hello_world)
	.add_startup_system_to_stage(stage::PRE_EVENT, hello_world)
	.add_startup_system_to_stage(stage::EVENT, hello_world)
	.add_startup_system_to_stage(stage::PRE_UPDATE, hello_world)
	.add_startup_system_to_stage(stage::UPDATE, hello_world)
	.add_startup_system_to_stage(stage::POST_UPDATE, hello_world)
	.add_startup_system_to_stage(stage::LAST, hello_world)
	.run()
}

fn hello_world(){
	println!("Hello World!")
}
```

**What you expected to happen**

This should prints "Hello World" 7 times.

**What actually happened**

> thread 'main' panicked at 'Stage does not exist: first'

**Additional information**

All stages are broken, but the first trips the panic.

**Comment by alice-i-cecile** [comment]
```rust
fn main() {
    App::build()
    .add_startup_system_to_stage("pre_startup", hello_world)
    .add_startup_system_to_stage("startup", hello_world)
    .add_startup_system_to_stage("post_startup", hello_world)
    .run()
}

fn hello_world(){
	println!("Hello World!")
}
```

Most stages are not included without using the DefaultPlugins. However, the systems listed above are. See: https://github.com/bevyengine/bevy/blob/master/crates/bevy_app/src/startup_stage.rs

Changing the code as above fixes the issue, so this should just be noted in the documentation for the function.

**Comment by cart** [comment]
Glad you sorted it out. This might sound a little unsatisfying, but I'm going to close this out, rather than wait for someone to write the docs. Documentation at this point in the project isn't a "requirement" because these apis are in flux and I don't want to spend too much time writing docs that will quickly become out of date. And I don't want a bunch of issues hanging open for "missing docs".

As soon as documentation becomes a requirement, we will track undocumented symbols and try to drive that number to 0.

**Comment by alice-i-cecile** [comment]
Yep, that's the right call. This issue should be handy for writing those docs when the time comes.
